projectblacklight/spotlight

app/models/spotlight/blacklight_configuration.rb, spec/features/update_appearance_spec.rb
=> Remove saved searches and search history if an exhibit is not searchable

app/assets/javascripts/spotlight/catalog_edit.js, app/controllers/spotlight/resources/upload_controller.rb, app/models/spotlight/custom_field.rb, app/models/spotlight/resources/upload.rb, app/views/spotlight/catalog/_edit_default.html.erb, app/views/spotlight/resources/upload/_single_item_form.html.erb, spec/features/upload_non_repository_item_spec.rb, spec/models/spotlight/custom_field_spec.rb, spec/models/spotlight/resources/upload_spec.rb
=> Allow exhibit specific fields to be populated when uploading a non-repo item

app/controllers/spotlight/catalog_controller.rb, app/models/concerns/spotlight/solr_document.rb, app/views/spotlight/catalog/_edit_default.html.erb, spec/models/solr_document_spec.rb, spec/test_app_templates/catalog_controller.rb, spec/views/spotlight/catalog/_edit_default.html.erb_spec.rb
=> Make configured non-repository item upload fields editable

app/views/spotlight/catalog/_admin_header.html.erb, app/views/spotlight/catalog/new.html.erb, app/views/spotlight/resources/_bookmarklet.html.erb, lib/spotlight/engine.rb, spec/features/add_item_bookmarklet_spec.rb, spec/views/spotlight/catalog/admin.html.erb_spec.rb, spec/views/spotlight/catalog/new.html.erb_spec.rb
Part of #846. After this, downstream applications can implement whatever type of form they want.
=> Make repository items a config option for implementations to override

.travis.yml, app/controllers/spotlight/catalog_controller.rb, app/controllers/spotlight/resources/upload_controller.rb, app/jobs/spotlight/add_uploads_from_csv.rb, app/mailers/spotlight/indexing_complete_mailer.rb, app/models/spotlight/resources/csv_upload.rb, app/models/spotlight/resources/upload.rb, app/views/spotlight/catalog/_edit_default.html.erb, app/views/spotlight/indexing_complete_mailer/documents_indexed.html.erb, app/views/spotlight/resources/upload/_multi_item_form.html.erb, app/views/spotlight/resources/upload/_single_item_form.html.erb, app/views/spotlight/resources/upload/new.html.erb, blacklight-spotlight.gemspec, config/locales/spotlight.en.yml, config/routes.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/resources/upload_controller_spec.rb, spec/features/upload_non_repository_item_spec.rb, spec/fixtures/csv-upload-fixture.csv, spec/mailers/spotlight/indexing_complete_mailer_spec.rb, spec/models/spotlight/resources/upload_spec.rb
Closes #888
This refactors a bunch of the upload class and therefore will unfortunately be totally clobbered by #891.
=> Add multiple non-repository item upload via CSV.

app/helpers/spotlight/main_app_helpers.rb, app/views/spotlight/catalog/edit.html.erb, spec/helpers/spotlight/main_app_helpers_spec.rb, spec/views/spotlight/catalog/edit.html.erb_spec.rb
=> Fixes edit screen inconsistencies

app/views/spotlight/dashboards/_page.html.erb, app/views/spotlight/home_pages/_edit_page_link.html.erb, app/views/spotlight/pages/_edit_page_link.html.erb, app/views/spotlight/pages/show.html.erb
This PR makes the edit and view links for home pages `/:exhibit_id/home/edit` and `/:exhibit_id` respectively.
We need to have separate logic for home pages because they are a singular resource as opposed to the about and feature pages (see rails/rails#1769).
=> Use explicit named routes when linking to the singular HomePage resource

app/assets/stylesheets/spotlight/_catalog.scss, app/forms/spotlight/appearance.rb, app/helpers/spotlight/application_helper.rb, app/helpers/spotlight/main_app_helpers.rb, app/models/concerns/spotlight/solr_document/active_model_concern.rb, app/models/concerns/spotlight/solr_document/atomic_updates.rb, app/models/spotlight/blacklight_configuration.rb, app/views/catalog/_save_search.html.erb, app/views/catalog/_sort_and_per_page.html.erb, app/views/spotlight/catalog/_sort_and_per_page.html.erb, config/routes.rb, lib/spotlight/catalog/access_controls_enforcement.rb, spec/controllers/spotlight/catalog_controller_spec.rb, spec/features/catalog_spec.rb, spec/helpers/spotlight/application_helper_spec.rb, spec/helpers/spotlight/main_app_helpers_spec.rb, spec/models/spotlight/appearance_spec.rb, spec/models/spotlight/blacklight_configuration_spec.rb
I think this fixes #896 
Once I fixed the `#apply_permissive_visibility_filter` issue there were some helpers that were throwing errors.
Not sure if I'm doing the right thing with the `#link_back_to_catalog` override or not, so let me know if you have other ideas.
=> Allow for search results and records to be accessed w/o exhibit context.

app/controllers/spotlight/catalog_controller.rb, app/controllers/spotlight/resources/upload_controller.rb, app/helpers/spotlight/application_helper.rb, app/models/spotlight/resources/upload.rb, app/views/spotlight/catalog/_edit_default.html.erb, app/views/spotlight/resources/upload/_single_item_form.html.erb, lib/spotlight/engine.rb, spec/features/upload_non_repository_item_spec.rb, spec/helpers/spotlight/application_helper_spec.rb, spec/models/spotlight/resources/upload_spec.rb, spec/views/spotlight/catalog/_edit_default.html.erb_spec.rb
fixes #934, by allowing applications to map uploaded fields to multiple fields (e.g. a display field and an indexed, searched field)
=> Allow uploaded field configuration to support mapping to multiple solr fields

app/assets/javascripts/spotlight/blocks/search_result_block.js, app/controllers/spotlight/blacklight_configurations_controller.rb, app/controllers/spotlight/exhibits_controller.rb, app/helpers/spotlight/pages_helper.rb, app/models/sir_trevor_rails/blocks/search_results_block.rb, app/models/spotlight/ability.rb, app/models/spotlight/exhibit.rb, app/serializers/spotlight/exhibit_export_serializer.rb, app/serializers/spotlight/page_representer.rb, app/views/spotlight/pages/_form.html.erb, blacklight-spotlight.gemspec, config/routes.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/blacklight_configurations_controller_spec.rb, spec/features/import_exhibit_spec.rb, spec/features/javascript/search_result_block_spec.rb, spec/helpers/spotlight/pages_helper_spec.rb, spec/models/spotlight/exhibit_spec.rb, spec/serializers/spotlight/exhibit_export_serializer_spec.rb
Fixes #894 
I've configured `roar` to just replace all data with the provided import. I think that's closer to our use-case than the previous behavior was anyway.
Fixes #939 
Fixes #698
=> Replace activemodel-serializers with roar

app/models/spotlight/exhibit.rb
Fixes #945 ?
Not sure why `HTML::FullSanitizer` works under rspec but it fails when trying to create a new exhibit through the UI.
According to https://github.com/rails/rails-html-sanitizer#usage the appropriate way to invoke the sanitizer is `Rails::Html::FullSanitizer.new`.
=> Use ::Rails::Html::FullSanitizer in exhibit description sanitization.

app/assets/stylesheets/spotlight/_exhibit_admin.scss, app/models/spotlight/analytics/ga.rb, app/models/spotlight/exhibit.rb, app/views/spotlight/dashboards/_analytics.html.erb, blacklight-spotlight.gemspec, config/locales/spotlight.en.yml, spec/models/spotlight/analytics/ga_spec.rb, spec/models/spotlight/exhibit_spec.rb, spec/views/spotlight/dashboards/_analytics.html.erb_spec.rb
=> Add exhibit-specific analytics dashboard

app/assets/javascripts/spotlight/blocks/featured_browse_categories_block.js, app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss, app/assets/stylesheets/spotlight/_spotlight.scss, app/models/sir_trevor_rails/blocks/featured_browse_categories_block.rb, app/models/spotlight/search.rb, app/views/spotlight/sir_trevor/blocks/_featured_browse_categories_block.html.erb, spec/features/javascript/featured_browse_categories_block_spec.rb
Closes #914 
Still working out some kinks w/ the tests.  Also, @ggeisler can you take a look at the 5 category w/ no-sidebar on different view-ports.  Under certain circumstances I see the categories overlapping.
TODO:
=> Add Featured Browse Categories Widget

app/controllers/spotlight/application_controller.rb, app/controllers/spotlight/pages_controller.rb, app/controllers/spotlight/versions_controller.rb, app/models/spotlight/ability.rb, app/models/spotlight/page.rb, app/models/spotlight/search.rb, blacklight-spotlight.gemspec, config/locales/spotlight.en.yml, config/routes.rb, lib/generators/spotlight/install_generator.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/about_pages_controller_spec.rb, spec/controllers/spotlight/feature_pages_controller_spec.rb, spec/controllers/spotlight/home_pages_controller_spec.rb, spec/controllers/spotlight/versions_controller_spec.rb
=> Add undo/redo support for feature, about, and home pages using paper_trail

app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
Fixes #957 
Updates the SCSS to calculate the image width values based on the Bootstrap container size. In a couple of places I couldn't avoid a using fixed values without just throwing an arbitrary value into the width formula.
Calculates the image height values based on a ratio that applies at all container sizes.
Things still don't look ideal at less than tablet size, but I don't think it's worth the time right now to figure out how to improve the xs size. And it's not ideal that at the smaller widths the smaller images are just as wide as the "large" ones, but in practice I don't think it will be as noticeable as it is in the examples below because presumably curators won't normally put two instances of the widget right next to each other.
=> Replace image width and height values with calculated values

app/views/_user_util_links.html.erb
=> Move and group items differently in user utility links menu.

app/assets/stylesheets/spotlight/_pages.scss
Closes #998 
* Remove top margin from heading
* Add 1px border to images
* At small viewport and smaller, when image grid and heading are stacked, add margin between them
----
----
=> Updates to item grid widget styling

app/views/spotlight/sir_trevor/blocks/_item_text_block.html.erb
=> Replace item+text row w/ clearfix to address alignment.

app/assets/stylesheets/spotlight/_browse.scss, app/assets/stylesheets/spotlight/_header.scss, app/helpers/spotlight/main_app_helpers.rb, app/helpers/spotlight/navbar_helper.rb, app/jobs/spotlight/set_default_thumbnail_job.rb, app/views/shared/_exhibit_masthead.html.erb, app/views/shared/_exhibit_navbar.html.erb, app/views/shared/_header_navbar.html.erb, app/views/spotlight/browse/_search.html.erb, app/views/spotlight/browse/_search_title.html.erb, app/views/spotlight/browse/show.html.erb, lib/spotlight/controller.rb, spec/helpers/spotlight/navbar_helper_spec.rb, spec/lib/spotlight/controller_spec.rb, spec/views/shared/_exhibit_masthead.html.erb_spec.rb, spec/views/shared/_exhibit_navbar.html.erb_spec.rb, spec/views/shared/_header_navbar.html.erb_spec.rb, spec/views/spotlight/browse/show.html.erb_spec.rb
=> Add exhibit-style browse category landing page 

app/assets/javascripts/spotlight/croppable.js, app/assets/stylesheets/spotlight/_croppable.scss, app/assets/stylesheets/spotlight/_spotlight.scss, app/assets/stylesheets/spotlight/typeahead.css, app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/featured_images/_form.html.erb
Closes #978 (sort-of, I don't think this takes care of all the cases we would want, but it's certainly a start)
=> Use jcrop's animated loading icon when images are loading.

app/assets/javascripts/spotlight/croppable.js, app/assets/stylesheets/spotlight/typeahead.css
Fixes #1003 
Make sure auto-complete has a higher z-index than the Jcrop select box and add address Jcrop + turbolinks problem that was causing a javascript error.
=> Jcrop improvements

app/views/spotlight/about_pages/_page_options.html.erb, app/views/spotlight/feature_pages/_page_options.html.erb, app/views/spotlight/home_pages/_page_options.html.erb, config/locales/spotlight.en.yml
Now that we're using bootstrap form on the page edit form we get labels generate for us (which are reasonable enough on their own).
=> Remove extra labels on page options tab.

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss, app/assets/stylesheets/spotlight/_croppable.scss, app/assets/stylesheets/spotlight/_curation.scss, app/views/spotlight/searches/_form.html.erb, config/locales/spotlight.en.yml
Close #1017 
- Improve formatting of edit pages
- Update instruction text for browse category edit, masthead tab
=> Update styling of appearance and browse edit pages

app/views/spotlight/searches/_form.html.erb, spec/views/spotlight/searches/edit.html.erb_spec.rb
Item autocomplete does not work for masthead or thumbnail currently.
=> Fix data attribute that hold autocomplete url on search edit form.

app/assets/stylesheets/spotlight/_header.scss
Closes #1023 
Add styling for image background, general case:
----
And move to left if a search masthead exists (right side gets crowded with menu choices):
----
In action:
=> Update styling of More exhibits link to account for image mastheads

app/assets/stylesheets/spotlight/_header.scss
e.g., when the browser window is way bigger than 1800px wide:
When the window is smaller than the image, the previous behavior still applies.
=> Scale up masthead images to fill full width

app/assets/javascripts/spotlight/block_mixins/autocompleteable.js, app/assets/javascripts/spotlight/blocks/browse_block.js, app/assets/javascripts/spotlight/blocks/pages_block.js, app/assets/javascripts/spotlight/blocks/search_result_block.js, app/assets/javascripts/spotlight/blocks/solr_documents_block.js, app/assets/javascripts/spotlight/blocks/solr_documents_carousel_block.js, app/assets/javascripts/spotlight/blocks/solr_documents_features_block.js, app/assets/javascripts/spotlight/blocks/solr_documents_grid_block.js, app/assets/stylesheets/spotlight/_pages.scss, app/assets/stylesheets/spotlight/_sir-trevor_overrides.scss, spec/features/javascript/blocks/solr_documents_block_spec.rb
Closes #871 
* Renamed widget titles to shorten and make more clear:
* Updated widget descriptions
* Updated widget configuration panels, mostly just to adding spacing and make minor alignment adjustments. I also made the widget titles to always show on open widgets, rather than just showing on hover. I don't see a drawback to doing this (but speak up if I'm missing something) and I think it helps if you forget what widget you're working with, or if you have several widgets open at once.
* I also added a placeholder in the item inputs to make it a little more obvious to a novice curator that they are supposed to type in there to find items.
A couple examples of the updated styling:
----
=> Update widget config panels

app/views/spotlight/pages/_sort_and_per_page.html.erb, app/views/spotlight/sir_trevor/blocks/_search_results_block.html.erb, spec/features/javascript/blocks/search_result_block_spec.rb
=> Hide sort and per-page widgets on the search results widget

app/assets/stylesheets/spotlight/_pages.scss
Closes #1064 
Minor styling updates (first and third examples below are only applicable at small viewport sizes):
----
----
=> Update widget display styling

app/assets/stylesheets/spotlight/_catalog.scss, app/controllers/spotlight/catalog_controller.rb, app/models/concerns/spotlight/solr_document.rb, app/models/spotlight/blacklight_configuration.rb, app/views/spotlight/catalog/_tags_default.html.erb, blacklight-spotlight.gemspec, spec/features/exhibits/add_tags_spec.rb, spec/models/spotlight/blacklight_configuration_spec.rb
Requires https://github.com/projectblacklight/blacklight/pull/1149
Fixes #866
=> Use ordinary facet and show fields for exhibit-specific tags

app/controllers/spotlight/exhibits_controller.rb, app/views/spotlight/blacklight_configurations/edit_sort_fields.html.erb, spec/features/create_exhibit_spec.rb
=> Few minor bug fixes

.gitignore, app/assets/stylesheets/spotlight/_header.scss, app/helpers/spotlight/jcrop_helper.rb, app/uploaders/spotlight/masthead_uploader.rb
Fixes #1126 
Changes masthead height to 180px (from 120px) but only increases total height of masthead+menu a little because this fix also moves the main menu nav on top of the image. This is the case for both the site masthead and the browse category masthead.
This might need some additional styling tweaking after I take a break from looking at it, and probably tweaking when used with the SUL theme. Also, I haven't handled responsiveness of the masthead/menu nav at smaller viewports, but will tackle that later with some other responsive issues.
---
---
---
=> Improve display of site masthead

app/assets/stylesheets/spotlight/_header.scss
Fixes #1130 
Minor CSS updates to ensure the Curated Features dropdown menu items are visible:
(Also made very slight adjustment to text shadow on masthead title/subtitle.)
=> Update main menu dropdown menu (Curated Features) styling

app/views/spotlight/shared/_report_a_problem.html.erb
Another minor update to fix the report a problem form layout, at medium viewport size (this wasn't apparent when manually resizing the browser width to medium, but was when I refreshed the page at medium width):
=> Fix inconsistent column settings on feedback form

app/views/spotlight/pages/show.html.erb
Added column class when there is no sidebar, which gives the page title and content the default 15px left-padding to left-align the content as expected.
=> Ensure 'no sidebar' page header and content is wrapped in column class

app/assets/stylesheets/spotlight/_pages.scss, app/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb
Fixes #1144 
* Check to see if Item Grid has a text block. If not, make the items column take 12 columns instead of 9, so it uses full width of content area
---
* Adjust size of Item Grid boxes to fit more appropriately in available space, depending on whether the page has a sidebar and whether the Item Grid has an associated text block
=> Item grid widget layout updates

app/helpers/spotlight/pages_helper.rb, spec/helpers/spotlight/pages_helper_spec.rb
`available_index_fields` includes exhibit-specific fields. Fixes #1147
=> available_index_fields helper should use blacklight_config

app/assets/stylesheets/spotlight/_pages.scss
Longer text fields used for exhibit contacts wrap under the contact photo, which can create a somewhat disjointed appearance, which as the second contact in this example:
This commit indents the text fields when there is a contact photo to avoid the wrapping:
If a contact doesn't include a photo, the text is not indented:
=> Ensure wrapped contact text fields left align in sidebar

.travis.yml
Do we really need to alert this list for travis builds?
=> Removes SU list notifications for travis builds

app/models/spotlight/resource.rb, lib/spotlight/engine.rb, spec/models/spotlight/resource_spec.rb, spec/models/spotlight/resources/open_graph_spec.rb
I hope this will let us simplify `Spotlight::Resources::DorResource` to just the glue code with `gdor-indexer`.
=> Pull batch indexing and exhibit-specific data logic up from spotlight-dor-resources

app/views/spotlight/search_configurations/_search_fields.html.erb, config/locales/spotlight.en.yml, spec/features/javascript/search_config_admin_spec.rb
Closes #1222 
Moved and renamed the checkbox that enables the search box. Minor update to instructions text to reflect renamed checkbox.
--
--
=> Update text to clarify options for displaying search options

app/controllers/spotlight/exhibits_controller.rb, app/views/layouts/spotlight/home.html.erb, app/views/layouts/spotlight/spotlight.html.erb, app/views/shared/_exhibit_masthead_and_navbar.html.erb, app/views/shared/_flash_messages.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/_modal.html.erb, spec/views/shared/_exhibit_masthead_and_navbar.html.erb_spec.rb, spec/views/shared/_header_navbar.html.erb_spec.rb
This allows us to easily customize the home page downstream
=> Use a different template for the spotlight home page

app/views/spotlight/search_configurations/_default_per_page.html.erb, app/views/spotlight/search_configurations/_document_index_view_types.html.erb, config/locales/spotlight.en.yml
Closes #1234 
Add strings for Curation > Search, Results tab labels
=> Add translations for search results config form labels

.hound.yml, .javascript-style.json, .scss-lint.yml
- Disable CSS selector format style, as many of the elements we style are
outside our immediate control. Fixes #1247.
- Update jshint configuration to require a line length of 120 (to match
ruby-land equivalent; fixes #1246) and add predefined globals for Blacklight
and Spotlight classes
=> Add hound configuration for javascript and css styling

app/assets/stylesheets/spotlight/_browse.scss, app/jobs/spotlight/default_thumbnail_job.rb, app/models/concerns/spotlight/default_thumbnailable.rb, app/models/spotlight/exhibit.rb, app/models/spotlight/search.rb, spec/jobs/spotlight/default_thumbnail_job_spec.rb, spec/models/spotlight/default_thumbnailable_concern_spec.rb, spec/models/spotlight/exhibit_spec.rb, spec/models/spotlight/search_spec.rb
Closes #1004 
Closes #1225 
This adds a `DefaultThumbnailable` concern that is mixed into `Exhibit` and `Search`. This concern adds an `after_create` hook that fetches a default thumbnail asynchronously via the `ActiveJob` queue. Each class that mixes in the `DefaultThumbnailable` concern has to implement how it fetches the default thumbnail (by implementing a `set_default_thumbnail` method).
=> Add a DefaultThumbnailJob and hook it up to Exhibit and Search

app/models/spotlight/exhibit.rb, app/views/spotlight/exhibits/_exhibit_list.html.erb, app/views/spotlight/exhibits/index.html.erb, config/locales/spotlight.en.yml, spec/views/spotlight/exhibits/index.html.erb_spec.rb
=> Display a list of private exhibits on the exhibits index page

app/views/spotlight/exhibits/_exhibit_card.html.erb
=> Use the cropped exhibit thumbnail on the exhibits landing page

app/models/spotlight/featured_image.rb, app/serializers/spotlight/featured_image_representer.rb, spec/serializers/spotlight/exhibit_export_serializer_spec.rb
For some (as yet undetermined) reason, we have some browse categories in the wild with mastheads without attached images. I suspect it's just migration pains, but it seems safe enough to guard against this case anyway.
=> Guard against missing image files

app/views/spotlight/searches/index.html.erb, config/locales/spotlight.en.yml, spec/views/spotlight/searches/index.html.erb_spec.rb
=> Update message when editing browse categories while search is off

app/models/spotlight/blacklight_configuration.rb, app/models/spotlight/custom_field.rb, app/models/spotlight/solr_document_sidecar.rb, db/migrate/20151124105543_update_custom_field_names.rb, spec/models/spotlight/custom_field_spec.rb, spec/models/spotlight/resources/upload_spec.rb
Instead, construct the solr field name with the exhibit prefix on-the-fly for solr.
=> Update custom field names to not contain the field name

spec/factories/pages.rb
When initializing, friendly_id invokes some Rails logic that requires the database to be already migrated:
```
.gem/ruby/2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:511:in `table_structure': Could not find table 'spotlight_pages' (ActiveRecord::StatementInvalid)
from .gem/ruby/2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:385:in `columns'
from .gem/ruby/2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
from .gem/ruby/2.2.3/gems/activerecord-4.2.5/lib/active_record/attributes.rb:93:in `columns'
from .gem/ruby/2.2.3/gems/activerecord-4.2.5/lib/active_record/attributes.rb:98:in `columns_hash'
from .gem/ruby/2.2.3/gems/activerecord-4.2.5/lib/active_record/inheri …
```
=> Update STI-based factories to lazily evaluate the class name to avoid 'Could not find table' errors with friendly_id

app/models/concerns/spotlight/exhibit_documents.rb, app/models/spotlight/blacklight_configuration.rb, lib/generators/spotlight/install_generator.rb, lib/spotlight/catalog/access_controls_enforcement.rb, spec/models/spotlight/exhibit_spec.rb
Instead of using custom logic for picking out all the exhibit's solr documents, use the application's `SearchBuilder` class, which already has that logic.
=> Use the exhibit search builder to retrieve an exhibit's solr documents

lib/tasks/spotlight_tasks.rake
Support a better exhibit import/export experience from the command line by adding the `spotlight:export` rake task, and updating `spotlight:import` to accept a slug as an argument to the task.
=> Add spotlight:export rake task for exporting an exhibit as JSON

app/assets/stylesheets/spotlight/_blacklight_overrides.scss
=> Change the search field selector to use a smaller font size, so it aligns better with the query input

config/locales/spotlight.en.yml
Fixing a couple of minor problems I noticed when updating the wiki pages (arrows point to out of date text):
Before
--
After
-- 
Before
--
After
--
=> Text updates in Admin > Configuration pages

app/assets/stylesheets/spotlight/_header.scss, app/assets/stylesheets/spotlight/_navbar.scss, app/assets/stylesheets/spotlight/_spotlight.scss, app/assets/stylesheets/spotlight/_variables.scss
... that appears over a masthead image. This should make it easier for downstream applications to retheme the navbar, and ensure we're consistently applying styles.(with the ad-hoc approach, we're running into trouble with the `:focus` state not being transparent..)
Before:
After:
=> Copy bootstrap's approach to navbar styling to style the transparent navbar

app/helpers/spotlight/jcrop_helper.rb, app/uploaders/spotlight/featured_image_uploader.rb, app/views/spotlight/appearances/edit.html.erb, app/views/spotlight/exhibits/_exhibit_card.html.erb, lib/spotlight/engine.rb, spec/helpers/spotlight/jcrop_helper_spec.rb
Generated thumbnails should also be a configurable size.
Fixes #1295
=> The site thumbnail should be a square image by default

app/assets/stylesheets/spotlight/_header.scss, app/assets/stylesheets/spotlight/_variables.scss
(Fixing a regression in #1304)
Before:
After:
=> Use a darker background for the page-level masthead

app/models/spotlight/resource.rb
This doesn't seem to scale well for very large collections, and with all
indexing happening through ActiveJob queuing also seems unnecessary.
=> Remove database-level locking when reindexing resources

app/assets/stylesheets/spotlight/_exhibits_index.scss, app/controllers/spotlight/exhibits_controller.rb, app/models/concerns/spotlight/user.rb, app/views/spotlight/exhibits/_exhibit_card.html.erb, app/views/spotlight/exhibits/_exhibit_list.html.erb, app/views/spotlight/exhibits/index.html.erb, config/locales/spotlight.en.yml, spec/controllers/spotlight/exhibits_controller_spec.rb, spec/views/spotlight/exhibits/index.html.erb_spec.rb
=> Add role-based filtering for exhibits displayed on the exhibits index

app/assets/stylesheets/spotlight/_nestable.scss
Follow the 2012 (latest) spec: http://www.w3.org/TR/css3-images/#linear-gradients
This prevents autoprefixer from issuing warnings.
Fixes sul-dlss/spotlight#1340
=> Update gradient direction

app/views/layouts/spotlight/spotlight.html.erb, app/views/shared/_flash_messages.html.erb
This enables a Blacklight application which renders
shared/flash_messages to mount Spotlight
See https://github.com/projectblacklight/blacklight/blob/39634587ed3bde2eced6d94673417c78eb2f4682/app/views/layouts/blacklight.html.erb#L41 as an example of the "standard" way
=> Use the flash_messages partial in the standard way

app/assets/javascripts/spotlight/reindex_monitor.js, app/controllers/spotlight/resources_controller.rb, app/jobs/spotlight/reindex_job.rb, app/models/spotlight/exhibit.rb, app/models/spotlight/reindex_progress.rb, app/models/spotlight/resource.rb, app/views/spotlight/catalog/_admin_header.html.erb, app/views/spotlight/catalog/_reindex_progress_panel.html.erb, config/locales/spotlight.en.yml, config/routes.rb, db/migrate/20151215192845_add_index_status_to_resources.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/resources_controller_spec.rb, spec/features/javascript/reindex_monitor_spec.rb, spec/models/spotlight/exhibit_spec.rb, spec/models/spotlight/reindex_progress_spec.rb, spec/views/spotlight/catalog/admin.html.erb_spec.rb
Also add an index_status enum column to the Spotlight::Resource to track the index state.
Closes #1220
=> Add panel to monitor reindex status.

app/controllers/spotlight/search_configurations_controller.rb, app/models/spotlight/field_metadata.rb, app/views/spotlight/search_configurations/_facet_metadata.html.erb, app/views/spotlight/search_configurations/_facets.html.erb, config/locales/spotlight.en.yml, spec/models/spotlight/field_metadata_spec.rb, spec/views/spotlight/search_configurations/_facet_metadata.html.erb_spec.rb
Fixes #1333
With a multitenant index, the luke request handler data cannot be scoped to the
current exhibit. Instead, use the search builder and ordinary facet queries to
get the appropriate information (with a slight loss of information -- we can't
get the number of terms in an exhibit, so just give '20+' for large counts)
=> Use naive solr facet query to get facet values and term counts

app/assets/stylesheets/spotlight/_header.scss
`.masthead { overflow: hidden }` is bad; turns out we need the overflow behavior for dropdown menus.
=> Adjust masthead with background image to use relative sizing

app/views/spotlight/appearances/edit.html.erb, app/views/spotlight/contact_forms/new.html.erb, app/views/spotlight/metadata_configurations/edit.html.erb, app/views/spotlight/search_configurations/edit.html.erb, app/views/spotlight/searches/_form.html.erb
=> Responsive grid classes should be defined for both controls and labels

app/assets/javascripts/spotlight/check_user_existence.js, app/assets/javascripts/spotlight/users.js, app/controllers/spotlight/admin_users_controller.rb, app/controllers/spotlight/concerns/user_existable.rb, app/controllers/spotlight/concerns/user_invitable.rb, app/controllers/spotlight/roles_controller.rb, app/views/devise/mailer/invitation_instructions.html.erb, app/views/shared/_site_sidebar.html.erb, app/views/spotlight/admin_users/index.html.erb, config/locales/spotlight.en.yml, config/routes.rb, spec/controllers/spotlight/admin_users_controller_spec.rb, spec/controllers/spotlight/roles_controller_spec.rb, spec/features/site_admin_management_spec.rb
=> Allow site admins to manage other site admins

spec/features/edit_search_fields_spec.rb, spec/test_app_templates/catalog_controller.rb
Closes #1406 
This is purely cosmetic since it is only in the `CatalogController` generated into the internal test app.
=> Move Date sort to the bottom of the list in the test-app

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss, app/assets/stylesheets/spotlight/_exhibits_index.scss, app/assets/stylesheets/spotlight/_header.scss, app/assets/stylesheets/spotlight/_variables.scss, app/views/shared/_site_sidebar.html.erb, app/views/spotlight/exhibits/_new_exhibit_form.html.erb, app/views/spotlight/exhibits/_tags.html.erb, app/views/spotlight/exhibits/new.html.erb, app/views/spotlight/sites/edit.html.erb, config/locales/spotlight.en.yml, spec/features/create_exhibit_spec.rb, spec/features/site_admin_management_spec.rb
Includes a handful of updates, all related to tidying up the exhibit admin pages:
* Several adjustments for better alignment of page elements
* I updated the page title and subtitles scheme, so that all page titles are "Manage exhibits" and the subtitles are the same as the sidebar links. This is more consistent with how we do things in the exhibit admin pages, and generally feels more logical than the previous scheme.
=> Exhibits admin pages updates

.rubocop_todo.yml, app/helpers/spotlight/title_helper.rb, app/views/spotlight/searches/index.html.erb, app/views/spotlight/tags/index.html.erb, spec/helpers/spotlight/title_helper_spec.rb, spec/views/spotlight/tags/index.html.erb_spec.rb
Closes #1440 
Removed label of counts from the Tags and Browse Categories pages. This label wasn't shown on any other pages.
Also removed a helper (and associated test) used to produce the label since it wasn't used anywhere else in the app after I updated the tags and browse categories views.
=> Remove label that shows tag and browse category counts

spec/features/edit_search_fields_spec.rb, spec/views/spotlight/about_pages/index.html.erb_spec.rb, spec/views/spotlight/searches/_search.html.erb_spec.rb
Looks like Capybara's default functionality is to hide invisible
elements. Proposing we go with it rather than turning off Capybara's
#ignore_hidden_elements.
=> Fix tests.

app/models/spotlight/custom_field.rb, app/values/custom_field_name.rb, spec/models/spotlight/custom_field_spec.rb
Allows imported fields to have the same label as a user-defined field,
but have its own content.
=> ReadOnly has a different field name.

.gitignore
`.ruby-version` and `.ruby-gemset` are the two files that are commonly used by RVM and rbenv. Ignore both.
=> Ruby version management artifacts should be ignored by git

.gitignore, spec/helpers/spotlight/application_helper_spec.rb, spec/helpers/spotlight/browse_helper_spec.rb, spec/helpers/spotlight/crud_link_helpers_spec.rb, spec/helpers/spotlight/jcrop_helper_spec.rb, spec/helpers/spotlight/navbar_helper_spec.rb, spec/helpers/spotlight/pages_helper_spec.rb, spec/helpers/spotlight/roles_helper_spec.rb, spec/helpers/spotlight/search_configurations_helper_spec.rb, spec/helpers/spotlight/title_helper_spec.rb, spec/routing/spotlight/exhibit_catalog_spec.rb, spec/views/spotlight/catalog/admin.html.erb_spec.rb, spec/views/spotlight/exhibits/edit.html.erb_spec.rb, spec/views/spotlight/exhibits/index.html.erb_spec.rb, spec/views/spotlight/metadata_configurations/_metadata_field.html.erb_spec.rb, spec/views/spotlight/metadata_configurations/edit.html.erb_spec.rb, spec/views/spotlight/pages/edit.html.erb_spec.rb, spec/views/spotlight/pages/new.html.erb_spec.rb, spec/views/spotlight/pages/show.html.erb_spec.rb, spec/views/spotlight/roles/index.html.erb_spec.rb, spec/views/spotlight/search_configurations/_facet_metadata.html.erb_spec.rb, spec/views/spotlight/search_configurations/_search_fields.html.erb_spec.rb, spec/views/spotlight/search_configurations/_sort.html.erb_spec.rb, spec/views/spotlight/sites/edit_exhibits.html.erb_spec.rb
The only adjustment required was to fully qualify `Spotlight::Xxx` in a few mocks/let statements.
While this appears to change many lines, the difference is almost entirely whitespace.
=> Remove unneccessary module namespacing from specs

app/models/concerns/spotlight/resources/open_graph.rb, app/models/spotlight/resource.rb, app/models/spotlight/resources/upload.rb, app/services/spotlight/solr_document_builder.rb, app/services/spotlight/upload_solr_document_builder.rb, spec/models/spotlight/resource_spec.rb, spec/models/spotlight/resources/open_graph_spec.rb, spec/models/spotlight/resources/upload_spec.rb, spec/services/spotlight/solr_document_builder_spec.rb
This positions us to run indexing for a document independent of a single
exhibit.
This would require changes to `spotlight-dor-resources`.
https://github.com/sul-dlss/spotlight-dor-resources/blob/master/app/models/spotlight/resources/dor_harvester.rb#L18
=> Extract Solr document building from the resource

blacklight-spotlight.gemspec
See:
https://github.com/plataformatec/devise/issues/4045#issuecomment-215854347
This affects our gem spotlight-dor-resources, among others.
=> Bump devise_invitable to support Devise 4+

app/models/concerns/spotlight/ar_light.rb, app/models/concerns/spotlight/solr_document.rb, app/models/spotlight/solr_document_sidecar.rb, app/services/spotlight/solr_document_builder.rb, spec/models/solr_document_spec.rb, spec/services/spotlight/solr_document_builder_spec.rb
This should allow items to be part of multiple exhibits.
Fixes https://github.com/sul-dlss/exhibits/issues/205.
=> Persist exhibit membership in the Sidecar

Rakefile
Rubocop is much faster to run than the rest of the build, so put it on
the front end.  That way we use less time seeing if a build failed.
=> Fail the build more quickly if Rubocop fails

app/assets/javascripts/spotlight/application.js, app/assets/javascripts/spotlight/copy_email_addresses.js, app/models/concerns/spotlight/user.rb, app/views/spotlight/admin_users/index.html.erb, blacklight-spotlight.gemspec, config/locales/spotlight.en.yml, lib/spotlight/engine.rb, spec/features/site_admin_management_spec.rb
Fixes #1472
Implementation:
Copy button color changes on hover:
Addresses are highlighted when button is pressed (and they are copied to the clipboard):
=> Generate list of email addresses of current site administrators, exhibit administrators, and exhibit curators

lib/generators/spotlight/install_generator.rb
=> Fix install generator while we're pointing at an unreleased version of friendly_id

app/views/spotlight/search_configurations/_search_fields.html.erb, app/views/spotlight/search_configurations/_sort.html.erb, spec/views/spotlight/search_configurations/_search_fields.html.erb_spec.rb, spec/views/spotlight/search_configurations/_sort.html.erb_spec.rb
Fixes #1608 
@ggeisler it would be helpful if you could validate that the behavior in the **Before** gif was what you were seeing on the exhibits site (particularly the empty dotted border).
=> Parameterize configuration keys in Nestable's data-id attribute.

app/assets/javascripts/spotlight/block_mixins/autocompleteable.js, app/assets/javascripts/spotlight/catalog_edit.js, app/assets/javascripts/spotlight/search_typeahead.js, app/assets/stylesheets/spotlight/_sir-trevor_overrides.scss, app/assets/stylesheets/spotlight/typeahead.css, app/controllers/spotlight/catalog_controller.rb
=> Make autocomplete results with many items more usable

app/assets/stylesheets/spotlight/_pages.scss, app/controllers/spotlight/contacts_controller.rb, app/views/spotlight/about_pages/_contact_properties.html.erb, spec/controllers/spotlight/contacts_controller_spec.rb, spec/features/add_contacts_spec.rb
also:
* limit avatar height/width to 70px
* fix/augment tests to check for avatar info in DB for newly created contact
closes #1570
=> fix avatar_attributes param handling in ContactsController

app/assets/stylesheets/spotlight/typeahead.css, lib/spotlight/engine.rb, spec/features/exhibit_masthead_spec.rb
also, get rid of no-longer-applicable `rubocop:disable` statement
note that there are still a couple references to jcrop in add_contacts_spec.rb, but those should be taken care of by PR #1643.
closes #1623
=> remove remaining jcrop references

app/controllers/spotlight/contact_forms_controller.rb, app/models/spotlight/contact_form.rb, app/views/spotlight/contact_forms/new.html.erb, app/views/spotlight/shared/_report_a_problem.html.erb, config/locales/spotlight.en.yml, lib/spotlight/engine.rb, spec/controllers/spotlight/contact_forms_controller_spec.rb, spec/features/report_a_problem_spec.rb, spec/models/spotlight/contact_form_spec.rb
also, turn the email fields from text fields to proper HTML email fields.
here's a screenshot of the feedback form, with the new DOM element for the (visually) hidden form field in view in the debugger:
paired w/ @jkeck.
closes sul-dlss/exhibits#345
=> add non-visible field for catching spammy feedback submissions, add tests for field validation

app/models/spotlight/resource.rb, app/views/spotlight/browse/_search.html.erb, spec/models/spotlight/resource_spec.rb
This includes things like the browse#index caches, which can now avoid expensive
solr queries by relying on the exhibit cache key.
Fixes #1657
=> After reindexing a resource, touch the exhibit to break any caches that might exist

.rubocop_todo.yml, app/helpers/spotlight/browse_helper.rb, app/helpers/spotlight/pages_helper.rb, app/helpers/spotlight/rendering_helper.rb, app/views/spotlight/browse/show.html.erb, spec/support/views/test_view_helpers.rb, spec/views/spotlight/browse/show.html.erb_spec.rb
=> Allow the browse category description to be marked up with markdown

app/views/spotlight/appearances/edit.html.erb, app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/featured_images/_form.html.erb, app/views/spotlight/featured_images/_upload_form.html.erb, app/views/spotlight/pages/_form.html.erb, app/views/spotlight/searches/_form.html.erb, app/views/spotlight/sites/edit.html.erb, config/locales/spotlight.en.yml, spec/features/exhibit_masthead_spec.rb
Closes #1670 
This PR also aims to distinguish between Site and Exhibit mastheads in tab labeling.
=> Update crop area help text.

app/views/spotlight/dashboards/_reindexing_activity.html.erb
=> Wrap "no indexing activity" notice in a paragraph tag for improved vertical spacing

app/controllers/spotlight/appearances_controller.rb, app/helpers/spotlight/application_helper.rb, app/helpers/spotlight/main_app_helpers.rb, app/models/spotlight/exhibit.rb, app/views/layouts/spotlight/spotlight.html.erb, app/views/spotlight/appearances/edit.html.erb, config/locales/spotlight.en.yml, db/migrate/20170204091234_add_theme_to_spotlight_exhibits.rb, lib/spotlight/engine.rb, spec/features/autocomplete_typeahead_spec.rb, spec/features/exhibit_themes_spec.rb, spec/helpers/spotlight/main_app_helpers_spec.rb, spec/spec_helper.rb
=> Add configuration and UI for selected themes for an exhibit

app/assets/javascripts/spotlight/multi_image_selector.js, app/assets/javascripts/spotlight/search_typeahead.js, spec/features/autocomplete_typeahead_spec.rb
=> Destroy multiImageSelectors before instantiating new ones

app/assets/javascripts/spotlight/crop.es6
When a crop box bound is greater than 180, rectangles render funny, but polygons seemingly are ok.
=> Use polygons instead of rectangles to work around possible leaflet rendering bug

app/controllers/spotlight/contact_forms_controller.rb, app/views/shared/_masthead.html.erb, app/views/spotlight/contact_forms/new.html.erb, app/views/spotlight/shared/_report_a_problem.html.erb, config/locales/spotlight.en.yml, spec/features/report_a_problem_spec.rb
=> Cleanup feedback form inconsistencies

app/assets/stylesheets/spotlight/typeahead.css
Fixes https://github.com/sul-dlss/exhibits/issues/1750
Reverts part of 0f02dd9dac3ca494d6ecb0e1534344a70dd7ebaa
=> Override typeahead z-index with a big enough value (restores #1588)

db/migrate/20170821165811_change_index_status_to_longblob.rb
Prevents an error like:
```
ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column
'index_status' at row 1: UPDATE `spotlight_solr_document_sidecars` SET
`index_status` = x'2d2d2d0a3a6f6...
```
by converting the `binary` column into a LONGBLOB type
=> Prevent overflow of the index_status when deploying to mysql

app/assets/javascripts/spotlight/application.js
Blacklight already generates jquery into the host app.
We also want to enable the host to change versions (to jquery3 for
example)
=> Don't include jquery by default.

app/assets/javascripts/spotlight/pages.js.erb
For a Spotlight adopter not on Rails 5.1, `Rails` will be undefined
without including rails-ujs. This sets the adapter for both rails-ujs
and jquery-ujs adopters.
=> Uses a backwards compatible ujs adapater.

app/views/spotlight/appearances/edit.html.erb
Per Rails guides, when using `image_tag` you must specify the extension
of the image.
http://guides.rubyonrails.org/layouts_and_rendering.html#linking-to-images-with-the-image-tag
An error is noticed when using Spotlight in a production environment.
=> Specifies png as the custom theme's image extension

app/assets/stylesheets/spotlight/application.scss
The latter is generated into the application.  Having both scss files
means that bootstrap is loaded twice.
Fixes #1833
=> Remove application.scss as it duplicates spotlight.scss

app/assets/javascripts/spotlight/exhibits.js, app/controllers/spotlight/contact_email_controller.rb, app/models/spotlight/ability.rb, app/views/spotlight/exhibits/_confirmation_status.html.erb, app/views/spotlight/exhibits/_contact.html.erb, app/views/spotlight/exhibits/_form.html.erb, config/locales/spotlight.en.yml, config/routes.rb, spec/controllers/spotlight/contact_email_controller_spec.rb, spec/factories/contact_emails.rb, spec/features/exhibits/administration_spec.rb
successful deletion example (including manual page refresh to show contact email was actually deleted):
error deleting (contact address already deleted, e.g. in another page load in a different tab):
closes #669
=> allow deleting contact email addresses

app/models/sir_trevor_rails/blocks/browse_block.rb, app/models/sir_trevor_rails/blocks/featured_pages_block.rb, spec/models/sir_trevor_rails/blocks/browse_block_spec.rb, spec/models/sir_trevor_rails/blocks/featured_pages_block_spec.rb
We noticed this issue downstream in Exhibits, that when enabling "browse categories" and then creating an empty "BrowseBlock" (no browse category added), an "undefined method each for nil" error could be raised. This PR ensures that `items` retrieved from `data` are cast to a `Hash` with `.each` available.
See: https://github.com/sul-dlss/exhibits/issues/789
=> Cast empty items to a Hash for empty browse categories & feature pages

app/models/sir_trevor_rails/blocks/browse_block.rb, spec/models/sir_trevor_rails/blocks/browse_block_spec.rb, spec/models/sir_trevor_rails/blocks/featured_pages_block_spec.rb
This is a temporary fix to stop errors being thrown on edit pages.  A more permanent solution should be implemented in the future.
Connects to #1782
=> Only handle browse block items whose block id/slug exists.

README.md
We switched from PhantomJS to ChromeDriver in [316ada6](https://github.com/projectblacklight/spotlight/commit/316ada66493bac8df93854c7602d6563c0578777).
=> Remove PhantomJS requirement from README

db/migrate/20171005231502_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
I think this migration was missed in the acts-as-taggable-on v5.0 upgrade cc @cbeer
=> add missing migration from acts-as-taggable-on

app/controllers/spotlight/concerns/application_controller.rb, app/models/spotlight/blacklight_configuration.rb, app/views/spotlight/metadata_configurations/edit.html.erb, app/views/spotlight/search_configurations/_facets.html.erb, app/views/spotlight/search_configurations/_search_fields.html.erb, app/views/spotlight/search_configurations/_sort.html.erb, spec/controllers/spotlight/catalog_controller_spec.rb, spec/views/spotlight/search_configurations/_facets.html.erb_spec.rb, spec/views/spotlight/search_configurations/_search_fields.html.erb_spec.rb, spec/views/spotlight/search_configurations/_sort.html.erb_spec.rb
Use this, instead of the upstream_if hack, to evaluate whether to offer fields for admin users or not
=> Store a copy of the original field configuration before applying spotlight-specific changes

app/assets/javascripts/spotlight/blocks/link_to_search_block.js
Closes #1863 for now. So we don't have to update the svg sprites for this. Likely we should have a repo / process / command for doing this in the future.
=> just use existing search_results icon

app/models/spotlight/blacklight_configuration.rb, lib/generators/spotlight/templates/catalog_controller.rb, spec/models/spotlight/blacklight_configuration_spec.rb
This PR is connected to https://github.com/sul-dlss/exhibits/issues/999, and it fixes #1810, fixes #1809, and fixes #1808.
To enable the title only by default (i.e., deselected all metadata by default), you need to configure the `view.foobar` data, like so:
```
config.view.gallery.title_only_by_default = true
```
=> provide support to configure a view by default to show the title only

app/views/spotlight/roles/_edit_fields.html.erb, config/locales/spotlight.en.yml
TODO:
Related: sul-dlss/exhibits#1040
This PR adds help text to the new user form in Configuration > Users. The default i18n key can be overridden in `spotlight.roles.edit_fields.help`.
@ggeisler What do you think about this default helper text?
@jkeck opinions? 
```html
<div class="form-group">
<label class="sr-only control-label" for="exhibit_roles_attributes_2_user_key">User key</label>
<input aria-describedby="newUserHelpBlock" class="form-control" type="email" name="exhibit[roles_attributes][2][user_key]" id="exhibit_roles_attributes_2_user_key">
</div>
<small id="newUserHelpBlock" class="form-text text-muted">Please use a valid email address</small>
```
```html
<div class="form-group">
<label class="sr-only control-label" for="exhibit_roles_attributes_2_user_key">User key</label> …
```
=> Add helptext to add user form

.travis.yml, spec/features/javascript/search_config_admin_spec.rb
- Updating some JS tests that have been (inconsistently) killing Travis builds this week
- Applying a .travis.yml workaround that may help with builds timing out
```ruby
Failure/Error: expect(page).to have_selector('.zpr-link[data-iiif-tilesource]')
expected to find visible css ".zpr-link[data-iiif-tilesource]" but there were no matches
```
=> Update flaky JS test and add TravisCI workaround

app/views/spotlight/shared/_report_a_problem.html.erb
This prevents us from having a label that points at a non-existant
field, which is an accessability concern.
=> Bootstrap_form_for email_address field handles labels

app/assets/javascripts/spotlight/clear_form_button.js, app/assets/stylesheets/spotlight/_browse.scss, app/controllers/spotlight/browse_controller.rb, app/controllers/spotlight/searches_controller.rb, app/helpers/spotlight/browse_helper.rb, app/views/spotlight/browse/_search_box.html.erb, app/views/spotlight/browse/_search_title.html.erb, app/views/spotlight/browse/show.html.erb, app/views/spotlight/searches/_form.html.erb, config/locales/spotlight.en.yml, db/migrate/20180119193632_add_search_box_to_spotlight_searches.rb, spec/features/browse_category_admin_spec.rb, spec/features/browse_category_spec.rb
Fixes #1880 
This PR adds a configurable search box to browse categories. Users can provide a query to search within the browse category / saved search.
=> Add a configurable search box to browse categories

app/assets/stylesheets/spotlight/_pages.scss
When using the "text align: right" option for the Embed + Text widget, the text can overlap the embed if the embed width exceeds the width allocated for the six columns assigned to it (bottom example below):
This PR is a simple change that limits the width of the iframe (at medium or larger viewports), which keeps in within the column and thus prevents the text overlap:
It's not an ideal approach, since if the iframe width is greater than the available column width the iframe just gets its sides cut-off to fit, but the result is likely not to be terrible (e.g., compare before and after videos above) so might be sufficient for an immediate fix.
Longer term, a more sophisticated approach that would adjust the size of the iframe proportionally would probably be better. I'll create a …
=> Limit max-width of iframe in Embed + Text widget

app/assets/javascripts/spotlight/sir-trevor/locales.js
Closes sul-dlss/exhibits#1023
This PR adds example to the description text for the "Embed + Text" widget. 
"This widget embeds a web resource and a text block to the left or right of it."
"This widget embeds an oEmbed-supported web resource and a text block to the left or right of it. Examples of oEmbed-supported resources include those from YouTube, Twitter, Flickr, and SlideShare."
=> Update description for Embed + Text widget

app/controllers/spotlight/browse_controller.rb
Hopefully fixes sul-dlss/exhibits#1103
This PR updates the `search_query` method that is used to construct browse categories. Accessing the query params for a `Spotlight::Search` requires a string (`"q"`), not a symbol (`:q`). This change was introduced in #1888 https://github.com/projectblacklight/spotlight/blob/0a3e4302e1240efbd084e7cd2d833e2f826f310e/app/controllers/spotlight/browse_controller.rb#L42
=> Fix browse controller bug: access query params with string

blacklight-spotlight.gemspec
- Adds the [iiif-presentation gem](https://rubygems.org/gems/iiif-presentation/versions/0.2.0) to our dependencies and fixes our failing Travis builds
- `iiif_presentation` was [recently removed from the iiif_manifest gem](https://github.com/samvera-labs/iiif_manifest/commit/8324094efa93e6bd7e78ffd71b9c969543b40673#diff-3ca3e0de685e1e0bfa36f0c111f9710c)
=> Add iiif-presentation gem as a dependency

app/views/spotlight/dashboards/_analytics.html.erb
Minor update to add classes that right-align the numeric column of the Analytics popular pages table, and to add a class to the table element so other table elements can be customized without complicated CSS.
=> Add class to right-align numeric table column

app/controllers/concerns/spotlight/controller.rb, app/models/concerns/spotlight/custom_translation_extension.rb, app/models/spotlight/exhibit.rb, blacklight-spotlight.gemspec, db/migrate/20180306142612_create_translations.rb, lib/generators/spotlight/install_generator.rb, lib/generators/spotlight/templates/config/initializers/translation.rb, lib/spotlight/engine.rb, spec/factories/translation.rb, spec/features/translation_scope_spec.rb
This groundwork is a prerequisite for additional i18n + translation issues.
Adopters wanting to take advantage of this will need to copy the `translation.rb` initializer into their Spotlight application and uncomment the commented lines.
=> Enable exhibit specific translations to be stored in ActiveRecord

blacklight-spotlight.gemspec, spec/features/add_iiif_manifest_spec.rb, spec/models/spotlight/resources/iiif_harvester_spec.rb, spec/spec_helper.rb
The hope here is to improve the reliability and speed of the test suite by disabling external requests.
=> Adds Webmock to project to disable external requests

app/assets/stylesheets/spotlight/_spotlight.scss, app/assets/stylesheets/spotlight/_translations.scss, app/assets/stylesheets/spotlight/_utilities.scss, app/assets/stylesheets/spotlight/_variables.scss, app/controllers/spotlight/translations_controller.rb, app/models/concerns/spotlight/translatables.rb, app/models/spotlight/ability.rb, app/models/spotlight/exhibit.rb, app/views/spotlight/shared/_curation_sidebar.html.erb, app/views/spotlight/translations/edit.html.erb, config/locales/spotlight.en.yml, config/routes.rb, lib/generators/spotlight/templates/config/initializers/translation.rb, spec/controllers/spotlight/translations_controller_spec.rb, spec/features/exhibits/language_create_edit_spec.rb, spec/features/exhibits/translation_editing_spec.rb, spec/models/spotlight/ability_spec.rb, spec/models/spotlight/exhibit_spec.rb
Work outlined in #1914 
Fixes #1914. Unresolved items have been split off as additional tickets.
Make sure to update your `config/initializers/translation.rb` file to turn on the i18n-active_record backend.
None, just create an exhibit
This is a proof of concept with some lingering questions: ✅
=> add basic implementation of general edit form

app/assets/stylesheets/spotlight/_translations.scss, app/controllers/spotlight/translations_controller.rb, app/models/spotlight/search.rb, app/views/spotlight/translations/_browse_categories.html.erb, app/views/spotlight/translations/_general.html.erb, app/views/spotlight/translations/edit.html.erb, config/locales/spotlight.en.yml, spec/features/exhibits/translation_editing_spec.rb
Closes #1917 
- What should we do if there are no browse categories? (Don't show the tab / Put some explanation/help text as the tab content?)
- I'm using the browse category's `slug` as part of the key (similar to how we do w/ the exhibit) so it can be fetched appropriately by the `Translatables` mixin.  This has the potential of causing an issue if you were to name a browse category the same thing as your exhibit. A few ways that we could solve this is adding some sort of normalization of the class name into the key or to have the Translation have a polymorphic relationship (not sure how that will play w/ how we've set things up so far though).
- Another issue w/ using the `slug` is that if a browse category is renamed, its slug is updated (this will break all translation keys as-is). …
=> Add ability to translate title/description of browse categories

app/models/spotlight/exhibit.rb
This is already defined by calling acts_as_tagger and there is a rails 5.1 issue that throws an error when redefining these associations.
Closes #1944 
Closes sul-dlss/exhibits#1125
=> Remove our has_many :owned_taggings definition.

app/models/spotlight/exhibit.rb, app/models/spotlight/main_navigation.rb, app/views/spotlight/translations/_general.html.erb, config/locales/spotlight.en.yml, spec/factories/main_navigation.rb, spec/features/exhibits/translation_editing_spec.rb, spec/models/spotlight/exhibit_spec.rb
Closes #1936 
Adds "main menu" translations to "General" translations.
*Note to reviewer* You may need to enable browse categories, about pages
=> adds main menu navigation translation functionality

app/controllers/spotlight/exhibits_controller.rb, app/controllers/spotlight/filters_controller.rb, app/controllers/spotlight/languages_controller.rb, app/views/spotlight/exhibits/_export.html.erb, app/views/spotlight/exhibits/_import.html.erb, app/views/spotlight/exhibits/_languages.html.erb, app/views/spotlight/exhibits/edit.html.erb, app/views/spotlight/filters/_form.html.erb, spec/controllers/spotlight/filters_controller_spec.rb, spec/controllers/spotlight/languages_controller_spec.rb
Fixes #1932 
1. Pass a `tab` parameter through a hidden_field on each form within Configuration > General
2. Pass the `tab` parameter to the controller action's redirect 
2. In the view, apply the `active` class to the nav tab and `div.tab-content` that have an id that matches the `tab` param
Note: h/t to @mejackreed for providing [an example of this approach](https://github.com/projectblacklight/spotlight/pull/1931/files#diff-059f2c780562af6d663a2f0d5cd9038bR9)
`http://test.host/spotlight/exhibit-title-714/edit#language`
`http://test.host/spotlight/exhibit-title-714/edit?tab=language`
- Basic settings
- Languages
- Filter
- Import (unchanged; redirects to exhibit dashboard)
- Export (unchanged; stays on the same page after downloading)
- Delete (unchanged; redirects to exhibits#index)
=> Redirect to the same Configuration > General tab after forms are saved

app/views/spotlight/translations/_search_fields.html.erb, app/views/spotlight/translations/edit.html.erb, config/locales/spotlight.en.yml, lib/generators/spotlight/templates/catalog_controller.rb, spec/features/exhibits/translation_editing_spec.rb, spec/test_app_templates/catalog_controller.rb
=> Add the Search field labels tab to the Translations configuration

app/assets/javascripts/spotlight/translation_progress.js, app/views/spotlight/translations/_browse_categories.html.erb, app/views/spotlight/translations/_general.html.erb, app/views/spotlight/translations/_search_fields.html.erb, app/views/spotlight/translations/edit.html.erb, spec/features/exhibits/translation_editing_spec.rb
Closes #1935 
This PR adds progress counters to each tab of the Translations page. Note: this counter is not dynamic. Counts are updated when a form is saved.
=> Add progress counter to Translations tabs

app/controllers/spotlight/translations_controller.rb, app/views/spotlight/translations/_browse_categories.html.erb, app/views/spotlight/translations/_general.html.erb, app/views/spotlight/translations/_search_fields.html.erb, app/views/spotlight/translations/edit.html.erb, spec/features/exhibits/translation_editing_spec.rb
Closes #1958 
This PR enhances redirect behavior for the Config > Translations form. After a user submits a translation form (e.g. "Search fields"), they will be sent back to the same tab.
**Note:** This only implements redirects for General, Search fields, and Browse categories. This behavior will need to be added to Metadata fields (#1959) and Pages (#1919) once available.
=> Redirect to the same Config > Translations tab after submitting form

app/models/spotlight/exhibit.rb, spec/models/spotlight/exhibit_spec.rb
(looks like we missed this the first time around)
=> Add Description to the list of translatable fields for an exhibit.

db/migrate/20180403130857_translation_uniqueness.rb, spec/models/translation_spec.rb
Fixes #1933 
I'm not adding an ActiveRecord validation here also as it would require us to monkey patch i18n_active-record. I think the SQL validation gets us what we want.
=> add SQL validation for translation uniqueness

app/views/spotlight/translations/_browse_categories.html.erb, spec/features/exhibits/translation_editing_spec.rb
=> Add a description translation field for all browse categories.

spec/features/slideshow_spec.rb
This should reduce our testing suite runtime ~10sec
=> add more specific selector to fix chromeheadless error

.travis.yml, app/views/spotlight/search_configurations/_search_fields.html.erb, spec/features/javascript/blocks/solr_documents_block_spec.rb, spec/features/javascript/search_config_admin_spec.rb
They shall flap no more! 
This PR:
- treats some squeaky `expect` statements by either
- nesting them inside of a `within` or
- adding `visible: true` 
- disables image loading in Chrome headless
- ~~increases the max wait time in CI only~~
See #1974
=> Update flaky JS tests

README.md, blacklight-spotlight.gemspec, spec/spec_helper.rb
Also removes `database_cleaner` in favor of transaction fixtures.
_Checking to see if this helps our build performance at all._
_This should get rolled out with Spotlight 2_
=> Drop support for rails 5.0

lib/migration/page_language.rb, lib/tasks/spotlight_tasks.rake, spec/lib/migration/page_language_spec.rb
Fixes #2003 
A few questions here...
=> add page migration task to new locales

app/views/spotlight/exhibits/_languages.html.erb
=> Display language instructions only when languages are present.

app/views/spotlight/browse/_search.html.erb
I believe this is causing browse category titles to be cached and not changed when switching locales on the browse category landing page.
=> Add the current locale to the cache key for searches/browse categories.

app/assets/javascripts/spotlight/form_observer.js, app/assets/javascripts/spotlight/pages.js.erb, spec/features/javascript/feature_page_admin_spec.rb
Refactor form-observer to be useful when serving javascript as async
This refactor does a few things:
- Removes the form observer methods from the global state
- creates this as a singleton jQuery type plugin/module
- Documents some strange edge cases / handles same event instantiation
Unforuntately this is not compatible to running our tests in an async
way. But manual smoke testing has confirmed this working.
To test, set:
https://github.com/projectblacklight/spotlight/blob/master/app/views/layouts/spotlight/spotlight.html.erb#L24
```diff
- <%= javascript_include_tag "application" %>
+ <%= javascript_include_tag "application", async: true %>
```
You will also need to set:
```diff
- config.assets.debug = true
+ config.assets.debug = false
```
=> Fix async form observer

app/models/spotlight/resources/iiif_harvester.rb, spec/models/spotlight/resources/iiif_harvester_spec.rb
IIIF Presentation resources are not required to support a HEAD
request. This change will use a 405 response from a resource
to try a GET request.
=> This commit adds support for harvesting IIIF w/out HEAD requests

db/migrate/20180822233601_change_type_of_taggings_taggable.rb
Fixes GH-1433.
Closes GH-1827.
Tests are failing locally with:
```
== 20180814221815 ChangePaperTrailVersionsObjectColumnToMediumText: migrating =
-- adapter_name()
-> 0.0000s
-- change_column(:versions, :object, :text, {:limit=>1073741823})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
Could not find table 'versions'
/Users/alex/clones/spotlight/.internal_test_app/db/migrate/20180814221815_change_paper_trail_versions_object_column_to_medium_text.rb:9:in `change'
/Users/alex/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/alex/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'
=> db: change taggable_id to integer

app/services/spotlight/carrierwave_file_resolver.rb
This avoids a deprecation warning thrown in the super class
=> Fixed typo in method name for CarrierwaveFileResolver

app/models/spotlight/resources/upload.rb
It seems that, with optional associations, if an associated object is invalid it'll just get dropped. For uploaded objects, if the image is invalid we want to alert the user and cancel the upload.
=> Validate the FeaturedImage object if provided.

app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/featured_images/_form.html.erb, app/views/spotlight/featured_images/_upload_form.html.erb, config/locales/spotlight.en.yml, spec/views/spotlight/contacts/edit.html.erb_spec.rb, spec/views/spotlight/featured_images/_form.html.erb_spec.rb, spec/views/spotlight/featured_images/_upload_form.html.erb_spec.rb
This PR adds the ability to customize help blocks for image uploads in various places.
We hope to use this in Exhibits as help text along with #2146 to limit upload sizes.
Related to https://github.com/sul-dlss/exhibits/issues/1342
=> Adds the ability to modify help text blocks for images

app/assets/javascripts/spotlight/crop.es6
This seems to handle an issue in some spotlight installations where we're getting an invalid authenticity token error when uploading images using for cropping in thumbnails/mastheads.
See sul-dlss/vatican_exhibits#415
=> Add the document's csrf token to the AJAX request for uploading images.

app/serializers/spotlight/exhibit_export_serializer.rb
This avoids the edge case where exporting an exhibit with a contact email then
importing it into the same Spotlight instance causes this sort of error:
```
F, [2019-07-29T12:32:28.849634 #15168] FATAL -- : [157062cd-0728-432e-8acb-252372f37ce0] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_spotlight_contact_emails_on_confirmation_token"
DETAIL:  Key (confirmation_token)=(R6A-skseGTy41-9EHs5T) already exists.
: INSERT INTO "spotlight_contact_emails" ("exhibit_id", "email", "confirmation_token", "confirmed_at", "confirmation_sent_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"):
```
=> ExhibitExportSerializer: remove confirmation token

app/helpers/spotlight/pages_helper.rb, app/models/spotlight/page.rb, app/models/spotlight/page_content.rb, app/models/spotlight/page_content/sir_trevor.rb, app/views/spotlight/pages/_form.html.erb, db/migrate/20190807085432_add_content_type_to_pages.rb, lib/spotlight/engine.rb, spec/helpers/spotlight/pages_helper_spec.rb, spec/models/spotlight/page_spec.rb
This lays the groundwork for alternative page editors (other than SirTrevor) by allowing applications (or perhaps other plugins) to provide a different page editor or custom rendering.
To add a new editor, one must:
1. Implement `Spotlight::PageContent::SomeClass` with a class-level parse method that returns something Rails can render, e.g.:
```
class Spotlight::PageContent::Identity
def self.parse(page, attribute)
page.read_attribute(attribute)
end
end
```
2. Inject some javascript into the application to provide an editing experience. The text area will have the class 'js-some-class-instance' (using a parameterized version of your implementation). Replace the textarea with whatever editor you want, but make sure to serialize the editor state back to a form field of the same `name`.
3. …
=> Allow applications to provide different page content types and editors

app/serializers/spotlight/exhibit_export_serializer.rb
When the target instance does not have the same theme, errors occur: https://gitlab.com/surfliner/surfliner/issues/145#note_203830948
=> ExhibitExportSerializer: ignore theme when unavailable

app/presenters/spotlight/iiif_manifest_presenter.rb
This fixes how thumbnails of uploaded resources appear (or, rather, don't) in Mirador 3.
=> Make sure IIIF canvas dimensions are given as a number, not a string

app/controllers/spotlight/featured_images_controller.rb, app/models/spotlight/featured_image.rb, app/presenters/spotlight/iiif_manifest_presenter.rb, app/services/spotlight/upload_solr_document_builder.rb, lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb, lib/spotlight/engine.rb, spec/presenters/spotlight/iiif_manifest_presenter_spec.rb
This change allows Spotlight applications to use an external (non-riiif) IIIF server for image derivative requests.
It does not teach Spotlight to send uploaded resources to that server; currently using this configuration option requires that the images already exist on the IIIF server.
=> allow IIIF url helpers to be reconfigured

app/controllers/spotlight/custom_search_fields_controller.rb, app/models/spotlight/ability.rb, app/models/spotlight/blacklight_configuration.rb, app/models/spotlight/custom_search_field.rb, app/models/spotlight/exhibit.rb, app/views/spotlight/custom_search_fields/_form.html.erb, app/views/spotlight/custom_search_fields/edit.html.erb, app/views/spotlight/custom_search_fields/new.html.erb, app/views/spotlight/search_configurations/_search_fields.html.erb, app/views/spotlight/search_configurations/edit.html.erb, config/i18n-tasks.yml, config/locales/spotlight.en.yml, config/routes.rb, db/migrate/20190910200927_create_spotlight_custom_search_fields.rb, spec/controllers/spotlight/custom_search_fields_controller_spec.rb, spec/factories/custom_search_fields.rb, spec/features/exhibits/custom_search_fields_spec.rb, spec/models/spotlight/blacklight_configuration_spec.rb, spec/models/spotlight/custom_search_field_spec.rb
=> Add exhibit-specific configuration for custom search fields

app/presenters/spotlight/iiif_manifest_presenter.rb, spec/presenters/spotlight/iiif_manifest_presenter_spec.rb
A small follow-up to #2203. 
This ensures that `#iiif_url` uses the same protocol as the host. I noticed that our Spotlight instance started serving up manifests with HTTP image service IDs instead of HTTPS ids (see below). 
So I _think_ what's happening here... 
`IIIFManifest::IIIFEndpoint` is instantiated with the URL provided by `#iiif_url`.
https://github.com/projectblacklight/spotlight/blob/62b3c7b056d5fcfa3e4a8877780c73cb4b157c46/app/presenters/spotlight/iiif_manifest_presenter.rb#L72-L74
Spotlight uses the `iiif_manifest` gem to construct manifests for uploaded resources. In this case it passes the HTTP URL on to `iiif_manifest`'s [image service builder](https://github.com/samvera/iiif_manifest/blob/15676e227b0ff3fcc68ac8eb4204468d0e997912/lib/iiif_manifest/manifest_builder/image_se …
=> IIIF manifests for uploaded resources should match host protocol

app/controllers/spotlight/admin_users_controller.rb, app/views/spotlight/admin_users/index.html.erb, config/locales/spotlight.en.yml, config/routes.rb, spec/controllers/spotlight/admin_users_controller_spec.rb, spec/features/site_admin_management_spec.rb, spec/features/site_users_management_spec.rb
This PR creates a new table on the AdminUsers page that lists all registered users and their roles:
Fixes GH-2108.
=> AdminUsers: allow superadmins to view all registered users 

config/locales/spotlight.en.yml, lib/spotlight/engine.rb, spec/helpers/spotlight/languages_helper_spec.rb
Follow-on to #2214 
sul-dlss/dlme#606 
This PR makes Arabic available in the Configuration > General > Languages menu.
=> Add Arabic to curator menu

app/assets/stylesheets/spotlight/_header.scss, app/assets/stylesheets/spotlight/_pages.scss, app/views/shared/_exhibit_navbar.html.erb, app/views/spotlight/resources/_external_resources_form.html.erb, app/views/spotlight/resources/new.html.erb, lib/generators/spotlight/install_generator.rb, spec/test_app_templates/Gemfile.extra
Before:
After:
---
<table>
<thead><th>Before</th><th>After</th></thead>
<tr>
<td>
</td><td>
</td>
</tr>
</table>
=> Apply some bootstrap 4 styling fixes

app/views/spotlight/catalog/_reindex_progress_panel.html.erb
=> Update reindex monitor styling

app/assets/stylesheets/spotlight/_blacklight_configuration.scss, app/views/spotlight/search_configurations/_facets.html.erb
=> Fix up facet configs after Bootstrap 4 upgrade

app/views/spotlight/searches/_search.html.erb
=> Restore drag handles to browse category config after Bootstrap 4 upgrade

app/views/spotlight/shared/_locale_picker.html.erb
It seems like things get a little funny because the locales/rtl stuff works based on changes to the `<html>` DOM element, which may not get reloaded.
=> Disable turbolinks when changing locales

app/views/catalog/_save_search.html.erb
=> Update modal header to use Blacklight 7 patterns

app/assets/stylesheets/spotlight/_exhibits_index.scss
=> Center the unpublished banner; fixes #2255

app/views/spotlight/browse/index.html.erb
=> Put browse category links into a row so they align correctly; fixes #2263

app/views/shared/_exhibit_navbar.html.erb
=> Align resource-specific mastheads to the right; part of #2281

app/assets/stylesheets/spotlight/_browse.scss, app/controllers/spotlight/browse_controller.rb, app/views/spotlight/browse/_search_box.html.erb, app/views/spotlight/browse/_sort_and_per_page.html.erb, spec/views/spotlight/browse/_sort_and_per_page.html.erb_spec.rb
=> Wrap the browse category search box in a row; part of #2262

app/views/layouts/spotlight/spotlight.html.erb
Backport to v2.x release
Slightly different than #2246 as we are assuming the Blacklight helper is not available. 🤷‍♂
=> Enable HTML lang attribute to use I18n.locale value

app/assets/stylesheets/spotlight/_blacklight_configuration.scss
=> Tweak metadata config checkbox alignment

app/assets/stylesheets/spotlight/_curation.scss, app/assets/stylesheets/spotlight/_mixins.scss
Without this, the page hover background is applied to the wrong element and overflows its container.
=> Fix page hover state

app/views/spotlight/appearances/edit.html.erb
=> Fix alignment for the main menu items

app/assets/stylesheets/spotlight/_catalog.scss
Fixes #2283
In discussion with @ggeisler we decided to hold off on the Bootstrap column changes. We could do something upstream in Blacklight but it seems not fully clear what that should be quite yet.
Could be done upstream perhaps like this? https://github.com/projectblacklight/blacklight/issues/2213
=> Add max-width of list thumbnail fixes #2283

app/views/shared/_site_sidebar.html.erb
_I'm pretty sure this was a larger button previously, feel free to 🔪 this if we decide it's not a good idea._
=> Remove the nav-link class from the Create Exhibit button.

app/assets/javascripts/spotlight/user/zpr_links.js.erb
We cannot guarantee that all icon svgs do not have trailing whitespace.
To inject this into JavaScript we need to make sure we escape properly
Fixes the build issue here: https://github.com/sul-dlss/dlme/pull/704
=> Make sure that Blacklight::Icon file_source is stripped

app/views/shared/_curated_features_navbar.html.erb, app/views/shared/_user_util_links.html.erb
Fixes #2309 This was causing some styling display issues. BS4 updated
how these elements should be styled.
We could go further by removing the `<li>` but I've kept that for
consistency.
=> Move dropdown-item class to links instead of <li>

app/serializers/spotlight/exhibit_export_serializer.rb, app/serializers/spotlight/page_representer.rb, lib/spotlight/engine.rb, spec/serializers/spotlight/exhibit_export_serializer_spec.rb
This should allow e.g. implementors to exclude resources and solr documents from their exports which is most likely to contribute to bloating export size + time.
I think the technical approach is potentially amenable to run-time selection (by the admin), but I figured that'd make a good phase 2.
=> Add engine configuration to enable/disable exporting parts of an exhibit

app/assets/stylesheets/spotlight/_pages.scss
Super minor update but I noticed that when using a contact photo, the contact info below the name is indented 2px further right than the name (it's subtle but true):
=> Improve contact info alignment when using contact photo

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
Small update to add a bit more vertical spacing between the page header (I believe this just affects the admin pages) and the page content. Sometimes the page content starts with another heading and the three stacked headings feel too close together:
(This PR also includes moving the text-muted class I added in PR #2318 since I now see I can add it to an existing selector rather than creating a new one as I did in PR #2318. Same result but probably better code organization.)
=> Add vertical space between page header and page content

app/assets/stylesheets/spotlight/_header.scss, app/views/shared/_masthead.html.erb, spec/features/browse_category_spec.rb, spec/views/shared/_masthead.html.erb_spec.rb
As a result of the BS4 upgrade some of the default typography and spacing values changed and this resulted in a taller masthead with some extra vertical spacing (on the left below is an exhibit based on BS3, on the right is current with BS4):
I adjusted the font-sizes and spacing values to get something close to what we saw in BS3. We're still using default BS values, so it should be relatively straightforward for implementers to customize.
=> Update masthead font sizes and spacing values

app/assets/stylesheets/spotlight/_mixins.scss, app/assets/stylesheets/spotlight/_pages.scss, app/views/spotlight/feature_pages/_sidebar.html.erb, spec/features/feature_page_spec.rb, spec/views/spotlight/feature_pages/_sidebar.html.erb_spec.rb
I think the BS4 upgrade affected the styling of the links in the feature page sidebar, which are now too large:
I think this has to do with the fact that the parent sidebar links are `<h4>`s, which I don't think they need/should be (all other sidebars in the app just use `<li><a>`s for the sidebar links).
So this PR removes the `<h4>`s and associated styling, and cuts down on other related styling to produce a pretty generic sidebar. Implementors will most likely want to fine-tune the styling of this sidebar to match the way their institution treats links, etc. so my goal was to have something that is readable when there are feature pages with child links to display but otherwise fairly basic.
=> Update feature page sidebar structure and styling

app/assets/stylesheets/spotlight/_header.scss, app/views/shared/_exhibit_navbar.html.erb
=> Update responsive styling for exhibit navbar

app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
Fixes #2323
Seems like just some cruft from BS4 upgrade
Specified in the issue some things I wasn't really able to recreate:
- Tiles too tall (fixing might take care of next couple of items?)
- Spacing between category tiles
- Row extends past right-edge of page content area
I'm happy to look into this further, but not exactly sure how to proceed.
=> Updates browse / page embed styling

app/controllers/concerns/spotlight/search_helper.rb, app/controllers/spotlight/pages_controller.rb, spec/features/javascript/blocks/search_result_block_spec.rb
Blacklight has moved the `search_results` method from where it was. 
Fixes #2332
=> Fix bug in SearchRresults widget

app/assets/images/blacklight/arrow_back_ios.svg, app/assets/images/blacklight/arrow_forward_ios.svg, app/assets/images/blacklight/chevron_left.svg, app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb
=> Update carousel next/prev icons

.rubocop.yml, app/serializers/spotlight/exhibit_export_serializer.rb, spec/serializers/spotlight/exhibit_export_serializer_spec.rb
Add translations and languages configuration to the exhibit export.
Part of https://github.com/sul-dlss/dlme/issues/814
=> Add translations to the exhibit export

app/mailers/spotlight/contact_mailer.rb, app/models/spotlight/contact_form.rb
… from address
Related to https://github.com/sul-dlss/dlme/issues/626
Fixes https://github.com/sul-dlss/dlme/issues/813
`Net::SMTPFatalError: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-2:`
If you use something like Amazon's Simple Email Service (SES) you can't just spoof the `from` header, but must use a verified address. This pull request removes spotlight from spoofing froms.
Adopters should use the ActionMailer `default_options[:from]` https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
=> Removes the ability to spoof from emails.

.travis.yml, app/views/spotlight/catalog/_document_admin_table.html.erb, app/views/spotlight/catalog/_index_compact_default.html.erb
=> Update the items tables to not use bootstrap column classes

app/assets/stylesheets/spotlight/_exhibits_index.scss
Addresses https://github.com/sul-dlss/exhibits/issues/1488
=> Add back landing page card title margins

app/models/concerns/spotlight/solr_document.rb, app/models/spotlight/solr_document_sidecar.rb, spec/models/solr_document_spec.rb, spec/models/spotlight/solr_document_sidecar_spec.rb
We're currently storing empty strings when the exhibit custom field is an empty string, leading to empty values getting indexed into solr and then displaying in the UI
This PR makes sure we clean up the data both when it gets persisted to the database and when it gets serialized out for Solr (both may be excessive, but it seems easier than trying  to remediate all the bad data in the world?). 
Fixes https://github.com/sul-dlss/exhibits/issues/1369
=> Sanitize exhibit custom field data

app/helpers/spotlight/application_helper.rb, app/helpers/spotlight/main_app_helpers.rb, app/models/spotlight/exhibit.rb, app/views/spotlight/appearances/edit.html.erb, spec/models/spotlight/exhibit_spec.rb
This is a stab at an approach that would allow us to resolve sul-dlss/exhibits#1462 downstream without changing behavior in Spotlight proper.
If this approach is agreeable, I'll update https://github.com/projectblacklight/spotlight/wiki/Creating-a-theme to include details of how to configure this downstream.
=> Allow downstream applications to set exhibit specific themes

app/views/spotlight/about_pages/_contacts.html.erb
Closes sul-dlss/exhibits#1543
This PR applies the same styling to the "About" and "Contacts" headings on about pages.
=> Unify about page header styling

app/assets/stylesheets/spotlight/_translations.scss
Fixes https://github.com/sul-dlss/exhibits/issues/1554
Bootstrap 4 adds for a `.table.table-striped` a top border (BS3 did not have a top border). This reverts for the translation pages the previous table behavior (no top border). 
@ggeisler was there a better way this should be handled that is more globally relevant?
=> Remove top-border for translation page tables

app/assets/stylesheets/spotlight/_catalog.scss
This way the browser reserves 60px for the image content, not just  content and padding
Fixes https://github.com/sul-dlss/exhibits/issues/1559
=> Use box-sizing: content-box for the thumbnail column

app/assets/stylesheets/spotlight/_exhibits_index.scss, app/views/spotlight/exhibits/_exhibit_card.html.erb, app/views/spotlight/exhibits/_exhibit_card_back.html.erb, app/views/spotlight/exhibits/_exhibit_card_front.html.erb, app/views/spotlight/exhibits/_exhibits.html.erb, spec/views/spotlight/exhibits/_exhibit_card_front.html.erb_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1555
This PR aims to do a few different things:
1. Fixes the stacking of 2 x 1 at certain screen resolutions (see gif)
1. Fixes https://github.com/sul-dlss/exhibits/issues/1555
1. aims to reduce the custom Spotlight styling for native BS4 styling
This goes a bit off the rails from what was originally suggested in the ticket, but overall I hope its an improvement in Spotlight for all users.
=> Move front page styling to using flexbox approach and native BS4

app/assets/javascripts/spotlight/admin/sir-trevor/locales.js, app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb, spec/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1208
Only uses two column layout when there is no text. This aims to improve the layout for feature pages.
=> Update solr documents embed column layout logic

app/assets/stylesheets/spotlight/_curation.scss, app/views/spotlight/searches/_search.html.erb
=> Modify browse category edit panels to use flexbox/bootstrap utilities.

app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/featured_images/_form.html.erb, app/views/spotlight/featured_images/_upload_form.html.erb, spec/views/spotlight/contacts/edit.html.erb_spec.rb, spec/views/spotlight/featured_images/_form.html.erb_spec.rb, spec/views/spotlight/featured_images/_upload_form.html.erb_spec.rb
Related to https://github.com/sul-dlss/exhibits/issues/1591
https://getbootstrap.com/docs/4.4/components/forms/#help-text
> Block-level help text in forms can be created using .form-text (previously known as .help-block in v3). Inline help text can be flexibly implemented using any inline HTML element and utility classes like .text-muted.
=> Update help-block to form-text

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
Closes  sul-dlss/exhibits#1588
This increases the font-weight on active `.nav-tabs`.
=> Increase fontweight on active tabs

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
The top and bottom margins for the `fieldset` element, used several places in the admin pages, seem bigger than necessary, creating more whitespace between sections than ideal:
This PR just reduces the top and bottom margins by `1rem` each, which is not dramatic but feels a bit more normal for spacing between sections:
---
=> Reduce fieldset's vertical margins

app/assets/stylesheets/spotlight/_header.scss
This fixes a potential accessibility problem that @jvine discovered.
If an exhibit has an image masthead, as most exhibits probably do, and during a user's session the image used for the masthead background doesn't load for some reason, the result will be white text on a light background that doesn't pass required color contrast for acceptable accessibility:
This PR makes the background of the `.image-masthead` black, so the new result when the masthead image fails to load will be:
This shouldn't affect things when the masthead image loads as expected, nor when an image is not used for the masthead.
=> Add bg-color to image masthead for better a11y

app/assets/stylesheets/spotlight/_translations.scss, app/views/spotlight/about_pages/_contacts_form.html.erb, app/views/spotlight/pages/_order_pages.html.erb
The headings on a few admin pages don't have any top margin and get too close to the content above:
---
---
This PR adds the `mt-4` class used elsewhere for headings in the admin to the headings where we need some top margin:
---
---
Plus all the Curation > Translation pages (not shown) via an `@extend`.
=> Add top margin to admin page headers

app/assets/stylesheets/spotlight/_curation.scss, app/views/spotlight/feature_pages/_header.html.erb
While the height is not exactly the same, this brings things together much more inline with how the draggable page cards are styled.
=> More closely style homepage card fixes #2407

app/assets/javascripts/spotlight/admin/tabs.js, app/views/spotlight/exhibits/_delete.html.erb, spec/views/spotlight/exhibits/edit.html.erb_spec.rb
Closes #2406 
This also fixes a bug where the tabs would not be loaded when the relevant anchor was in the URL.
=> Fix "Export data" link in the Delete Exhibit alert

app/views/catalog/_save_search.html.erb
Also preserves the tab order of save first
=> Use flexbox to align buttons fixes #2420

app/helpers/spotlight/main_app_helpers.rb, app/helpers/spotlight/masthead_helper.rb, app/views/shared/_masthead.html.erb, app/views/spotlight/about_pages/_contacts.html.erb, app/views/spotlight/about_pages/_contacts_form.html.erb, app/views/spotlight/about_pages/_sidebar.html.erb, app/views/spotlight/browse/index.html.erb, app/views/spotlight/dashboards/_analytics.html.erb, app/views/spotlight/dashboards/_page_activity.html.erb, app/views/spotlight/dashboards/_reindexing_activity.html.erb, app/views/spotlight/dashboards/_solr_document_activity.html.erb, app/views/spotlight/exhibits/_delete.html.erb, app/views/spotlight/exhibits/_languages.html.erb, app/views/spotlight/feature_pages/_header.html.erb, app/views/spotlight/feature_pages/_sidebar.html.erb, app/views/spotlight/metadata_configurations/edit.html.erb, app/views/spotlight/pages/_order_pages.html.erb, app/views/spotlight/search_configurations/_search_fields.html.erb, app/views/spotlight/searches/index.html.erb, app/views/spotlight/shared/_configuration_sidebar.html.erb, app/views/spotlight/shared/_curation_sidebar.html.erb, app/views/spotlight/shared/_exhibit_sidebar.html.erb, config/locales/spotlight.en.yml, spec/features/home_page_spec.rb, spec/features/main_navigation_spec.rb, spec/helpers/spotlight/masthead_helper_spec.rb, spec/views/shared/_masthead.html.erb_spec.rb, spec/views/spotlight/browse/index.html.erb_spec.rb, spec/views/spotlight/dashboards/_reindexing_activity.html.erb_spec.rb
This is an attempt to close gaps in the heading structure and ensure that all pages have an appropriate heading.
Closes sul-dlss/exhibits#1601
One area that this doesn't account for is in curator driven pages.  (See the 3rd bullet on sul-dlss/exhibits#1601 and https://github.com/sul-dlss/exhibits/issues/1601#issuecomment-584422430 for relevant discussion) where there is a heading widget that provides an `<h2>` and the widgets themselves have `<h3>` headings.
This doesn't account for all possible scenarios of what curators might want to add to their page (single widget doesn't need a superfluous heading above it, but w/o it there is a heading gap), but is a good step in the right direction.
=> Update heading structure of user facing and admin pages

app/views/spotlight/about_pages/_contact_properties.html.erb
This bug was not present in Firefox.
=> Fixes #2419 Add width-100 to support Chrome width expansion

app/assets/stylesheets/spotlight/_pages.scss
Adds the requested 0.75rem margin.
=> Add margin for zipr button fixes #2430

lib/generators/spotlight/install_generator.rb
`insert_into_class` apparently now requires a class, not a module, and complains about it when you use the generator.
=> Fix generator helper injection

app/assets/stylesheets/spotlight/_spotlight.scss
This was causing duplication of blacklight-gallery and bootstrap styles
in downstream applications. Blacklight-gallery generates itself into an
application and consumers can choose how it should import things.
=> Remove duplicate import of blacklight-gallery

app/assets/stylesheets/spotlight/_sir-trevor_overrides.scss, vendor/assets/stylesheets/sir-trevor/block-controls.scss
I noticed this on a clean generated app while working on something else.
=> Fix sir trevor button styling that was broken

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
This gets everything to line up against the edge  of the sidebar consistently
=> Remove extra left padding from sidebar nav elements

app/views/spotlight/admin_users/index.html.erb
=> Update styling on site-wide user admin dashboard

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss, app/assets/stylesheets/spotlight/_slideshow_block.scss
The current override also hits the actual carousel block, e.g.:
=> Use a more  targeted opacity override; part of #2427

app/views/spotlight/translations/_search_fields.html.erb
=> Add a row class to the sort fields translation page.

app/assets/stylesheets/spotlight/_curation.scss, app/assets/stylesheets/spotlight/_utilities.scss, app/views/spotlight/about_pages/_contact.html.erb, app/views/spotlight/admin_users/index.html.erb, app/views/spotlight/catalog/_edit_default.html.erb, app/views/spotlight/catalog/_index_compact_default.html.erb, app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/custom_fields/_form.html.erb, app/views/spotlight/custom_search_fields/_form.html.erb, app/views/spotlight/dashboards/_page.html.erb, app/views/spotlight/feature_pages/_header.html.erb, app/views/spotlight/metadata_configurations/edit.html.erb, app/views/spotlight/pages/_form.html.erb, app/views/spotlight/pages/_page.html.erb, app/views/spotlight/roles/index.html.erb, app/views/spotlight/search_configurations/_facets.html.erb, app/views/spotlight/search_configurations/_search_fields.html.erb, app/views/spotlight/searches/_form.html.erb, app/views/spotlight/shared/_report_a_problem.html.erb, spec/features/javascript/search_config_admin_spec.rb
Aims to fix https://github.com/sul-dlss/exhibits/issues/1628
We used `.btn .btn-links` in many places, just to size links similarly to buttons. While this is all and good, it prevented default accessibility technology. This PR removes the proliferation of that pattern in favor of using it on actual `<button>` elements as intended while retaining the ability to have a `btn`like size.
I want to verify this w/ @jvine and @ggeisler before shipping.
=> Update btn links

app/views/spotlight/browse/show.html.erb
=> Remove superfluous col-md-12 divs when viewing a browse category.

app/assets/stylesheets/spotlight/_pages.scss
Connected to sul-dlss/exhibits#1653
=> Tighten up spacing overrides we have on the about page sidebar elements.

app/assets/stylesheets/spotlight/_exhibits_index.scss
Pointing  at exhibits:
This isn't a major functional change, but it makes some of the margins and paddings make a little more logical sense.
=> Update exhibit card detail to use flexbox

app/assets/stylesheets/spotlight/_exhibits_index.scss, app/views/spotlight/exhibits/_exhibit_card.html.erb
(and update subtitle + description heights accordingly)
|         | XS | SM | MD | LG | XL |
|-----|----|-----|----|----|----|
| Title |  3  |  3    |  3   |  3  |  3  |
| Subtitle |  3  |  2    |  2   |  2  |  2  |
| Description |  15  |  5    |  4   |  4  |  6  |
| **Total** |  **21**  | **10**    |  **9**   | **9**  |  **11**  |
=> Use line-clamp to truncate exhibit card content

app/assets/stylesheets/spotlight/_exhibits_index.scss
Part of sul-dlss/exhibits#1727
@jvine @ggeisler 
**There are two aims in this PR:**
- make focus styles for exhibit cards more consistent within the same browser (i.e. `outline:auto` is not used for `:focus` in WebKit browsers) 
- enhance native focus on exhibit cards where it is currently insufficient (i.e. Firefox) 
**How do we do this?** 
- unify styles where WebKit is available (i.e. Chrome, Safari) 
- default to Bootstrap focus styles where it's not available (i.e. Firefox)
**Out of scope:** 
- unifying focus styles across Spotlight (some work on this sul-dlss/exhibits#1745)
In the screenshots below I've artificially focused on both exhibit cards and tabs to contrast the exhibit card enhancements with the browser focus styles.
=> Revise exhibit card focus styles

app/assets/stylesheets/spotlight/_accessibility.scss, app/assets/stylesheets/spotlight/_spotlight.scss
This PR aims to unify the experience of focus styles within Firefox. We do this by overriding the default Firefox focus style so that it matches(ish) the Bootstrap focus style (see work on exhibit cards in #2491). @jvine and I paired on this so this just needs dev review.
=> Enhance visibility of Firefox focus indicator globally

app/assets/stylesheets/spotlight/_pages.scss
The sidebar section of feature pages looks fine when there are no child pages, but when there are child pages, the parent feature page list item is too closely vertically to the previous child page list item:
This PR adds some bottom margin to the nested child page list to fix that:
This only affects the feature page sidebar, since we don't have child pages elsewhere.
One minor negative ramification of this is I couldn't avoid adding the new bottom margin to the the parent list item when there are no child pages because of the way the sidebar is rendered (it outputs a `ol.subsection` even when there are no child pages to put in it). I'm going to file a separate ticket for that in case anyone wants to figure out how to omit that element when we don't need it. In the meantime it's not too …
=> Add bottom margin to sidebar sections with child pages

app/assets/stylesheets/spotlight/_pages.scss
Firefox's flex implementation appears to resize the image in odd ways otherwise
Closes sul-dlss/exhibits#1800
_Screenshots in Firefox_
=> Explicitly size the contact-photo image.

app/controllers/spotlight/admin_users_controller.rb, app/controllers/spotlight/exhibits_controller.rb, app/controllers/spotlight/sites_controller.rb, app/helpers/spotlight/title_helper.rb, app/views/shared/_site_sidebar.html.erb, app/views/spotlight/admin_users/index.html.erb, app/views/spotlight/exhibits/new.html.erb, app/views/spotlight/sites/edit.html.erb, app/views/spotlight/sites/edit_exhibits.html.erb, config/locales/spotlight.en.yml, spec/features/create_exhibit_spec.rb, spec/helpers/spotlight/title_helper_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1584
=> Change site admin page headers and add breadcrumbs

app/views/spotlight/browse/_search.html.erb, app/views/spotlight/browse/_search_title.html.erb
This allows downstream applications to make more targeted overrides (like e.g. https://github.com/sul-dlss/dlme/issues/834)
=> Wrap browse category titles in a span

app/controllers/spotlight/translations_controller.rb, app/views/spotlight/translations/_browse_categories.html.erb, app/views/spotlight/translations/_general.html.erb, app/views/spotlight/translations/_import.html.erb, app/views/spotlight/translations/_metadata.html.erb, app/views/spotlight/translations/_page.html.erb, app/views/spotlight/translations/_pages.html.erb, app/views/spotlight/translations/_pages_table.html.erb, app/views/spotlight/translations/_search_fields.html.erb, app/views/spotlight/translations/edit.html.erb, app/views/spotlight/translations/show.yaml.yamlbuilder, config/locales/spotlight.en.yml, config/routes.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/translations_controller_spec.rb, spec/views/spotlight/translations/_import.html.erb_spec.rb
Closes sul-dlss/dlme#868
This feature:
- Add export button that generates Rails-based YML (compatible with Transifex and other i18n tools for other workflows like i18n-tasks, etc. 
- Adds the ability to import a Rails-based YML file to the Curator UI (i.e. a file generated by Transifex)
- Importing a YML file will override any existing translations
- This approach does not include Feature and About pages. This could be ticketed for future work, but I'm doubtful we would revisit that until we reconsider widget frameworks. 
TODOs:
- ~[-]~ add ability to export locales besides `I18n.default_locale` (English for the  generated test app) (splitting out to another ticket)
=> YML import/export for Curator UI translations

app/assets/javascripts/spotlight/admin/blocks/uploaded_items_block.js, app/assets/javascripts/spotlight/admin/sir-trevor/locales.js, app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb, spec/features/javascript/blocks/uploaded_items_block_spec.rb
=> Add Link URL attribute to the uploaded item row widget

app/models/concerns/spotlight/translatables.rb, app/models/spotlight/main_navigation.rb, app/views/spotlight/translations/_import.html.erb, app/views/spotlight/translations/show.yaml.yamlbuilder, config/locales/spotlight.en.yml, spec/controllers/spotlight/translations_controller_spec.rb, spec/models/spotlight/exhibit_spec.rb, spec/views/spotlight/translations/_import.html.erb_spec.rb
Fixes #2516 
This PR builds on work from #2509 to make curator-provided translations exportable to YML files. This PR:
- Adds metadata field labels to YML export
- Updates UI for exporting YML: a user can export both the current language being translated and the default / source language
- adds `#translated_#{attr_name}` methods for looking up strings. My first pass at implementing this involved a lot of conditional logic in the `yamlbuilder`. 
- Lookup for these strings can vary depending on several factors, such as:
- whether the value is in the default locale or a translated language
- whether a value has been provided in a translated language
- whether the value uses Spotlight's default or has been customized by curator (e.g. facet field labels) 
- empty string values have been …
=> Add YML export for locales beside the default language

app/controllers/spotlight/pages_controller.rb, app/views/spotlight/pages/_form.html.erb, spec/controllers/spotlight/home_pages_controller_spec.rb, spec/features/home_page_spec.rb
Fixes sul-dlss/dlme#967
The polymorphic routing seems to choke on allowing us to handle both the has_many feature/about pages relation and the has_one home_page relation the same.
In the case of the has_one relationship we're seeing the "slug" or ID of the page being appended like a format to the URL.
If we explicitly pass a nil format through the form (which should always be HTML and is handled appropriately as the default) and then pass the format param explicitly back through the redirect after update (so updating via API will still work in theory) and things appear to work out both on the home and feature/about pages side of things.
=> Pass format explicitly through page form/controller when updating.

.rubocop.yml, README.md, blacklight-spotlight.gemspec, spec/i18n_spec.rb
[Ruby 2.4 is EOL](https://www.ruby-lang.org/en/downloads/branches/) as of March 31, 2020.
=> Bump Ruby minimum version to 2.5

config/locales/spotlight.ar.yml
Keys related to browse categories were missing an indent.
=> Update Arabic locale file

app/models/spotlight/featured_image.rb, spec/models/spotlight/featured_image_spec.rb
Fixes a regression  introduced  in https://github.com/projectblacklight/spotlight/commit/4d7786c2f6c465e369060dd4f99a84e1853b697b.
This patch seems  in the spirit of the previous implementation, at least? (https://github.com/projectblacklight/spotlight/commit/4d7786c2f6c465e369060dd4f99a84e1853b697b#diff-bcb0a609fba5effed919e646fc3312e1L52)
Fixes https://github.com/sul-dlss/exhibits/issues/1903.
=> Provide IIIF URLs for any image attached to a Spotlight::FeaturedImage

app/assets/stylesheets/spotlight/_pages.scss
When we last updated Spotlight to the latest version of Bootstrap, we styled the About page Contacts sidebar info to indent the second line of a contact person's info when it needed to wrap due to lack of column width.
However, I've heard from several curators who were confused the resulting uneven left alignment of the contact info and thought the page might be broken. I had some concerns about that as well.
This PR updates the styling to go back to the even left alignment of contact info and tries to make distinguishing the wrapped lines of a single piece of contact info from subsequent pieces of info by slightly reducing the line-height (which I think is still sufficient in this context) and slightly increasing the vertical space between each piece of contact info.
In the before and …
=> Adjust styling of About page Contacts info

app/assets/stylesheets/spotlight/_translations.scss, app/views/spotlight/translations/_import.html.erb
=> Update styling of import/export translations section

app/views/spotlight/about_pages/_empty.html.erb, app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/feature_pages/_empty.html.erb, app/views/spotlight/featured_images/_form.html.erb, app/views/spotlight/featured_images/_upload_form.html.erb, app/views/spotlight/home_pages/_empty.html.erb, config/locales/spotlight.en.yml
Goal of this PR is to make some text-related things more consistent in the UI.
I think all strings affected are in the curator admin side of things.
The primary changes are:
- Changed occurrences of "click" to "select" to make the wording less mouse-centric
- When referring to a specific button, wrapped the text referring to the button label in `<b>` (sometimes it was in double-quotes, sometimes not, and when it was wrapped in an element, we were using `<strong>` but `<b>` is the more appropriate element to use because we're not emphasizing the text for importance, just to distinguish it from the surrounding text).
---
---
=> Update text strings to be more consistent in usage

blacklight-spotlight.gemspec
https://github.com/norman/friendly_id/issues/950
=> Pin friendly_id < 5.4.0 until breaking change is reverted or a workaround is in place

app/assets/stylesheets/spotlight/_catalog.scss
When multiple exhibit item tags are assigned to an item they currently display with no spacing between each other, and on the results pages the tags have no special styling. I'm guessing, but I suspect these might be styling regressions that were missed during the upgrade to Bootstrap 4.
This PR adds right-margin after each tag except the last one. It also removes some styling to assign font color, which I think is covered by the use of the Bootstrap `badge-secondary` class, and a line-height specification, which appears no longer needed for the correct line alignment. I don't think removing these should affect any existing implementation, unless there is an implementation that uses a dark color for their page backgrounds and they have reassigned the  `badge-secondary` class to a light …
=> Improve styling of item tags on show and results pages

app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
The browse categories, saved searches, and pages widgets all use the same SCSS to determine how those widgets are rendered, and that SCSS is complex, because these widgets can contain any number of tiles and when used on features pages they might or might not have a sidebar. The SCSS uses complicated and hard to understand logic (saying that as the one who, if I remember correctly, at least wrote the initial version of this SCSS). At some point, the calculations in the SCSS became outdated (Bootstrap breakpoint widths changed, but the SCSS variables using them weren't updated accordingly), resulting in less than ideal display:
- Tiles overlap at the `lg` breakpoint width
- Tile row extends beyond right edge of the main content area
- Margin between tiles is inconsistent
- Tile size not …
=> Improve rendering of browse categories, saved searches, and pages widgets

app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
This PR updates the font sizing for the text displayed on the tiles used in the Browse Categories and Pages widgets. Currently the same font size is used on this widgets, despite the very different tile sizes that are displayed depending on the user's viewport width and whether the page is displaying a sidebar or not. The current font size is usually okay, but in certain cases it is arguably too large, as in the `sm` viewport example below (the problem is more clear than below when the titles are longer than in my example):
This PR adds some adjustments to the font size, taking into account the tile size at different viewports widths and the difference in content area width at the `lg` viewport when there is or isn't a sidebar displayed.  Some examples of how things look with this PR:
--- …
=> Adjust responsive font sizing for browse/pages widget

app/controllers/spotlight/browse_controller.rb, app/models/spotlight/exhibit.rb, app/models/spotlight/group.rb, app/models/spotlight/group_member.rb, app/models/spotlight/search.rb, app/views/spotlight/browse/_search.html.erb, app/views/spotlight/browse/index.html.erb, config/locales/spotlight.en.yml, config/routes.rb, db/migrate/20210113092223_create_spotlight_groups.rb, spec/controllers/spotlight/browse_controller_spec.rb, spec/factories/group.rb, spec/factories/searches.rb, spec/features/browse_category_navigation_spec.rb, spec/models/spotlight/group_spec.rb, spec/models/spotlight/search_spec.rb, spec/views/spotlight/browse/index.html.erb_spec.rb
Part of #2562 
This sets up models and associations to "group" browse categories. The group modeling sets us up for potential polymorphic membership (or, more likely, model re-use for grouping other types of things), but Rails doesn't care for polymorphic `has_many` relations, so we're stuck with the database model being ready for it but with Rails accessors that need to be targeted at specific models 🤷‍♂️ 
For future compatibility, the join table for group members is made explicit in anticipation of emerging or future requirements  (perhaps ordering group members or other features that require some metadata on the membership relation).
TODO:
=> Add Spotlight::Group and Spotlight::GroupMember models

app/controllers/spotlight/searches_controller.rb, app/views/spotlight/searches/_form.html.erb, config/locales/spotlight.en.yml, spec/features/browse_category_admin_spec.rb
=> Fixes #2597 by associating BrowseCategories with Groups

app/views/spotlight/translations/_groups.html.erb, app/views/spotlight/translations/edit.html.erb, config/locales/spotlight.en.yml, spec/features/exhibits/translation_editing_spec.rb
Not specified yet in a ticket I could find, but provides a similar interface to Browse Categories.
=> Adds the ability to provide curator translations to Browse Groups

app/controllers/spotlight/appearances_controller.rb, app/controllers/spotlight/concerns/application_controller.rb, app/controllers/spotlight/pages_controller.rb, app/controllers/spotlight/searches_controller.rb, app/services/spotlight/exhibit_import_export_service.rb, spec/controllers/spotlight/about_pages_controller_spec.rb, spec/controllers/spotlight/feature_pages_controller_spec.rb, spec/controllers/spotlight/home_pages_controller_spec.rb, spec/helpers/spotlight/title_helper_spec.rb, spec/services/spotlight/exhibit_import_export_service_spec.rb
Fixes https://github.com/sul-dlss/dlme/issues/1158
This pull request does two things:
1. Move all of the iiif crop image params to a single helper so that if we change/modify them they won't be different. A previous PR that added a param missed one of these.
2. Unset the iiif_tilesource for a Spotlight::FeaturedImage when importing an exhibit. The rationale here is that this field can be regenerated if unset and could contain some incorrect data coming from a remote image being reimported.
=> Updates to resolve issues with import/export exhibit lifecycle

app/controllers/spotlight/groups_controller.rb, config/i18n-tasks.yml, config/locales/spotlight.en.yml, spec/controllers/spotlight/groups_controller_spec.rb, spec/features/javascript/browse_group_admin_spec.rb
Closes #2613 
A few other updates I made was to add a flash message after a group was deleted consistent with our other flash messages.
=> Update i18n for Spotlight::Group to be named "Browse group"

app/services/spotlight/exhibit_import_export_service.rb, spec/services/spotlight/exhibit_import_export_service_spec.rb
I think I made a mistake in #2624 and now I've tested this with a full round trip to verify that this change should work.
For a given exhibit export with a thumbnail:
```json
],
"thumbnail": {
"display": null,
"source": "exhibit",
"document_global_id": "gid://dlme/SolrDocument/p15795coll21%2F494",
"image_crop_x": null,
"image_crop_y": null,
"image_crop_w": null,
"image_crop_h": null,
"created_at": "2021-01-29 21:24:27 UTC",
"updated_at": "2021-01-29 21:24:27 UTC",
"iiif_region": "250,211,916,688",
"iiif_manifest_url": "https://cdm15795.contentdm.oclc.org/iiif/info/p15795coll21/494/manifest.json",
"iiif_canvas_id": "https://cdm15795.contentdm.oclc.org/digital/iiif/p15795coll21/492/canvas/c0",
"iiif_image_id": "https://cdm15795.contentdm.oclc.org/digital/iiif/p15795coll21/492/annotation/a0", …
```
=> Change unsetting for iiif_tilesource location

app/helpers/spotlight/pages_helper.rb, spec/helpers/spotlight/pages_helper_spec.rb
I believe this will address #2581 (but I'm not 100% sure)
I feel like this may have been the intent of the original code.  The current code passes a single new line character through (and it is not acted on in the markdown), so just creates on paragraph tag w/ the two lines joined by a new line character.
It appears that we could actually remove our `clean_text` (and just ensure `nil` is handled appropriately) however this ends up retaining the `<br>`, which in this case ends up wrapping the two lines with a paragraph tag and joining the two lines with the `<br>`.  While this visually appears the same, it might not necessarily be what the user wanted (and creates an odd inconsistency with what shift+enter does if you press it once vs. twice).
=> Replace line breaks in sir-trevor text blocks with paragraphs

app/views/spotlight/sir_trevor/blocks/_browse_group_categories_block.html.erb
This PR adjusts a few things with the group categories widget for better alignment purposes.
- Makes the browse group categories widget tiles have the same horizontal alignment as the older browse categories widget (compare before and after below to see how currently the browse group categories widget is further left and its tiles are not directly in line with the ones in the row below). This is especially important if a current ever uses those two widgets on the same page and in somewhat close proximity.
- Sets the browse group categories widget title, "view all" link, and nav arrow icons on the same baseline
- Reduces the horizontal space between the browse group categories widget title and the "View all" link
(Note this PR does not try to fix anything with [a ticket](#2653) I just …
=> Adjust alignment of group categories widget elements

app/views/spotlight/exhibits/_exhibit_card_front.html.erb
_NOTE: This was identified as an accessibility error by SiteImprove: Fix accessibility Image with no alt attribute_
The image displayed on the Exhibit card on the home page does not have `alt` attribute.  
As the purpose of the image is decoration, and in keeping with the 3.x solution,  the alt text is added as an empty string.
This issue does not exist in 3.x code.  This PR is set to merge into branch `release-2.x` in order to be included in a future 2.x series release.
=> Accessibility: Image with no alt attribute - Exhibit cards

app/assets/stylesheets/spotlight/_catalog.scss, app/controllers/concerns/spotlight/catalog.rb, app/controllers/spotlight/bulk_actions_controller.rb, app/jobs/spotlight/change_visibility_job.rb, app/models/concerns/spotlight/solr_document/atomic_updates.rb, app/models/spotlight/blacklight_configuration.rb, app/views/catalog/_bulk_actions.html.erb, config/locales/spotlight.en.yml, config/routes.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/bulk_actions_controller_spec.rb, spec/controllers/spotlight/catalog_controller_spec.rb, spec/features/bulk_actions_spec.rb, spec/jobs/spotlight/change_visibility_job_spec.rb, spec/models/spotlight/solr_document/atomic_updates_spec.rb
Fixes #2645 and fixes #2644
Todos:
=> Add bulk action functionality for updating item visibility

app/controllers/spotlight/browse_controller.rb
I'm not sure what the intention should be, my guess would be to not show it.. but lets disable it until we determine how to get the search injected.
=> Do not render the bulk_actions UI on Browse groups

app/views/catalog/_bulk_actions.html.erb
This was causing an issue downstream, but I wasn't able to replicate upstream 🤷 but this works
=> Set empty string as a default for tag input

lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb
Updates list of sir treavor widgets in the generator initializer to match those defined in [lib/spotlight/engine.rb](https://github.com/projectblacklight/spotlight/blob/master/lib/spotlight/engine.rb#L270-L274)
=> generated initializer list of sir treavor widgets should match configured list

app/controllers/spotlight/catalog_controller.rb, spec/controllers/spotlight/catalog_controller_spec.rb
**_NOTE: This replaces PR #2656.  I had problems with the fork associated with that PR because it was out of date.  I had to create a new fork and new PR.  Comments are copied forward from the original PR._**
----
_NOTE: This was identified as an accessibility error by SiteImprove: Link text used for multiple different destinations_
On item show pages (e.g. http://localhost:3000/test-exhibit/catalog/3-9), the "Home" link in the exhibit navigation menu and the "Home" link in the breadcrumbs are going to two different locations. 
| Menu | URL |
| -- | -- |
| "Home" navigation menu | https://localhost/test-exhibit |
| "Home" breadcrumb | https://localhost/test-exhibit?q= |
Change the breadcrumb "Home" link to match the one in the navigation menu.
Fixed a similar issue on line 131 of the same …
=> Accessibility: Link text used for multiple different destinations - Home Links on Exhibit

app/builders/spotlight/bootstrap_breadcrumbs_builder.rb, app/controllers/spotlight/catalog_controller.rb, blacklight-spotlight.gemspec, spec/controllers/spotlight/catalog_controller_spec.rb, spec/features/catalog_spec.rb
The parameter order ends up not matching because rails does something internally to re-order them on us, so we can just tell breadcrumbs_on_rails that it is the current url and bypass the whole thing 🤷 .
=> Add a silly hack so the search results breadcrumb is marked as active

app/uploaders/spotlight/featured_image_uploader.rb, blacklight-spotlight.gemspec, spec/uploaders/spotlight/featured_image_uploader_spec.rb
extension_whitelist has been deprecated upstream:
https://github.com/carrierwaveuploader/carrierwave/blob/13330a70323cde83b319520f5c1874227de79cdf/lib/carrierwave/uploader/extension_whitelist.rb#L35-L36
=> Rename extension_whitelist to extension_allowlist

app/controllers/spotlight/bulk_updates_controller.rb, app/models/concerns/spotlight/exhibit_documents.rb, app/models/spotlight/ability.rb, app/services/spotlight/bulk_updates_csv_template_service.rb, app/views/spotlight/bulk_updates/_download.html.erb, app/views/spotlight/bulk_updates/_overview.html.erb, app/views/spotlight/bulk_updates/edit.html.erb, app/views/spotlight/shared/_curation_sidebar.html.erb, config/locales/spotlight.en.yml, config/routes.rb, lib/spotlight/engine.rb, spec/controllers/spotlight/bulk_actions_controller_spec.rb, spec/controllers/spotlight/bulk_updates_controller_spec.rb, spec/models/spotlight/ability_spec.rb, spec/services/spotlight/bulk_updates_csv_template_service_spec.rb
Part of sul-dlss/exhibits#1995
Closes sul-dlss/exhibits#1996
Closes sul-dlss/exhibits#1997
Closes sul-dlss/exhibits#1998
Closes sul-dlss/exhibits#1999
This will be a bit slow with a large amount of records.  I'm not sure there is much we could do about that unless we put this in the background and email the resulting CSV / CSV download link (which would be a pretty big departure from this)
=> Add the initial bulk updates admin pages

app/assets/stylesheets/spotlight/_modals.scss, app/assets/stylesheets/spotlight/_spotlight.scss, app/views/catalog/_remove_tags.html.erb, config/locales/spotlight.en.yml, spec/features/bulk_actions_spec.rb
There are kind of a lot of text changes but it is pretty straightforward. I just customized the singular case strings and the plural case strings bit more, and updated a few words here and there. 
I also added a sentence to the confirmation dialog, but used the same wording for all confirmation cases to keep it simple.
Also made a couple of very small styling updates. I created a new SCSS partial for the modals because I can foresee downstream implementers wanting to do a bit more styling customization on them.
=> Update text and styling of bulk actions modals

app/assets/javascripts/spotlight/admin/sir-trevor/locales.js, app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb, config/locales/spotlight.en.yml, spec/features/javascript/blocks/solr_documents_block_spec.rb
=> Rename ZPR Viewer/Link to "View larger"

app/views/spotlight/catalog/_edit_default.html.erb, app/views/spotlight/custom_fields/_form.html.erb, app/views/spotlight/custom_search_fields/_form.html.erb, app/views/spotlight/pages/_form.html.erb, app/views/spotlight/resources/_form.html.erb, app/views/spotlight/resources/csv_upload/_form.html.erb, app/views/spotlight/resources/iiif/_form.html.erb, app/views/spotlight/resources/json_upload/_form.html.erb, app/views/spotlight/resources/upload/_form.html.erb
This is pretty minor and only affects admin pages, but currently our Cancel link styling is inconsistent across pages. In some cases the Cancel link is too close to the submit button, and in other cases the Cancel link is styled as a secondary button instead of a link as it elsewhere. 
This PR just adds the `btn-sizing` class to the non-conforming Cancel link cases to make those consistent with the styling elsewhere.
---
---
=> Make Cancel link styling consistent across all pages

app/assets/stylesheets/spotlight/_browse.scss
It isn't super obvious in the default Spotlight implementation, but when you style the browse group filter links to look like buttons, there isn't any vertical spacing between rows when you have enough group filters to wrap to a second row:
---
---
This PR adds some bottom margin to the browse group filter links to provide spacing between rows when the links wrap:
---
---
(I had to be more specific with the selector here than ideal but it was either that or use `!important` to override the default styling for `.main-container .nav`)
=> Add vertical space below browse group filter buttons

app/models/spotlight/feature_page.rb, app/views/spotlight/pages/_form.html.erb
This was probably preventing feature images from being re-saved
=> Remove duplicate belongs_to from Spotlight::FeaturePage

app/jobs/spotlight/process_bulk_updates_csv_job.rb
Without this, `nil` can be present and raise errors in the csv processing job
=> Cast bool check to a string so that strip works effectively

config/locales/spotlight.en.yml
Updates text to better represent how the feature works in practice. The red vertical bars in the screenshot below indicate the sections that I updated (the first is a new paragraph, the second is edits to the existing text).
@caaster Take a look and let me know if you have any suggestions.
---
=> Update text on Bulk updates Download CSV tab page

app/assets/stylesheets/spotlight/_exhibit_admin.scss, app/views/spotlight/bulk_updates/_download.html.erb
Fixes a couple of styling issues. 
---
---
---
---
---
=> Improve layout of the Download CSV options and button

app/controllers/spotlight/job_trackers_controller.rb, app/helpers/spotlight/job_trackers_helper.rb, app/jobs/spotlight/reindex_job.rb, app/models/spotlight/ability.rb, app/models/spotlight/job_tracker.rb, app/views/spotlight/dashboards/_reindexing_activity.html.erb, app/views/spotlight/job_trackers/show.html.erb, config/locales/spotlight.en.yml, config/routes.rb, spec/controllers/spotlight/job_trackers_controller_spec.rb, spec/views/spotlight/dashboards/_reindexing_activity.html.erb_spec.rb, spec/views/spotlight/job_trackers/show.html.erb_spec.rb
Put some information in a modal, linked to from the reindexing activity table's status label.
=> Spike out a way to see Spotlight::Event data related to a job tracker

app/models/sir_trevor_rails/blocks/browse_block.rb, app/models/sir_trevor_rails/blocks/featured_pages_block.rb, spec/models/spotlight/access_controls_enforcement_search_builder_spec.rb
This fixes an issue running the [caption value migration](https://github.com/projectblacklight/spotlight/blob/master/db/migrate/20210308090000_migrate_caption_values_for_title_key.rb#L5) with some versions of rails:
```
Caused by:
ArgumentError: wrong number of arguments (given 1, expected 0)
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.7.0/gems/blacklight-spotlight-3.0.1/app/models/sir_trevor_rails/blocks/browse_block.rb:34:in `as_json'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/core_ext/object/json.rb:154:in `block in as_json'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/core_ext/object/json.rb:154:in `map'
/opt/app/exhibits/exhibits/shared/bundle/ruby/2.7.0/gems/activesupport-6 …
```
=> Allow as_json to accept arguments.

app/jobs/spotlight/reindex_exhibit_job.rb
```
irb(main):001:0> Math.log(0).round
Traceback (most recent call last):
5: from /home/catalina/.nix-profile/bin/irb:23:in `<main>'
4: from /home/catalina/.nix-profile/bin/irb:23:in `load'
3: from /nix/store/gwy6vs99xyxv3f0kflvb8sclgbd81b0m-ruby-2.6.7/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
2: from (irb):1
1: from (irb):1:in `round'
FloatDomainError (-Infinity)
```
=> ReindexExhibitJob#perform: fix when object count is 0

app/assets/javascripts/spotlight/admin/blocks/block.js
This fixes a weird sir-trevor bug where having a heading block on the page breaks any custom block that has `p`  markup in it.
=> Explicitly re-enable p tags for text all of  our custom blocks

config/locales/spotlight.en.yml
REPLACES PR #2580 - The original fork and branch were deleted.  See this PR for the discussion related to the proposed change.
----
Label helpers.action.spotlight/role.destroy is set to Remove from site but is used on the Exhibit Dashboard -> Users list when the action icon is clicked to allow a user to be removed from having a role in the exhibit. I could not find it used anywhere else to remove a user from the entire site.
The action that occurs when the button is clicked is the user is removed from the current exhibit. It has no impact on the user’s roles in other exhibits or their access to the site. The current label is confusing.
=> Change label to Remove from exhibit

app/views/spotlight/sir_trevor/blocks/_iframe_block.html.erb
Allow aria-label and title in iFrames to allow curators to fix iFrame accessibility errors.
=> For accessibility, allow aria-label and title in iFrames

lib/tasks/spotlight_tasks.rake
This is a small PR to add the url slug to the command line prompt for exhibit creation. This will assist in automation of the initialization process - especially for local development via docker, etc.
=> Add prompt for URL slug to command line exhibit creation

CONTRIBUTING.md
The aim here is to provide more information for Spotlight contributors about contribution practices
=> Add a contributing.md document for Spotlight

app/views/spotlight/search_configurations/_facet_metadata.html.erb, app/views/spotlight/search_configurations/_facets.html.erb, spec/features/edit_search_fields_spec.rb, spec/views/spotlight/search_configurations/_facet_metadata.html.erb_spec.rb
Currently, we just assume no further facet limit has been set. Instead, we should see what limit is configured and apply the field-specific limit instead.
This should fix the misreported data for fields in DLME where field limits are configured: 
.
=> Use the actual configured facet limit to determine when to show the 'too many values' version of the count

app/mailers/spotlight/confirmation_mailer.rb, app/models/spotlight/contact_email.rb, app/views/spotlight/confirmation_mailer/confirmation_instructions.html.erb, config/i18n-tasks.yml, config/locales/spotlight.en.yml
fixes #2779
```html
Date: Fri, 25 Feb 2022 09:42:02 -0800
From: please-change-me-at-config-initializers-devise@example.com
Reply-To: please-change-me-at-config-initializers-devise@example.com
To: user@example.com
Subject: Exhibit feedback confirmation
<p>Hello user@example.com,</p>
<br /><br />
<p>An administrator of the asdfasd exhibit has added your email address to the list of feedback form recipients.
<br />This will enable you to receive any feedback submitted through the feedback form by visitors to the asdfasd exhibit.</p>
<p>To receive feedback from this exhibit, confirm your decision through the link below. If you do not want to
<br />receive feedback form submissions from this exhibit, you can ignore this email.
</p>
<br /><br />
<p><a …
```
=> Update confirmation email text

app/models/spotlight/page_configurations.rb, app/views/spotlight/catalog/admin.html.erb, app/views/spotlight/search_configurations/_document_index_view_types.html.erb, app/views/spotlight/searches/_form.html.erb, spec/spec_helper.rb, spec/test_app_templates/catalog_controller.rb
```
DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling gallery) is deprecated. Call it as gallery! or pass initialize arguments. (called from block in <class:CatalogController> at 
[...]
DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling masonry) is deprecated. Call it as masonry! or pass initialize arguments. (called from block in <class:CatalogController> at
[...]
DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling slideshow) is deprecated. Call it as slideshow! or pass initialize arguments. (called from block in <class:CatalogController> at 
[...]
DEPRECATION WARNING: Passing the key argument to ViewConfig#display_label is deprecated. (called from …
```
=> Address upstream deprecation warnings

app/models/sir_trevor_rails/blocks/displayable.rb
Several blocks of sir-trevor-rails display their items in a wrong order
(other than set in the backend) if there are more than ten items.
This bug concerns all blocks including the mixin Displayable:
- FeaturedPagesBlock
- BrowseBlock
- LinkToSearchBlock
- SearchResultsBlock
- SolrDocumentsBlock
The items are sorted in a non-natural order and thereby the item with a
weight of 10 is displayed between the ones with a weight of 1 and that
with a weight of 2.
As ruby does not provide a method for a natural sort order, fix this by
padding the weight with leading zeroes in Displayable#ordered_items
(Forward-port #2819 against 3.x)
=> Fix sort order in sir trevor displayable mixin

app/models/spotlight/search.rb
Fixes https://github.com/sul-dlss/exhibits/issues/2215
=> Apparently query_params can be nil now?

.github/workflows/ruby.yml
This avoids deprecation warnings visible on builds
=> Upgrade to latest actions

app/views/spotlight/shared/_exhibit_sidebar.html.erb, spec/views/spotlight/shared/_exhibit_sidebar.html.erb_spec.rb
If Analytics is not enabled, we should not show an Analytics link in the
sidebar for an Exhibit.
=> Render Analytics link in sidebar when enabled

app/views/spotlight/shared/_report_a_problem.html.erb, spec/features/report_a_problem_spec.rb
alert-primary is based off the brand color where as alert-info is more generally about presenting information.
=> Switch to alert-info for "Reporting from" on the feedback form

app/assets/javascripts/spotlight/application.js
Blacklight's installer already adds these. This prevents two copies from being initialized, which can result in popover toggle links bouncing (open then close).
=> Stop requiring bootstrap components

app/assets/stylesheets/spotlight/_spotlight.scss
This is already imported via the spotlight.scss in template
=> Remove unnecessary include of bootstrap/variables

lib/spotlight/engine.rb
Blacklight 8 refactored how configuration defaults are set, so Spotlight needed to be adjusted to use the appropriate method depending on the version of Blacklight.
=> Use Blacklight::Configuration.default_configuration for Blacklight 8

app/assets/config/spotlight/manifest.js, lib/spotlight/engine.rb
Fixes:
```
Sprockets::Rails::Helper::AssetNotFound: The asset "spotlight/default_thumbnail.jpg" is not present in the asset pipeline.
```
=> Link all the images

app/components/spotlight/document_component.rb, app/controllers/spotlight/catalog_controller.rb, app/views/spotlight/catalog/_curation_mode_toggle_default.html.erb, app/views/spotlight/catalog/_tophat_default.html.erb, spec/controllers/spotlight/catalog_controller_spec.rb
On Blacklight 8 the partials render at the bottom of the component, but we want the edit button in the header.
=> Make the edit button display in the right location on Blacklight 8

README.md
If SKIP_TRANSLATION is not set in the environment when building the application and running the db:migrate then the process will fail as the translation tables will not be present in the database yet.
=> Add SKIP_TRANSLATION for initial setup

app/services/spotlight/etl/solr_loader.rb
Fixes an exception:
```
wrong number of arguments (given 3, expected 2)
```
Alternatively we could have called `pipeline&.context&.on_error` which takes 3 args.
=> Call the on_error handler with the correct number of arguments.

app/models/spotlight/solr_document_sidecar.rb, spec/models/spotlight/solr_document_sidecar_spec.rb
If you happen to have data structures in the sidecar (besides `configured_fields`), things break when you try to convert them to an indexable solr value.
=> Do a better job handling e.g. hash data structures in sidecar data

.rubocop.yml, app/models/concerns/spotlight/browse_category_search_builder.rb, blacklight-spotlight.gemspec, config/locales/spotlight.en.yml, spec/factories/searches.rb, spec/features/browse_category_spec.rb, spec/features/exhibits/translation_editing_spec.rb, spec/models/spotlight/browse_category_search_builder_spec.rb, spec/services/spotlight/iiif_resource_resolver_spec.rb, spec/spec_helper.rb, spec/test_app_templates/catalog_controller.rb
This is a backport of #3004, with extra commits to reflect updated gems, versioning, and syntax in order to pass CI. 
A working search:
=> Backport: use lucene query parser for browse category search

app/models/spotlight/page_content.rb
In rails 7.1, this explicit load causes a LoadError from zeitwerk
=> Prevent explicit require of class in the autoload paths

blacklight-spotlight.gemspec
running tests locally with fresh bundle on main was throwing:
```
Failure/Error: EngineCart.load_application!
NoMethodError:
undefined method `responder' for Devise:Module
```
there seems to have been a bunch of recent work in devise to support turbo, culminating (possibly?) in v4.9.0.
=> Pin devise >= v4.9 for turbo compatibility

.github/workflows/ruby.yml, spec/test_app_templates/lib/generators/test_app_generator.rb
It should work fine with turbo, which is the default in Rails now
=> Drop turbolinks dependency

blacklight-spotlight.gemspec
Several people have been frustrated trying to install on Rails 7.1, so let's have bundler tell them it's not supported rather than figure it out with runtime errors.
=> Make it clear that Spotlight doesn't work with Rails 7.1

.github/workflows/ruby.yml
We were using a specific version of bundler to support ruby 2, but we have since stopped supporting ruby 2, so we can use the latest version
=> Use latest version of bundler

spec/models/spotlight/page_spec.rb
Rails 7.1 changes the autoloader behavior, and this require throws an error.
I don't think this require is needed any longer. Maybe in Rails 6.1 if using the classic autoloader?
=> Remove unnecessary require

.github/workflows/ruby.yml
This fixes the problem where the importmap:install task wouldn't run due to unresolved dependencies.:
```
Installing rails 7.0.8.4
Bundle complete! 11 Gemfile dependencies, 62 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
run  bundle binstubs bundler
rails  importmap:install
/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.14/lib/bundler/definition.rb:594:in `materialize': Could not find rails-7.0.8.4, sprockets-rails-3.5.1, sqlite3-1.7.3-x86_64-linux, puma-5.6.8, importmap-rails-2.0.1, turbo-rails-2.0.5, stimulus-rails-1.3.3, debug-1.9.2, web-console-4.2.1, actioncable-7.0.8.4, actionmailbox-7.0.8.4, actionmailer-7.0.8.4, actionpack-7.0.8.4, actiontext-7.0.8.4, actionview-7.0.8.4, activejob-7.0.8.4, activemodel-7.0.8.4, …
```
=> Disable bundler cache

app/controllers/spotlight/solr_controller.rb
Within the "Add items" function the "Upload raw documents" feature was broken because the code used "repository" which was not defined. Fix appears to behave, though obviously this is very much a feature for expert use, and I am not yet an expert.
=> Raw document upload broken: fixed to access Solr via blacklight_config

app/controllers/spotlight/resources/upload_controller.rb
Raising for missing callback actions is a new default in Rails 7.1.
We have `only: [:create]` for this.
=> Remove missing callback action

app/helpers/spotlight/meta_helper.rb
The opengraph metadata for images was being encoded with a property attribute of og:og:image instead of og:image.
=> Correct the property attribute for og:image meta tags

spec/features/javascript/blocks/solr_documents_block_spec.rb, spec/features/javascript/blocks/uploaded_items_block_spec.rb
Playing around with solutions for #3039.
Trying to see if we can get Capybara to wait for the thumbnail.
Definitely seems to be load dependent. The tests get less flaky locally the further I get into Friday afternoon...
=> Wait for data to load in flappy test

app/models/spotlight/blacklight_configuration.rb, app/models/spotlight/contact.rb, app/models/spotlight/custom_field.rb, app/models/spotlight/custom_search_field.rb, app/models/spotlight/exhibit.rb, app/models/spotlight/resource.rb, app/models/spotlight/search.rb, app/models/spotlight/solr_document_sidecar.rb
The positional argument is deprecated and will be removed in rails 7.2
=> Pass the class argument to serialize as a keyword

app/models/spotlight/resources/upload.rb, lib/spotlight/riiif_service.rb, spec/controllers/spotlight/catalog_controller_spec.rb, spec/controllers/spotlight/contact_email_controller_spec.rb, spec/controllers/spotlight/solr_controller_spec.rb, spec/models/spotlight/resources/upload_spec.rb
The manifest controller expects the URL to include the exhibit ID and resource ID, but the indexer has been using the ID of the resource's `FeaturedImage` instead.  This doesn't always cause issues, because in many situations the ID of a resource's `FeaturedImage` and the ID of the resource itself have the same numerical representation.  But those numbers can fall out of sync, and manifests will fail to load.
Meanwhile, update the `iiif_service#info` method to expect the ID of a `FeaturedImage` rather than a `Resource`.  This brings it in line with the other `RIIIFService` helper methods and is how `Spotlight::CarrierwaveFileResolver` behaves.
=> Fix ID handling in IIIF helper methods

spec/features/catalog_spec.rb
Prevent a future regression of the issue reported in https://github.com/projectblacklight/spotlight/issues/2992 and fixed in https://github.com/projectblacklight/spotlight/pull/3060
=> Add test to check that image viewer is rendered on the exhibits show page

.github/workflows/ruby.yml, spec/test_app_templates/lib/generators/test_app_generator.rb
We're not actually testing with Blacklight 8 now. Maybe https://github.com/projectblacklight/spotlight/issues/3047 will get us there, but until then we should remove the misleading builds.
=> Generate + test with the requested blacklight version.

app/views/spotlight/catalog/_index_compact_default.html.erb, spec/features/item_admin_spec.rb
Part of #2992
`render_document_partial` isn't able to find the `_admin_thumbnail_default.html.erb` partial with the full path specified.
=> Restore item thumbnails in admin view

.github/ISSUE_TEMPLATE/accessibility.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/maintenance.md
To help organize issues through the use of consistent labels as well as title prefix. 
The title prefix could be useful in email notifications.  If this is not preferred, I can take them out. 
5 templates are suggested in this PR, the labels are chosen from existing labels. 
Any changes and thoughts welcome.
=> Introducing GitHub issue templates

.github/workflows/ruby.yml
Ruby 3.2.5 was released, so bump our permissions change.
Chrome broke alert handling which causes some tests to fail.
https://issues.chromium.org/issues/351858989
Pin to a working version, 126, until they release a fix.
=> Update CI configuration

app/assets/stylesheets/spotlight/_bootstrap_overrides.scss, app/views/spotlight/contacts/_form.html.erb, app/views/spotlight/exhibits/_contact.html.erb, app/views/spotlight/exhibits/_form.html.erb, app/views/spotlight/featured_images/_form.html.erb, app/views/spotlight/featured_images/_upload_form.html.erb, app/views/spotlight/translations/_browse_categories.html.erb, app/views/spotlight/translations/_general.html.erb, app/views/spotlight/translations/_metadata.html.erb, app/views/spotlight/translations/_search_fields.html.erb
Fixes: #3089
Fixes: #3086
Fixes: #3085
Fix does not change the BS4 display.
Before:
After:
=> Use div instead of small for form-text

app/assets/stylesheets/spotlight/_translations.scss, app/views/spotlight/translations/_import.html.erb
Before:
After:
No impact to Bootstrap 4 layout
=> Fix translation export button layout for BS5

app/views/spotlight/bulk_updates/_upload.html.erb
=> Fix Upload CSV form layout for BS5

app/views/spotlight/bulk_updates/_download.html.erb
=> Add mb-3 to bulk download form group labels to even out spacing for BS5

app/views/spotlight/bulk_updates/_upload.html.erb
With `offset-md-3` set on the help `div` without `col-md-9` it was breaking out of the main container.
Before:
After:
=> Set col-md-9 on bulk upload help div

app/models/sir_trevor_rails/blocks/solr_documents_carousel_block.rb, app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb, app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
'false' is no longer a valid value for interval in BS5 carousels (https://getbootstrap.com/docs/5.2/components/carousel/#options). If interval is set to false, the carousel goes crazy mode (Warning: rapid flashing):
https://github.com/user-attachments/assets/14c8eb02-57b1-461b-a847-d9d907ef2253
For the static carousel we can omit ride and interval because a static carousel is the default in BS5.
=> Fix Sir Trevor Bootstrap 5 carousel blocks

app/views/spotlight/shared/_dd3_item.html.erb
This fixes a layout regression from adding BS5 support
Before:
After:
=> Add margin to right/end of page publish checkbox

.github/workflows/ruby.yml, blacklight-spotlight.gemspec, spec/jobs/spotlight/reindex_job_spec.rb
`acts-as-taggable` 11 is released and supports ActiveRecord versions `< 8`. This will let us update spotlight apps to Rails 7.2
We need a new release of riiif too with these changes: https://github.com/sul-dlss/riiif/pull/146 I think.
=> Allow acts-as-taggable 11 and Rails < 8

README.md
This separates and clarifies instructions for updating the JS bundle and instructions for releasing a new version of the gem and JS bundle to npm.
=> Update release instructions in README

spec/features/javascript/blocks/browse_group_categories_block_spec.rb, spec/features/javascript/blocks/featured_browse_categories_block_spec.rb, spec/features/javascript/blocks/featured_pages_block_spec.rb, spec/features/javascript/blocks/link_to_search_block_spec.rb, spec/features/javascript/blocks/rule_block_spec.rb, spec/features/javascript/blocks/search_result_block_spec.rb, spec/features/javascript/blocks/solr_documents_block_spec.rb, spec/features/javascript/blocks/solr_documents_carousel_block_spec.rb, spec/features/javascript/blocks/uploaded_items_block_spec.rb, spec/features/javascript/multi_image_select_spec.rb, spec/support/features/test_features_helpers.rb
This fixes a rubocop error and uses a clearer name.
=> Rename test helper save_page to save_page_changes

lib/spotlight/engine.rb
Fixes https://github.com/projectblacklight/spotlight/issues/2966
=> Explicitly allow browse category ID in search state

app/assets/stylesheets/spotlight/_header.scss, app/views/layouts/spotlight/base.html.erb
=> Style the skip links to look ok.

app/models/spotlight/blacklight_configuration.rb, app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb, spec/features/javascript/blocks/solr_documents_embed_block_spec.rb, spec/test_app_templates/catalog_controller.rb
Blocked by https://github.com/projectblacklight/blacklight-gallery/pull/151
Closes ##3111
We now see the viewer:
=> Pass the tile_source_field to blacklight-gallery

app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
Relates to having tests pass with Blacklight 8 (specially 8.3).
For 8.3, the following test is failing:
rspec ./spec/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb_spec.rb:48 # spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb without a primary caption falls back to the regular document title for the caption
The reason appears to be when the truncate method is passed an integer, e.g. truncate(1, length:95), it throws an error.  However, truncate("1", length:95) will work just fine. Adding a "to_s" ensures the caption text truncation does not throw an error. 
This test should still pass in Blacklight 7. 
How to test with Blacklight 8: Generate test app (.internal_test_app). Update the internal test app's Gemfile to use Blacklight 8.3.  Run …
=> ensure string is passed to truncate since errors with integers

.github/workflows/ruby.yml
Make Rails 7.2 our primary CI version and clean up other builds because:
- Rails 7.0 is out of active support upstream.
- Rails 7.1 is out of active support in another week (and has another year of security support)
=> Update build matrix.

spec/controllers/spotlight/catalog_controller_spec.rb
Blacklight 8 short-circuits some HTML safe-ing when it isn't necessary (and it isn't here.) At least for now, we can support either version 🤷‍♂️
=> Support html-safe (BL7) and non-html-safe (BL8) versions of the title for breadcrumbs

app/views/spotlight/pages/_view_type_group.html.erb, spec/test_app_templates/catalog_controller.rb
This updates our test catalog controller to match blacklight-gallery's (newer) generated configuration. The icon class configuration does require that we use the `ViewTypeButtonComponent` to render icons on feature pages, but it's been available since Blacklight 7.18.
=> Use icon components for gallery views.

app/controllers/spotlight/catalog_controller.rb, app/views/spotlight/catalog/_document_admin_table.html.erb
It's possible downstream application:
- render the document admin table partial outside the `catalog#admin` action, or
- customized the `admin_table` view but haven't updated it to use view components yet.
A little more defensive programming should help avoid breaking things 🤷‍♂️
=> Add a default document component for the admin table + blacklight 7.

app/models/spotlight/analytics/ga.rb
closes https://github.com/sul-dlss/exhibits/issues/2592
=> ga similar named exhibit collision fix

app/controllers/spotlight/bulk_updates_controller.rb, config/locales/spotlight.en.yml
closes https://github.com/sul-dlss/exhibits/issues/2595
=> add breadcrumbs to bulk_updates page

app/components/spotlight/tag_list_form_component.html.erb, app/components/spotlight/tag_list_form_component.rb, app/controllers/spotlight/exhibits_controller.rb, app/views/spotlight/exhibits/_form.html.erb, app/views/spotlight/exhibits/_new_exhibit_form.html.erb, lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb, lib/spotlight/engine.rb, spec/features/exhibits/administration_spec.rb
closes https://github.com/sul-dlss/exhibits/issues/2492
screenshot is for when ```Spotlight::Engine.config.site_tags = ['tag 1', 'tag 2', 'tag 3', 'tag 4', 'tag 5', 'tag 6', 'tag 7', 'tag 8', 'tag 9', 'tag 10', 'tag 11', 'tag 12']```
=> add controlled vocab functionality for tag_list

app/views/shared/_exhibit_navbar.html.erb, lib/generators/spotlight/templates/catalog_controller.rb, spec/test_app_templates/catalog_controller.rb
https://github.com/projectblacklight/spotlight/commit/5fd1d64bbd2e7e9281830fb0fb72d6b50c0f5c15 set this config at `blacklight_config.index`. However, the previous implementation with the navbar set in a partial instead of a component assumed there'd just be one exhibit navbar.
=> Don't scope exhibit_navbar_component setting to view type

blacklight-spotlight.gemspec
This clears up the failing test from the openseadragon rails issue.
Some configs will still fail because: `error Couldn't find any versions for "blacklight-frontend" that matches "7.39.0"`
The Docker build issue I'll work on in another PR.
=> Require version of OSD rails that supports turbo

.env, docker-compose.yml
These unused volumes are likely copypasta and are misleading about the use of redis.
=> Remove unused docker volumes

app/views/layouts/spotlight/base.html.erb
This is critical when using module based javascript, because the inline scripts occur ahead of deferred scripts. All module scripts are deferred by default. Script tags without a src attribute can not be deferred.
=> Defer configuration until the script is loaded

Dockerfile, template.rb
This ensures the importmap generator runs before any of the spotlight generators
=> Use after_bundle in the template

app/views/shared/_exhibit_navbar.html.erb
Closes #3200 .
What this PR does:
Updates the code to only throw a deprecation warning if the exhibit navbar component is not set in the configuration.
=> Preventing exhibit navb deprecation messages when not needed

.env, Dockerfile, compose.yaml
It is not a required dependency of Spotlight.
=> Remove Postgresql from the Docker build

Rakefile, lib/generators/spotlight/assets/propshaft_generator.rb
I think this is better suited here rather than in the generator.
=> Precompile assets before testing

app/controllers/spotlight/resources/csv_upload_controller.rb
=> have csv export template use slug for custom fields to match import

app/views/layouts/spotlight/base.html.erb
This reverts commit 17ca2998f5386c39ecd54c6b2d80feffc9a8b6b4.
From https://github.com/projectblacklight/spotlight/pull/2919
This breaks Sir Trevor icons for Exhibits.
=> Revert "Defer configuration until the script is loaded"

spec/features/javascript/blocks/uploaded_items_block_spec.rb
This test is flappy and has failed for me 10+ times today. For whatever reason it seems that sometimes the avatar fixture image precedes the 800x600 image when running on CI. Checking to see if moving the existing expect guards help with this.
=> Increase reliability of ZPR link test

spec/features/javascript/block_controls_spec.rb
I think we should add a test for checking if the Sir Trevor icons were successfully loaded. They are currently broken.
=> Add a test to check if the Sir Trevor icons loaded

app/assets/stylesheets/spotlight/_spotlight.scss
closes #3228 
https://github.com/projectblacklight/blacklight/blob/v7.39.0/app/assets/stylesheets/blacklight/_icons.scss#L2-L7 got removed in blacklight 8. I added a variation in _spotlight.scss.
=> add css for btn blacklight icons

app/components/spotlight/analytics/dashboard_component.rb, spec/components/spotlight/analytics/dashboard_component_spec.rb
Adjusts tests to use fixed dates so we don't need to rely on private`formatted_date` method in the tests.
=> Specify methods as private in Analytics::DashboardComponent

.github/workflows/ruby.yml, blacklight-spotlight.gemspec, lib/generators/spotlight/assets/propshaft_generator.rb, package.json, spec/test_app_templates/lib/generators/test_app_generator.rb, template.rb
This is for the `migrate-asset-pipeline` branch.
Removes testing for Blacklight 7 and switches the defaults to Blacklight 8.
It does not remove all the other Blacklight 7 related code. As we continue work on what is anticipated to be for Spotlight v5 we want to focus our efforts on Blacklight 8 but leave the option to pivot back to supporting Blacklight 7 if need be.
=> Remove active support for Blacklight 7

app/components/spotlight/solr_document_legacy_embed_component.rb
This is an extension on #3244; now that we're passing the block to the document component, we might as well keep track of it and make it available to the embed component at least.
=> Pass the block context through to the embed component

app/components/spotlight/document_admin_table_component.html.erb
Before this fix, when clicking on the link the url will look like this: http://localhost:3000/test-f71f4f09-8669-4b2f-8121-23ff6ceaaa30/catalog/%3Ca%20href=%22/test-f71f4f09-8669-4b2f-8121-23ff6ceaaa30/catalog/7-113%22%3ESHEPARD'S%20ALABAMA%20CITATIONS%3C/a%3E
=> fix view link to work correctly

.github/workflows/ruby.yml
It was also causing CI to fail since ruby 3.2.6 was released
=> Changing permission of gem directory is no longer needed

.solr_wrapper
With https://github.com/cbeer/solr_wrapper/pull/154 in, I think this pin can be removed.
=> Unpin solr_wrapper version

blacklight-spotlight.gemspec
See https://github.com/ruby/uri/issues/125
=> Unpin uri; v1.0.1 fixes carrierwave issue

app/components/spotlight/breadcrumbs_component.rb
closes https://github.com/sul-dlss/exhibits/issues/2638
Fix was due to me using the wrong way to compute path. I looked at how breadcrumb_rails did this and updated it to use the else in here: https://github.com/weppos/breadcrumbs_on_rails/blob/4e74436c0f3f5cdc16d05de92b67d97a45ba545a/lib/breadcrumbs_on_rails/breadcrumbs.rb#L56C7-L65C10. From what I can tell spotlight isn't using Proc or Symbols so I don't think we need to add it back in.
=> fix breadcrumbs for polymorphic paths

app/components/spotlight/skip_link_component.rb, app/views/layouts/spotlight/base.html.erb, lib/spotlight/engine.rb
Closes #3226.
Reported on the `migrate-asset-pipeline` branch but I think this is fine for main.
=> Use SkipLinkComponent for Blacklight 8

app/models/spotlight/custom_field.rb, app/services/spotlight/exhibit_import_export_service.rb, spec/models/spotlight/custom_field_spec.rb
closes #2983
What I found with this is when update runs for the license field, it makes the config :label => 'License' not 'label' => 'License'. I checked the data. It looks exactly the same as all the other fields.
=> fix for import using :label instead of 'label' for some custom fields

app/helpers/spotlight/application_helper.rb
The line in "content?" which strips out comment lines was throwing an error for me locally when I set up a test exhibit and clicked the edit button on the home page of the exhibit. 
This fix prevents an error being thrown if the field content is empty/nil. (Better solutions may exist).
=> fix error if field does not have content

app/components/spotlight/tag_list_form_component.html.erb
=> Add bootstrap 5 markup to tag form

app/assets/stylesheets/spotlight/_mixins.scss
In bootstrap 5 the text is white without sufficient contrast on the yellow background.
Before:
After:
=> Set private label text color to black

app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
Text and image should be able to be placed on the left or right side and the text should wrap around the image.
Before
After
=> Set items-block class on uploadeditems block widget so layout is correct in Bootstrap 5

app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
Backport https://github.com/projectblacklight/spotlight/pull/3277 to v4
=> Backport: Adjust uploaded item row markup so text wraps around image in bootstrap 5

app/components/spotlight/tag_list_form_component.html.erb
Backport of https://github.com/projectblacklight/spotlight/pull/3275 to release 4.x
=> Backport: Add bootstrap 5 markup to tag form

app/views/spotlight/exhibits/_form.html.erb, app/views/spotlight/searches/_form.html.erb, config/locales/spotlight.en.yml, spec/features/browse_category_admin_spec.rb
Second label is an accessibility issue for screen readers.
closes #3271
=> fix published label alignment, remove second label for checkbox

app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
Backport of https://github.com/projectblacklight/spotlight/pull/3287 to release-4.x
=> Backport set width auto on uploaded item text block so it wraps around images

app/controllers/spotlight/accessibility_controller.rb, app/views/spotlight/accessibility/alt_text.html.erb
closes https://github.com/sul-dlss/exhibits/issues/2656
To recreate, create a feature page. Add an item row widget. Save without adding an item. This means there will be zero items that can have alt text. 
Also for old instances of spotlight, the alt_text fields don't exist. Also the line ```next if item['alt_text_backup'].nil?``` is not necessary anymore since we are using the model to determine which fields can have alt text (this is leftover from a different approach).
=> allow for no items, no alt_text in model

app/views/spotlight/shared/_exhibit_sidebar.html.erb, spec/views/spotlight/dashboards/analytics.html.erb_spec.rb
Fixes an error in our exhibits app that has its own admin templates that render the sidebar:
```
tionView::Template::Error (undefined method `exhibit_alt_text_path' for #<ActionView::Base:0x0000000011f2d8>):
Causes:
NoMethodError (undefined method `exhibit_alt_text_path' for #<ActionView::Base:0x0000000011f2d8>)
4:   <% if current_exhibit.analytics_provider&.enabled? %>
5:   <%= nav_link t(:'spotlight.curation.sidebar.analytics'), spotlight.analytics_exhibit_dashboard_path(current_exhibit) %>
6:   <% end %>
7:   <%= nav_link t(:'spotlight.accessibility.header'), exhibit_alt_text_path(@exhibit) %>
8: </ul>
9: <%= render 'spotlight/shared/configuration_sidebar' if can? :update, current_exhibit %>
10: <%= render 'spotlight/shared/curation_sidebar' %>
app/views/viewers/edit.html.erb:2 …
```
=> Namespace reference to exhibit_alt_text_path

app/controllers/spotlight/accessibility_controller.rb, spec/features/alt_text_dashboard_spec.rb
cleanup in the controller for initial cruft that I missed.
=> add alt-text spec

app/views/spotlight/shared/_honeypot_field.html.erb
From https://github.com/sul-dlss/exhibits/issues/2497
Fixes one instance of "Element div not allowed as child of element span in this context."
=> Change wrapping tag on honeypot field

app/views/spotlight/shared/_honeypot_field.html.erb
Fixes one instance of "Element div not allowed as child of element span in this context."
=> backport: Change wrapping tag on honeypot field

app/views/spotlight/bulk_updates/_upload.html.erb, app/views/spotlight/translations/_import.html.erb
closes #3300 
To work only with bs5 we can remove `<div class="input-group-append">`.
=> make input-group-append work with bs4 and bs5

app/views/spotlight/feature_pages/_header.html.erb
Page: `/spotlight/{EXHIBIT_SLUG}/feature`
Before:
After:
=> Set bg-light on card to fix border

app/controllers/spotlight/accessibility_controller.rb, spec/features/alt_text_dashboard_spec.rb
right now if a page has any widgets that have alt text it counts all widgets toward the total. This fixes that.
=> account for mixed sirtrevor widget pages

.github/workflows/ruby.yml, Dockerfile, README.md, Rakefile, blacklight-spotlight.gemspec, lib/generators/spotlight/assets/importmap_generator.rb, lib/generators/spotlight/assets/propshaft_generator.rb, lib/generators/spotlight/templates/assets/spotlight.scss, spec/test_app_templates/lib/generators/test_app_generator.rb, template.rb
Blacklight 8.7.0 contains a backport of https://github.com/projectblacklight/blacklight/pull/3340 which alters the ordering of the install generators.
This PR:
* Removes the workarounds we had in place, waiting for that change
* Sets Blacklight 8.7.0 as the minimum required version. After a conversation with @corylown we think that's fine because no version of Spotlight v5 has been released yet.
* Moves to assuming Spotlight will be built using `--css bootstrap`
* Abandons Rails 7.0 as it handles our rails new options differently than subsequent releases
=> Update generators to handle Blacklight 8.7.0

app/components/spotlight/header_navigation_link_component.html.erb, app/components/spotlight/header_navigation_link_component.rb, app/views/shared/_about_navbar.html.erb, app/views/shared/_browse_navbar.html.erb, app/views/shared/_curated_features_navbar.html.erb, lib/spotlight/engine.rb, spec/components/spotlight/header_navigation_link_component_spec.rb
We will find this helpful in our app, because we can just override this component rather than have to copy 3 partials into our local app just to change some classes in the markup
=> Extract the HeaderNavigationLinkComponent

app/assets/stylesheets/spotlight/_blacklight_overrides.scss, app/views/spotlight/browse/_search_box.html.erb
This makes it possible to remove these classes in a downstream application if not desired.
=> Apply bootstrap classes without requiring SASS

app/helpers/spotlight/main_app_helpers.rb
This occurs any time the theme is "default" and the page is drawn, so that's a lot of warn messages.
=> Downgrade theme missing message to a debug

app/assets/stylesheets/spotlight/_blacklight_configuration.scss
It looks like this may have been added to work around an issue with a now 10 year old version of Firefox (https://github.com/projectblacklight/spotlight/pull/380). As far as I can tell it's no longer needed and removing it fixes a display issue when the content of the table wraps and causes the height of the row to increase.
Before:
After:
=> Remove "position: relative" from .handle-wrap to fix handle display

app/components/spotlight/bulk_action_component.html.erb, app/components/spotlight/bulk_action_component.rb, app/views/catalog/_bulk_actions.html.erb, spec/features/bulk_actions_spec.rb
This will enable downstream apps to easily set the css classes on the button
=> Extract BulkActionsComponent

app/views/layouts/spotlight/base.html.erb
Currently none of the default Leaflet icons will resolve. Leaflet builds the paths here:
https://github.com/Leaflet/Leaflet/blob/142f94a9ba5757f7e7180ffa6cbed2b3a9bc73c9/src/layer/marker/Icon.Default.js
The image assets will be present locally in `node_modules` for the style assets, but those icon paths are built & used after the propshaft digest steps. I think it's easiest just to point at the CDN.
Looks like Geoblacklight did similar: https://github.com/geoblacklight/geoblacklight/blob/bee5ae91cfee1fba8084a6e1d9a3f05d6a0cea00/app/javascript/geoblacklight/controllers/leaflet_viewer_controller.js#L44
=> Set imagePath for Leaflet

app/helpers/spotlight/main_app_helpers.rb
backport: https://github.com/projectblacklight/spotlight/pull/3340 to release-4.x
=> Backport: Downgrade theme missing message to a debug

app/components/spotlight/bulk_action_component.html.erb, app/components/spotlight/bulk_action_component.rb, app/views/catalog/_bulk_actions.html.erb, spec/features/bulk_actions_spec.rb
This will enable downstream apps to easily set the css classes on the button
Backports https://github.com/projectblacklight/spotlight/pull/3347/ to release-4.x
=> Backport: Extract BulkActionsComponent

spec/features/autocomplete_typeahead_spec.rb, spec/features/javascript/blocks/solr_documents_block_spec.rb, spec/support/features/test_features_helpers.rb
This dramatically reduces or eliminates erroneous test failures surrounding Sir Trevor widgets. It does increase the time to run the tests, but I feel that's better than having to restart them 2-4 times. It does this by moving and improving some of our in-test checks/guards/sleeps to the helpers.
I think after this, there is only one major flappy test remaining (in `spec/features/javascript/edit_in_place_spec.rb`).
=> Increase reliability of Sir Trevor feature tests

lib/generators/spotlight/assets/generator_common_utilities.rb, lib/generators/spotlight/assets/importmap_generator.rb, lib/generators/spotlight/assets/propshaft_generator.rb, spec/test_app_templates/lib/generators/test_app_generator.rb
Now that `app.config.assets.paths << Rails.root.join('node_modules')` has been removed via https://github.com/projectblacklight/spotlight/pull/3378 we can go back to using `yarn link` for the test app. It seems like that fixes our previous infinite propshaft issue.
This fixes the test app build, which is currently broken:
```
07:58:13 css.1  | Error: Can't find stylesheet to import.
07:58:13 css.1  |   ╷
07:58:13 css.1  | 5 │ @import "spotlight-frontend/vendor/assets/stylesheets/bootstrap-tagsinput";
07:58:13 css.1  |   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:58:13 css.1  |   ╵
07:58:13 css.1  |   app/assets/stylesheets/spotlight.scss 5:9              @import
07:58:13 css.1  |   app/assets/stylesheets/application.bootstrap.scss 4:9  root stylesheet …
```
=> Use 'yarn link' in the test app

app/javascript/spotlight/admin/croppable_modal.js
97% sure this bug is happening because the blacklight modal is reloading the modal on the second click and since the modal is already loaded it is rerunning the initialization of the cropper.
Tested this locally and it fixed things.
closes #3384
=> fix double click bug

lib/generators/spotlight/install_generator.rb
Update the v4 installer to work with the newest openseadragon/blacklight-oembed gems.
Currently I think it's best to leave all the sprockets config work out of the OSD gem. If Spotlight v4 still cares about sprockets we can make it do the work, especially since Spotlight v4 is a bit of a special case, deleting `app/javascript/application.js`.
=> Add config for updated gems

spec/test_app_templates/lib/generators/test_app_generator.rb
Trying to fix this error when backporting:
```
SyntaxError: --> /home/runner/work/spotlight/spotlight/.internal_test_app/config/initializers/assets.rb
syntax error, unexpected constant, expecting end-of-input
>  4  Rails.application.config.assets.version = "1.0"
>  8  Rails.application.config.assets.paths << Rails.root.join("node_modules/bootstrap/dist/js")
>  9  Rails.application.config.assets.paths << Rails.root.join("node_modules/bootstrap-icons/font")
> 10  Rails.application.config.assets.paths << Rails.root.join("node_modules/bootstrap/dist/js")
> 11  Rails.application.config.assets.precompile << "bootstrap.min.js"Rails.application.config.assets.precompile += %w( application_modern.css )
```
=> Add newline to test app generator

.env, Rakefile, compose.yaml, lib/generators/spotlight/templates/solr/conf/solrconfig.xml
Backport https://github.com/projectblacklight/spotlight/pull/3209 and https://github.com/projectblacklight/spotlight/pull/3417 to release-4.x
=> Backport: Prefer docker for starting solr; support Solr 9.8

app/controllers/spotlight/accessibility_controller.rb, app/models/sir_trevor_rails/block.rb, app/models/sir_trevor_rails/blocks/solr_documents_block.rb, app/models/sir_trevor_rails/blocks/solr_documents_embed_block.rb, app/models/sir_trevor_rails/blocks/uploaded_items_block.rb
This shows that the class supports having alt text, but does not have the alt text itself.
=> Give a more descriptive name to a method

app/assets/stylesheets/spotlight/_exhibits_index.scss
Before
After
closes https://github.com/sul-dlss/exhibits/issues/2819
=> fix long exhibit title display

app/views/spotlight/exhibits/_contact.html.erb
Currently this error is red text on a red background. This removes the red background.
=> Remove background color on contact error

spec/services/spotlight/iiif_resource_resolver_spec.rb
Seems like "unexpected token" has become "unexpected character" for some version. I don't think we need to have this level of specificity.
=> Check for less specific error message

app/assets/stylesheets/spotlight/_curation.scss, app/assets/stylesheets/spotlight/_sir-trevor_overrides.scss, app/components/spotlight/bulk_action_component.rb, app/components/spotlight/save_search_component.rb, app/jobs/concerns/spotlight/job_tracking.rb, app/views/shared/_site_sidebar.html.erb, app/views/spotlight/admin_users/index.html.erb, app/views/spotlight/catalog/_admin_header.html.erb, app/views/spotlight/exhibits/_delete.html.erb, app/views/spotlight/metadata_configurations/_metadata_field.html.erb, app/views/spotlight/resources/upload/_form.html.erb, app/views/spotlight/roles/index.html.erb, app/views/spotlight/shared/_dd3_item.html.erb, app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb, app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb, lib/generators/spotlight/scaffold_resource_generator.rb
Stanford is currently migrating away from two different color buttons on the page based on UX designers. Moving away from this might also be preferable to community but we want to check with the community before merging.
=> migrate secondary-btns to primary

spec/features/javascript/edit_in_place_spec.rb
This test flakes out sometimes on CI, including several times today.
The thought here is maybe sometimes it's managing to check the metadata fields so fast the page hasn't switched yet. We'd probably need to run it 100 times to get any real sense but here's 7 in a row:
=> Improve reliability of edit in place test

app/services/spotlight/exhibit_import_export_service.rb
```
app/services/spotlight/exhibit_import_export_service.rb:368:9: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a method call.
(page[:translated_pages]).each do |translated_page|
^^^^^^^^^^^^^^^^^^^^^^^^^
app/services/spotlight/exhibit_import_export_service.rb:376:9: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a method call.
(page[:translated_pages]).each do |translated_page|
```
=> Run Rubocop autocorrect

vendor/assets/stylesheets/sir-trevor/block-controls.scss
Uses whatever is set for `var(--bs-btn-hover-color)` instead.
Before:
After:
=> Let st-block-controls hover use the default color

blacklight-spotlight.gemspec
Bootstrap 5 only works with bootstrap_form 5 and above. Since we've dropped Bootstrap 4 we should set the gemspec appropriately.
=> Set gemspec to use compatible version of bootstrap_form gem

blacklight-spotlight.gemspec
No longer needed now that we've drawn a hard line between v4 and v5.
=> Remove sprockets specific dependencies

app/views/spotlight/catalog/admin.html.erb, spec/views/spotlight/catalog/admin.html.erb_spec.rb
The `search_header` partial is removed in Blacklight 9.
=> Render search header component directly

app/views/spotlight/sir_trevor/blocks/_heading_block.html.erb
Running the heading block text through the markdown renderer fixed the issues from https://github.com/projectblacklight/spotlight/issues/944 but is wrapping the inner text in a paragraph tag. This is flagging some a11y checks. See https://github.com/sul-dlss/exhibits/issues/2877 for more detail.
Using the markdown renderer this way results in only the h2 tag and heading text.
=> Remove p tag wrapper in heading block text

app/controllers/concerns/spotlight/controller.rb, app/controllers/spotlight/browse_controller.rb, app/controllers/spotlight/searches_controller.rb, app/models/sir_trevor_rails/blocks/displayable.rb, app/models/spotlight/lock.rb
Linter errors for reference:
```
app/controllers/spotlight/searches_controller.rb:38:61: F: Lint/Syntax: unexpected token kUNLESS_MOD
(Using Ruby 3.1 parser; configure using TargetRubyVersion parameter, under AllCops)
@search.assign_attributes(search_params.except(:title unless @search.new_record?))
^^^^^^
app/controllers/spotlight/searches_controller.rb:38:87: F: Lint/Syntax: unexpected token tRPAREN
(Using Ruby 3.1 parser; configure using TargetRubyVersion parameter, under AllCops)
@search.assign_attributes(search_params.except(:title unless @search.new_record?))
^
app/models/sir_trevor_rails/blocks/displayable.rb:23:27: F: Lint/Syntax: unexpected token kIF_MOD
(Using Ruby 3.1 parser; configure using TargetRubyVersion parameter, under AllCops)
Array(item.values if item.present?)
^^ …
```
=> Appease Rubocop

app/views/spotlight/about_pages/_contact.html.erb, app/views/spotlight/pages/_page.html.erb, app/views/spotlight/search_configurations/_facets.html.erb, app/views/spotlight/searches/_group.html.erb, app/views/spotlight/searches/_search.html.erb, app/views/spotlight/tags/_tag.html.erb, spec/features/javascript/feature_page_admin_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/2895
Similar to https://github.com/projectblacklight/spotlight/pull/3435, but that only added the initial weights to one of the sets of orderable (nestable) elements, we need to do them all.
=> Add initial weight to all nestables

lib/generators/spotlight/templates/.solr_wrapper.yml
We have it pinned in the project, we should pin it for the template installer as well. Otherwise it is confusing when solr_wrapper fails to start for new installs.
=> Pin Solr to 9.7 in the solr_wrapper template

.rubocop.yml, app/controllers/spotlight/catalog_controller.rb
`Style/SafeNavigation` can't parse `lib/generators/spotlight/assets/importmap_generator.rb`
`Naming/PredicateName` is now `Naming/PredicatePrefix`
=> Rubocop fixes

app/models/spotlight/page.rb, app/views/spotlight/translations/_page.html.erb, spec/features/exhibits/translation_editing_spec.rb, spec/models/spotlight/page_spec.rb
Part of #3478 
Fixes issue when a locale other than the default is set when viewing the exhibit dashboard translations editor. In the first column we always want the default language page title to display and for the link to go the page in the default language. Before this change it was displaying the page for the currently set locale and also linking to that page.
=> Always show the default title and link to the default page

app/components/spotlight/uneditable_non_default_language_component.html.erb, app/components/spotlight/uneditable_non_default_language_component.rb, app/views/spotlight/appearances/edit.html.erb, app/views/spotlight/exhibits/_form.html.erb, app/views/spotlight/metadata_configurations/edit.html.erb, app/views/spotlight/pages/_order_pages.html.erb, app/views/spotlight/search_configurations/edit.html.erb, app/views/spotlight/searches/index.html.erb, config/locales/spotlight.en.yml, spec/views/spotlight/about_pages/index.html.erb_spec.rb, spec/views/spotlight/exhibits/edit.html.erb_spec.rb, spec/views/spotlight/metadata_configurations/edit.html.erb_spec.rb, spec/views/spotlight/pages/index.html.erb_spec.rb, spec/views/spotlight/searches/index.html.erb_spec.rb
Fixes #3478 
More details in https://github.com/sul-dlss/exhibits/issues/2920
This change blocks editing of translatable fields/forms when a locale other than the default is selected. This prevents exhibit editors from unintentionally editing the default locale values and directs them to either switch locales or to use the translations editor:
=> Do not allow editing of translatable fields when a locale other than default is selected

app/components/spotlight/analytics/aggregation_component.rb, app/components/spotlight/analytics/dashboard_component.rb, app/components/spotlight/breadcrumbs_component.rb, app/components/spotlight/bulk_action_component.rb, app/components/spotlight/edit_view_links_component.rb, app/components/spotlight/header_navigation_link_component.rb, app/components/spotlight/save_search_component.rb, app/components/spotlight/select_image_component.rb, app/components/spotlight/skip_link_component.rb, app/components/spotlight/solr_document_legacy_embed_component.rb, app/components/spotlight/tag_list_form_component.rb, app/components/spotlight/tag_selector_component.rb, app/components/spotlight/title_component.rb, app/components/spotlight/translations/subheading_component.rb, app/components/spotlight/uneditable_non_default_language_component.rb, app/models/sir_trevor_rails/blocks/browse_block.rb, app/models/sir_trevor_rails/blocks/featured_pages_block.rb, app/models/spotlight/resource.rb, app/views/spotlight/catalog/edit.html.erb
Rubocop + Blacklight 8.12.0/view component 4 changes
=> Update for Blacklight 8.12.0 & View Component 4

.github/workflows/ruby.yml, spec/features/autocomplete_typeahead_spec.rb
Gets us past https://github.com/projectblacklight/spotlight/issues/3542 until we can address the incompatibility with Bundler 2.7.2
=> Trying different bundler version

spec/test_app_templates/lib/generators/test_app_generator.rb
fixes #3539
This also moves that yarn link up next to the package_json and before
all the gem stuff, which initially I did just to make it happen sooner
in my repeated runs but seems to slightly increase the thematic
arrangement of the code stanzas
referenced:
- https://github.com/cbeer/engine_cart/blob/c6896bab1e9191e2870db9d187158721dbc2c6eb/README.md#set-up-your-engine-to-use-engine_cart
- https://ruby-doc.org/3.0.7/stdlibs/bundler/Bundler/Thor/Actions.html#method-i-inside
Screenshot after this fix:
=> Run `yarn link` inside the spotlight directory, not the test app

spec/features/javascript/blocks/featured_pages_block_spec.rb
Now that the page widget permissions are fixed, we can use the exhibit creator role in the page widget specs. Fixes merge conflict from merging https://github.com/projectblacklight/spotlight/pull/3547 after https://github.com/projectblacklight/spotlight/pull/3550.
=> Use exhibit curator in pages widget feature specs

blacklight-spotlight.gemspec
version 2.2.0 of carrierwave is known not to work. Let's avoid it: https://github.com/carrierwaveuploader/carrierwave/issues/2554
=> Specify versions of carrierwave that work

config/initializers/devise_rails8_patch.rb
This fixes frequent / intermittent errors when running individual controller specs or controller specs as a whole in a local environment. example error:
```
main % bundle exec rspec --seed 54353 spec/controllers/spotlight/versions_controller_spec.rb
Randomized with seed 54353
Failures:
1) Spotlight::VersionsController when not authorized for the exhibit resource POST revert is not allowed
Failure/Error: sign_in user
RuntimeError:
Could not find a valid mapping for #<User id: 1, email: [FILTERED], created_at: "2025-09-16 16:44:45.748330000 +0000", updated_at: "2025-09-16 16:44:45.748330000 +0000", guest: false>
```
For more info see https://github.com/heartcombo/devise/pull/5728
advances #3538
=> patch devise mappings

app/models/spotlight/exhibit.rb, app/views/spotlight/exhibits/_exhibit_card.html.erb, spec/models/spotlight/exhibit_spec.rb, spec/views/spotlight/exhibits/_exhibit_card.html.erb_spec.rb
Fixes https://github.com/projectblacklight/spotlight/issues/3239
- Moves sanitization of description to view layer, per suggestion in [rails-html-sanitizer Readme](https://github.com/rails/rails-html-sanitizer?tab=readme-ov-file#a-note-on-html-entities). The description doesn't seem to be saved outside of typical ActiveRecord model updates, so this looks safe to do, but if anyone knows a reason why we need to sanitize this field before saving to the db, I can add this back.
- ~~Switches to default SafeListSanitizer with an empty tag list instead of FullSanitizer, since it seems like we mostly just want to strip html tags.~~
- We'll need to include a note in the release notes about updating any html entities in saved descriptions in folks' local spotlight instances.
=> Don't display special characters in description as html entities

app/helpers/spotlight/rendering_helper.rb, app/views/spotlight/sir_trevor/blocks/_text_block.html.erb, blacklight-spotlight.gemspec, lib/spotlight/engine.rb, spec/helpers/spotlight/rendering_helper_spec.rb
Advances #3499, adding automatic heading ids for section linking / table of contents
This ticket removes the gem `github-markup`, which served no purpose other than to [run a default version of the redcarpet markdown renderer](https://github.com/github/markup/blob/ebfff7059dcd84c8ec32df138392decfc6544fda/lib/github/markup/markdown.rb#L15). This update instead uses the `redcarpet` gem directly, including an extension to "add HTML anchors to each header in the output HTML, to allow linking to each section" (see [redcarpet readme](https://github.com/vmg/redcarpet) for details).
=> Remove Github Markup and add RedCarpet markdown renderer with automatic heading ids

CONTRIBUTING.md
For consideration; it will be convenient for everyone participating in the upcoming community sprint to have full repository access.
This is a diff from the process defined for [becoming a Blacklight committer](https://github.com/projectblacklight/blacklight/blob/main/CONTRIBUTING.md#becoming-a-committer), so should be called out in this contributing document, which otherwise references the Blacklight document.
=> Define sprint participation as a way to get repository access

app/services/spotlight/exhibit_import_export_service.rb, spec/services/spotlight/exhibit_import_export_service_spec.rb
This partially addresses #3199 by always importing sidecar and resource data values with string keys. This does not address problem where imported sidecars and resources are not correctly associated with each other.
=> Store imported sidecar and resource data with string keys

blacklight-spotlight.gemspec, spec/features/javascript/blocks/browse_group_categories_block_spec.rb, spec/features/javascript/blocks/featured_browse_categories_block_spec.rb, spec/features/javascript/blocks/featured_pages_block_spec.rb, spec/features/javascript/blocks/heading_block_spec.rb, spec/features/javascript/blocks/link_to_search_block_spec.rb, spec/features/javascript/blocks/rule_block_spec.rb, spec/features/javascript/blocks/search_result_block_spec.rb, spec/features/javascript/blocks/solr_documents_block_spec.rb, spec/features/javascript/blocks/solr_documents_carousel_block_spec.rb, spec/features/javascript/blocks/solr_documents_embed_block_spec.rb, spec/features/javascript/blocks/uploaded_items_block_spec.rb, spec/spec_helper.rb
Part of #3535
Adds the `axe-core-rspec` gem as a dev dependency. Axe core has good support for heading ordering rules, so this will start to give us some feedback as we make changes.
I've included these directly in the block specs, sometimes piggy-backing on an existing test, in an attempt to keep the number of new/mostly duplicated feature tests to a minimum. It looks like Blacklight moved away from the `be_accessible` helper and is now using `be_axe_clean` directly so I've done the same.
=> Add basic axe core testing for blocks

app/controllers/spotlight/browse_controller.rb, app/controllers/spotlight/bulk_actions_controller.rb, app/controllers/spotlight/catalog_controller.rb, app/controllers/spotlight/dashboards_controller.rb, app/controllers/spotlight/home_pages_controller.rb, app/controllers/spotlight/searches_controller.rb, app/views/spotlight/sir_trevor/blocks/_search_results_block.html.erb, spec/controllers/spotlight/browse_controller_spec.rb, spec/controllers/spotlight/catalog_controller_spec.rb, spec/controllers/spotlight/dashboards_controller_spec.rb, spec/controllers/spotlight/home_pages_controller_spec.rb, spec/helpers/spotlight/pages_helper_spec.rb
Addresses https://github.com/projectblacklight/spotlight/issues/3069.
Blacklight::SearchService#search_results returns only a Blacklight::Solr::Response in blacklight 8+, not `[response, document_list]`. We already stopped using document_list in spotlight, but this PR removes all assignments and updates mocked search result objects in specs.
=> Expect search_service.search_results to return only response

app/controllers/spotlight/browse_controller.rb, app/controllers/spotlight/catalog_controller.rb, app/controllers/spotlight/dashboards_controller.rb, app/helpers/spotlight/main_app_helpers.rb, app/views/spotlight/catalog/_document_admin_table.html.erb, app/views/spotlight/catalog/edit.html.erb, app/views/spotlight/sir_trevor/blocks/_embedded_document.html.erb, lib/spotlight/engine.rb, spec/controllers/spotlight/catalog_controller_spec.rb
Spotlight 5 does not support Blacklight 7 so we can remove conditionals that were added to maintain backwards compatibility.
=> Remove conditional checks for Blacklight 7 vs 8

.rubocop_todo.yml, app/models/spotlight/resources/iiif_manifest/metadata.rb, app/models/spotlight/resources/iiif_manifest_metadata.rb, app/models/spotlight/resources/iiif_manifest_v3.rb, app/models/spotlight/resources/iiif_service.rb, blacklight-spotlight.gemspec, lib/spotlight/engine.rb, spec/fixtures/iiif_responses.rb, spec/models/spotlight/resources/iiif_manifest_v3_spec.rb, spec/models/spotlight/resources/iiif_service_spec.rb, spec/support/stub_iiif_response.rb
Allow items to be added to exhibits via iiif v3 manifests.
This PR adds a sort of factory into Spotlight::Resources::IiifService so that it may return either a v2 or a v3 manifest object (via the iiif-presentation gem). A new manifest v3 class is split out and inherits from the previously-existing manifest class. The metadata class is configurable and both manifest classes use the same configuration. So rather than add a new metadata class for v3 I made it more flexible -- it already had notes about handling v3-type json-ld values. However, if we wanted to add an additional configuration for the metadata class, we could split that into 2 different classes.
closes #3482
screenshot of a successfully ingested item in my dev instance:
=> Support adding iiif v3 manifests to exhibits
