projectblacklight/spotlight

- app/assets/javascripts/spotlight/application.js
- app/assets/stylesheets/spotlight/_catalog.scss
- app/assets/stylesheets/spotlight/_spotlight.scss
- app/assets/stylesheets/spotlight/_upload.scss
- app/controllers/spotlight/resources/upload_controller.rb
- app/models/spotlight/resources/upload.rb
- app/uploaders/item_uploader.rb
- app/views/spotlight/catalog/_admin_header.html.erb
- app/views/spotlight/resources/upload/_single_item_form.html.erb
- app/views/spotlight/resources/upload/new.html.erb
- config/locales/spotlight.en.yml
- config/routes.rb
- spec/controllers/spotlight/resources/upload_controller_spec.rb
- spec/features/add_item_bookmarklet_spec.rb
- spec/features/upload_non_repository_item_spec.rb
- spec/models/spotlight/resources/upload_spec.rb
- spec/test_app_templates/catalog_controller.rb
- spec/views/spotlight/catalog/admin.html.erb_spec.rb
> Add a form to upload non-repository images.

- lib/tasks/spotlight_tasks.rake
Perhaps a short-term solution for #849
> Add rake task to promote a user to a application-wide admin

- app/forms/spotlight/appearance.rb
- spec/test_app_templates/catalog_controller.rb
> Fix Spotlight::Appearance handling of sort fields

- Gemfile
- app/models/spotlight/blacklight_configuration.rb
- spec/models/spotlight/blacklight_configuration_spec.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
- template.rb
> Touch exhibit

- app/models/spotlight/exhibit.rb
- app/serializers/spotlight/exhibit_export_serializer.rb
- spec/models/spotlight/exhibit_spec.rb
- spec/serializers/spotlight/exhibit_export_serializer_spec.rb
> Include the exhibit tags in the exhibit's serialization

- app/helpers/spotlight/title_helper.rb
- spec/helpers/spotlight/title_helper_spec.rb
> Strip tags from the HTML title.

- app/controllers/spotlight/appearances_controller.rb
- app/controllers/spotlight/attachments_controller.rb
- app/controllers/spotlight/blacklight_configurations_controller.rb
- app/controllers/spotlight/browse_controller.rb
- app/controllers/spotlight/catalog_controller.rb
- app/controllers/spotlight/concerns/application_controller.rb
- app/controllers/spotlight/contact_forms_controller.rb
- app/controllers/spotlight/custom_fields_controller.rb
- app/controllers/spotlight/dashboards_controller.rb
- app/controllers/spotlight/exhibits_controller.rb
- app/controllers/spotlight/pages_controller.rb
- app/controllers/spotlight/resources/upload_controller.rb
- app/controllers/spotlight/resources_controller.rb
- app/models/spotlight/ability.rb
- app/views/shared/_exhibit_masthead.html.erb
- app/views/spotlight/exhibits/edit.html.erb
- config/locales/spotlight.en.yml
- db/migrate/20150116161616_add_published_to_exhibit.rb
- spec/controllers/spotlight/home_pages_controller_spec.rb
> Add admin-togglable published flag for controlling exhibit access

- app/controllers/spotlight/dashboards_controller.rb
- app/models/concerns/spotlight/solr_document.rb
- app/models/concerns/spotlight/solr_document/atomic_updates.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/resource.rb
- app/models/spotlight/resources/csv.rb
- app/models/spotlight/resources/upload.rb
- app/models/spotlight/search.rb
- lib/spotlight/catalog.rb
- lib/spotlight/catalog/access_controls_enforcement.rb
- lib/spotlight/engine.rb
- lib/tasks/spotlight_tasks.rake
- spec/lib/spotlight/catalog/access_controls_enforcement_spec.rb
- spec/models/solr_document_spec.rb
- spec/models/spotlight/exhibit_spec.rb
- spec/models/spotlight/resource_spec.rb
- spec/models/spotlight/resources/csv_spec.rb
- spec/models/spotlight/resources/open_graph_spec.rb
- spec/models/spotlight/resources/upload_spec.rb
- spec/models/spotlight/solr_document_uploaded_resource_spec.rb
> Improve exhibit resource index machinery

- app/controllers/spotlight/appearances_controller.rb
- app/controllers/spotlight/exhibits_controller.rb
- app/models/spotlight/ability.rb
- app/models/spotlight/exhibit.rb
- app/views/spotlight/about_pages/_contacts_form.html.erb
- app/views/spotlight/about_pages/index.html.erb
- app/views/spotlight/catalog/_admin_header.html.erb
- app/views/spotlight/catalog/_edit_default.html.erb
- app/views/spotlight/exhibits/import.html.erb
- app/views/spotlight/shared/_admin_sidebar.html.erb
- app/views/spotlight/shared/_curation_sidebar.html.erb
- config/locales/spotlight.en.yml
- spec/views/spotlight/about_pages/index.html.erb_spec.rb
- spec/views/spotlight/catalog/_edit_default.html.erb_spec.rb
- spec/views/spotlight/catalog/admin.html.erb_spec.rb
> Use and check fine-grained permissions for admin and curator actions

- app/controllers/spotlight/home_pages_controller.rb
- app/models/spotlight/home_page.rb
- app/views/spotlight/home_pages/_page_options.html.erb
- spec/controllers/spotlight/home_pages_controller_spec.rb
- spec/features/home_page_spec.rb
- spec/models/spotlight/home_page_spec.rb
> Add display sidebar checkbox to home pages

- app/models/concerns/spotlight/solr_document.rb
- app/models/spotlight/solr_document_sidecar.rb
- app/serializers/spotlight/exhibit_export_serializer.rb
- blacklight-spotlight.gemspec
- db/migrate/20150217111511_add_polymorphic_document_to_sidecars.rb
- lib/generators/spotlight/install_generator.rb
- spec/models/solr_document_spec.rb
- spec/models/spotlight/resources/csv_spec.rb
- spec/models/spotlight/solr_document_sidecar_spec.rb
- spec/serializers/spotlight/exhibit_export_serializer_spec.rb
things I stumbled on trying to get spotlight running under europeana::repository
> Misc fixes

- app/controllers/spotlight/exhibits_controller.rb
- app/serializers/spotlight/exhibit_export_serializer.rb
- app/uploaders/spotlight/avatar_uploader.rb
- spec/factories/contacts.rb
- spec/factories/resources.rb
- spec/serializers/spotlight/exhibit_export_serializer_spec.rb
> Embed uploaded assets in the exhibit export

- app/views/shared/_analytics.html.erb
- app/views/shared/_footer.html.erb
- spec/views/shared/_analytics.html.erb_spec.rb
- spec/views/shared/_footer.html.erb_spec.rb
> Ga analytics

- app/models/spotlight/page.rb
- app/serializers/spotlight/page_representer.rb
- app/views/spotlight/sir_trevor/blocks/_heading_block.html.erb
- spec/models/spotlight/page_spec.rb
> Sir Trevor fixes

- app/controllers/spotlight/resources_controller.rb
- app/jobs/spotlight/reindex_job.rb
- app/models/spotlight/ability.rb
- app/models/spotlight/exhibit.rb
- app/views/spotlight/catalog/_admin_header.html.erb
- config/locales/spotlight.en.yml
- config/routes.rb
- lib/tasks/spotlight_tasks.rake
- spec/controllers/spotlight/resources_controller_spec.rb
- spec/factories/resources.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/models/spotlight/exhibit_spec.rb
- spec/views/spotlight/catalog/admin.html.erb_spec.rb
Fixes #887 
Fixes #489 
Fixes #488
> Add Spotlight::ReindexJob job and add a button to the curator's item view to enqueue the job

- app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
> Add calculated value for tablet image size in browse categories widget

- app/assets/javascripts/spotlight/application.js
- app/assets/javascripts/spotlight/jcrop.js
- app/views/spotlight/appearances/edit.html.erb
> Use Jcrop fork to fix boxWidth + minSize/maxSize issues.

- app/assets/javascripts/spotlight/blocks/item_grid_block.js
- app/assets/stylesheets/spotlight/_pages.scss
- app/models/sir_trevor_rails/blocks/item_grid_block.rb
- app/views/spotlight/sir_trevor/blocks/_item_grid_block.html.erb
- spec/features/javascript/item_grid_block_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_item_grid_block.html.erb_spec.rb
> Item grid block

- app/assets/stylesheets/spotlight/_browse.scss
- app/assets/stylesheets/spotlight/_header.scss
- app/assets/stylesheets/spotlight/_variables.scss
- app/controllers/spotlight/searches_controller.rb
- app/models/spotlight/exhibit.rb
- app/views/spotlight/browse/_search.html.erb
- app/views/spotlight/browse/index.html.erb
- app/views/spotlight/searches/_search.html.erb
- app/views/spotlight/searches/edit.html.erb
- spec/controllers/spotlight/searches_controller_spec.rb
- spec/views/spotlight/browse/_search.html.erb_spec.rb
- spec/views/spotlight/searches/_search.html.erb_spec.rb
- spec/views/spotlight/searches/edit.html.erb_spec.rb
> Update browse landing page.

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
- app/views/spotlight/pages/_form.html.erb
- config/locales/spotlight.en.yml
> Move page#edit content and options into bootstrap tabs

- app/assets/stylesheets/spotlight/_browse.scss
- app/views/spotlight/browse/show.html.erb
- app/views/spotlight/searches/_search.html.erb
- spec/views/spotlight/browse/show.html.erb_spec.rb
Begins work on #801 (this may close it out as the outstanding issues like the title being configurable will be resolved in other tickets)
> Update browse detail page.

- app/assets/stylesheets/spotlight/_curation.scss
- app/controllers/spotlight/appearances_controller.rb
- app/models/spotlight/main_navigation.rb
- app/views/shared/_exhibit_navbar.html.erb
- app/views/spotlight/appearances/edit.html.erb
- config/locales/spotlight.en.yml
- db/migrate/20150306202300_add_display_to_spotlight_main_navigations.rb
- spec/features/main_navigation_spec.rb
- spec/views/shared/_exhibit_navbar.html.erb_spec.rb
> Allow main navigation menu items to be toggleable.

- app/assets/javascripts/spotlight/croppable.js
- app/helpers/spotlight/jcrop_helper.rb
> Allow for initial Jcrop setSelect option to be set.

- app/controllers/spotlight/searches_controller.rb
- app/views/spotlight/appearances/edit.html.erb
- app/views/spotlight/searches/_form.html.erb
- spec/controllers/spotlight/searches_controller_spec.rb
> Fix item autocomplete on search and appearance pages

- app/assets/javascripts/spotlight/blocks/solr_documents_embed_block.js
- app/controllers/spotlight/pages_controller.rb
- app/models/sir_trevor_rails/blocks/solr_documents_block.rb
- app/models/sir_trevor_rails/blocks/solr_documents_embed_block.rb
- app/models/spotlight/blacklight_configuration.rb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb
- spec/models/sir_trevor_rails/blocks/solr_documents_block_spec.rb
- spec/models/spotlight/blacklight_configuration_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb_spec.rb
Now built as a generic way to invoke the blacklight rendering pipeline.
> Add sir-trevor document embed widget

- app/assets/stylesheets/spotlight/_pages.scss
- app/models/sir_trevor_rails/blocks/browse_block.rb
- app/models/sir_trevor_rails/blocks/featured_pages_block.rb
- app/models/sir_trevor_rails/blocks/oembed_block.rb
- app/models/sir_trevor_rails/blocks/solr_documents_block.rb
- app/models/sir_trevor_rails/blocks/textable.rb
- app/views/spotlight/sir_trevor/blocks/_oembed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb
- spec/models/spotlight/sir_trevor_blocks/textable_spec.rb
Also abstracting text behaviors into a SirTrevorRails::Blocks::Textable mixin.
Closes #782
> Fix spacing on embed + text widget.

- app/assets/javascripts/spotlight/block_mixins/autocompleteable.js
- app/assets/javascripts/spotlight/block_mixins/previewable.js
- app/assets/javascripts/spotlight/block_mixins/textable.js
- app/assets/javascripts/spotlight/blocks/browse_block.js
- app/assets/javascripts/spotlight/blocks/oembed_block.js
- app/assets/javascripts/spotlight/blocks/pages_block.js
- app/assets/javascripts/spotlight/blocks/resources_block.js
- app/assets/javascripts/spotlight/blocks/rule_block.js
- app/assets/javascripts/spotlight/blocks/search_result_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_carousel_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_embed_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_features_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_grid_block.js
- app/assets/javascripts/spotlight/sir-trevor/grouped_block_controls.js
- app/assets/javascripts/spotlight/sir-trevor/locales.js
I'm going to say, fixes #1021. There's a handful of random other strings (form observer, multiimage selector) outside of ST that we should figure out to deal with, but this was low-hanging fruit.
> Use sir-trevor's i18n framework for translations of blocks

- Rakefile
- app/controllers/spotlight/custom_fields_controller.rb
- app/helpers/spotlight/application_helper.rb
- app/helpers/spotlight/pages_helper.rb
- app/models/spotlight/blacklight_configuration.rb
- app/models/spotlight/custom_field.rb
- app/views/spotlight/blacklight_configurations/_metadata_field.html.erb
- app/views/spotlight/blacklight_configurations/edit_facet_fields.html.erb
- app/views/spotlight/blacklight_configurations/edit_metadata_fields.html.erb
- app/views/spotlight/custom_fields/_form.html.erb
- app/views/spotlight/pages/_form.html.erb
- config/locales/spotlight.en.yml
- db/migrate/20150313175432_add_field_type_to_custom_fields.rb
- spec/features/exhibits/custom_metadata_fields_spec.rb
- spec/helpers/spotlight/application_helper_spec.rb
- spec/models/spotlight/blacklight_configuration_spec.rb
- spec/models/spotlight/custom_field_spec.rb
- spec/views/spotlight/blacklight_configuration/_metadata_field.html.erb_spec.rb
- spec/views/spotlight/blacklight_configuration/edit_metadata_fields.html.erb_spec.rb
Fixed a couple bugs along the way.. this all needs tests before it should be merged.
Fixes #403
> Controlled vocabulary fields

- app/assets/stylesheets/spotlight/_blacklight_configuration.scss
- app/assets/stylesheets/spotlight/_catalog.scss
- app/controllers/spotlight/catalog_controller.rb
- app/controllers/spotlight/dashboards_controller.rb
- app/views/spotlight/catalog/_admin_index_header_default.html.erb
- app/views/spotlight/catalog/_index_compact_default.html.erb
- spec/controllers/spotlight/catalog_controller_spec.rb
> Catalog admin styling

- app/models/spotlight/home_page.rb
- app/models/spotlight/page.rb
- app/views/spotlight/home_pages/_empty.html.erb
- app/views/spotlight/pages/show.html.erb
- spec/models/spotlight/home_page_spec.rb
- spec/models/spotlight/page_spec.rb
- spec/views/spotlight/pages/show.html.erb_spec.rb
> Render placeholder content when the page is empty

- app/assets/javascripts/spotlight/blocks/iframe_block.js
- app/assets/javascripts/spotlight/sir-trevor/locales.js
- app/views/spotlight/sir_trevor/blocks/_iframe_block.html.erb
- spec/views/spotlight/sir_trevor/blocks/_iframe_block.html.erb_spec.rb
> Add iframe widget for sir-trevor

- Gemfile
- app/assets/javascripts/spotlight/blocks/solr_documents_embed_block.js
- lib/generators/spotlight/install_generator.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
Fixes #1078 
Requires releases of https://github.com/IIIF/openseadragon-rails/pull/11 and https://github.com/projectblacklight/blacklight-gallery/pull/26
> 	Initialize the openseadragon viewer after previewing the embed block

- app/views/spotlight/about_pages/_empty.html.erb
- app/views/spotlight/feature_pages/_empty.html.erb
- spec/views/spotlight/about_pages/_empty.html.erb_spec.rb
- spec/views/spotlight/feature_pages/_empty.html.erb_spec.rb
> Add new about and feature page default content

- app/assets/stylesheets/spotlight/_pages.scss
- app/views/spotlight/about_pages/_empty.html.erb
- app/views/spotlight/feature_pages/_empty.html.erb
- app/views/spotlight/home_pages/_empty.html.erb
- spec/views/spotlight/about_pages/_empty.html.erb_spec.rb
- spec/views/spotlight/feature_pages/_empty.html.erb_spec.rb
> Style the default text block to be more distinctive

- app/models/concerns/spotlight/solr_document/finder.rb
> Rewrite Spotlight::SolrDocument::Finder to use the blacklight repository pattern

- app/views/spotlight/pages/_form.html.erb
Workaround for https://github.com/madebymany/sir-trevor-rails/issues/38
> Fix sir-trevor text area handling under Rails 4.2.1

- app/models/spotlight/blacklight_configuration.rb
- lib/generators/spotlight/templates/catalog_controller.rb
- spec/models/spotlight/blacklight_configuration_spec.rb
> Default catalog controller

- app/forms/spotlight/appearance.rb
> Also set the exhibit's masthead/thumbnail if the image is just being recropped

- app/assets/stylesheets/spotlight/_pages.scss
- app/views/spotlight/sir_trevor/blocks/_oembed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb
- spec/features/javascript/blocks/solr_documents_block_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb_spec.rb
> Solr doc + text fixes

- app/models/concerns/spotlight/solr_document/spotlight_images.rb
- app/models/spotlight/search.rb
- spec/models/spotlight/search_spec.rb
- spec/models/spotlight/solr_document/spotlight_images_spec.rb
@ebenenglish, @ggeisler I'm optimistic this will fix the problems you both reported by email with items without thumbnails.
> Missing derivatives

- app/assets/stylesheets/spotlight/_report_a_problem.scss
- app/views/spotlight/shared/_report_a_problem.html.erb
> Widen form fields on Report a Problem form

- app/assets/javascripts/spotlight/blocks/resources_block.js
- app/models/sir_trevor_rails/blocks/solr_documents_block.rb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb_spec.rb
> Refactor sir-trevor resource blocks to support repeated documents

- app/assets/stylesheets/spotlight/_header.scss
Fixes #1156 
Increase z-index of main menu so dropdown menu is visible over page content.
> Fix overlapping content

- app/controllers/spotlight/searches_controller.rb
- app/models/spotlight/ability.rb
- app/models/spotlight/search.rb
- app/views/spotlight/searches/_search.html.erb
- db/migrate/20150713160101_change_spotlight_searches_to_published.rb
- spec/controllers/spotlight/searches_controller_spec.rb
- spec/factories/searches.rb
- spec/features/javascript/blocks/featured_browse_categories_block_spec.rb
- spec/features/javascript/blocks/search_result_block_spec.rb
- spec/features/javascript/search_context_spec.rb
- spec/features/main_navigation_spec.rb
- spec/helpers/spotlight/pages_helper_spec.rb
- spec/models/spotlight/search_spec.rb
- spec/serializers/spotlight/exhibit_export_serializer_spec.rb
> Rename Searches#on_landing_page to #published

- README.md
This is not ruby < 2.2 compatible.
https://github.com/sul-dlss/spotlight/blob/e57ad05fca0fd90c5a97e90d438356fa680ea89b/app/helpers/spotlight/application_helper.rb#L109-L110
> Update README file to indicate that we require ruby 2.2 or higher.

- Rakefile
> Make rubocop fail the build when violations are detected

- .gitignore
- README.md
@cbeer @peetucket 
I may have gone a bit overboard ...
> README updates for development

- lib/spotlight/version.rb
https://github.com/sul-dlss/spotlight/compare/v0.4.1...6bb7a4f
> Bump to 0.5.0

- .gitignore
- .rubocop.yml
- .travis.yml
- Gemfile
- README.md
- app/controllers/spotlight/pages_controller.rb
- app/controllers/spotlight/resources/upload_controller.rb
- app/controllers/spotlight/searches_controller.rb
- app/models/spotlight/search.rb
- blacklight-spotlight.gemspec
- lib/spotlight.rb
- lib/spotlight/engine.rb
- spec/controllers/spotlight/resources/upload_controller_spec.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
- spec/test_app_templates/spotlight_test.rake
- spec/uploaders/spotlight/item_uploader_spec.rb
- template.rb
@cbeer @peetucket 
(I got here by mistake, but I did it anyway)
> upgrade to engine_cart 0.8.0

- lib/spotlight/version.rb
@cbeer 
Had to do this as PR b/c:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected
To git@github.com:sul-dlss/spotlight.git
! [remote rejected] master -> master (protected branch hook declined)
```
> bump to version 0.6.0:  blacklight 5.16

- app/assets/javascripts/spotlight/blocks/resources_block.js
- app/models/sir_trevor_rails/blocks/browse_block.rb
- app/models/sir_trevor_rails/blocks/featured_pages_block.rb
- spec/features/javascript/blocks/featured_pages_block_spec.rb
> Allow Browse Category and Feature Page widgets to respect sort order

- app/assets/javascripts/spotlight/blocks/uploaded_items_block.js
- app/assets/javascripts/spotlight/sir-trevor/locales.js
- app/assets/stylesheets/spotlight/_sir-trevor_overrides.scss
- app/assets/stylesheets/spotlight/_spotlight.scss
- app/assets/stylesheets/spotlight/_uploaded_items_block.scss
- app/models/sir_trevor_rails/blocks/uploaded_items_block.rb
- app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
- spec/features/javascript/blocks/uploaded_items_block_spec.rb
> Add Uploaded Item Row Block.

- app/models/spotlight/contact.rb
- spec/models/spotlight/contact_spec.rb
- spec/serializers/spotlight/exhibit_export_serializer_spec.rb
> Ensure Spotlight::Contact#contact_info attributes are symbols

- spec/features/import_exhibit_spec.rb
Trying this out to see if travis will pass w/o this test as pending.
> Removing pending from spec that is now passing.

- lib/spotlight/engine.rb
> Advertise the spotlight factories to downstream applications

- app/views/spotlight/sir_trevor/blocks/_browse_block.html.erb
- spec/views/spotlight/sir_trevor/blocks/_browse_block.html.erb_spec.rb
> Browse category widget should link to public browse category

- app/assets/stylesheets/spotlight/_exhibits_index.scss
> Make exhibit cards more responsive at small and medium breakpoints

- app/assets/stylesheets/spotlight/_collapse_toggle.scss
- app/assets/stylesheets/spotlight/_curation.scss
- app/assets/stylesheets/spotlight/_spotlight.scss
- app/controllers/spotlight/search_configurations_controller.rb
- app/views/spotlight/search_configurations/_facets.html.erb
- config/locales/spotlight.en.yml
- spec/features/javascript/search_config_admin_spec.rb
- spec/models/spotlight/blacklight_configuration_spec.rb
> Allow the curator to select the default sort order for a facet

- app/models/spotlight/exhibit.rb
- db/migrate/20151208085432_add_weight_to_exhibits.rb
> Add default ordering to exhibits

- db/migrate/20151110082345_add_metadata_to_spotlight_resource.rb
> postgres does not support blob field type

- app/models/spotlight/exhibit.rb
- lib/spotlight/engine.rb
> Make the exhibit filter configurable

- app/helpers/spotlight/application_helper.rb
- app/models/concerns/spotlight/solr_document.rb
- app/models/spotlight/blacklight_configuration.rb
- app/models/spotlight/custom_field.rb
- app/models/spotlight/resource.rb
- app/models/spotlight/solr_document_sidecar.rb
- lib/spotlight/catalog.rb
- lib/spotlight/catalog/access_controls_enforcement.rb
- spec/controllers/spotlight/catalog_controller_spec.rb
- spec/helpers/spotlight/application_helper_spec.rb
- spec/helpers/spotlight/pages_helper_spec.rb
- spec/models/solr_document_spec.rb
- spec/models/spotlight/custom_field_spec.rb
- spec/models/spotlight/resources/open_graph_spec.rb
- spec/models/spotlight/sitemap_spec.rb
- spec/models/spotlight/solr_document/atomic_updates_spec.rb
- spec/models/spotlight/solr_document/uploaded_resource_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb_spec.rb
> Use the host application's configured document model to enable overriding

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
- app/views/shared/_site_sidebar.html.erb
- app/views/spotlight/about_pages/_sidebar.html.erb
- app/views/spotlight/shared/_configuration_sidebar.html.erb
- app/views/spotlight/shared/_curation_sidebar.html.erb
> Use bootstrap nav styling for the sidenav

- app/controllers/spotlight/roles_controller.rb
- app/models/concerns/spotlight/user.rb
- app/models/spotlight/ability.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/role.rb
- app/models/spotlight/site.rb
- app/views/devise/mailer/invitation_instructions.html.erb
- app/views/spotlight/home_pages/_empty.html.erb
- app/views/spotlight/shared/_configuration_sidebar.html.erb
- db/migrate/20151215141516_change_roles_to_support_polymorphic_associations.rb
- spec/controllers/spotlight/contacts_controller_spec.rb
- spec/controllers/spotlight/home_pages_controller_spec.rb
- spec/controllers/spotlight/roles_controller_spec.rb
- spec/controllers/spotlight/versions_controller_spec.rb
- spec/factories/roles.rb
- spec/factories/users.rb
- spec/features/add_contacts_spec.rb
- spec/features/edit_contact_spec.rb
- spec/models/spotlight/ability_spec.rb
- spec/views/spotlight/roles/index.html.erb_spec.rb
This is a prerequisite for #849
> Update roles to use polymorphic associations with resources

- app/views/shared/_site_sidebar.html.erb
- config/locales/spotlight.en.yml
> Add documentation link to the site sidebar

- app/models/spotlight/site.rb
- spec/features/site_masthead_spec.rb
> Spotlight::Site should update the masthead instead of replacing it

- app/controllers/spotlight/exhibits_controller.rb
- app/controllers/spotlight/solr_controller.rb
- app/models/concerns/spotlight/solr_document/atomic_updates.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/resource.rb
- app/views/spotlight/exhibits/_form.html.erb
- app/views/spotlight/exhibits/_new_exhibit_form.html.erb
- app/views/spotlight/exhibits/index.html.erb
- config/locales/spotlight.en.yml
- lib/spotlight/engine.rb
- lib/tasks/spotlight_tasks.rake
- spec/controllers/spotlight/exhibits_controller_spec.rb
- spec/controllers/spotlight/solr_controller_spec.rb
- spec/models/spotlight/resource_spec.rb
- spec/models/spotlight/solr_document/atomic_updates_spec.rb
Fixes #1394 
Fixes #1393 
Fixes #1391 
Fixes #1385
> Merge curationexperts pull requests

- app/controllers/concerns/spotlight/catalog/access_controls_enforcement.rb
- app/controllers/spotlight/filters_controller.rb
- app/models/concerns/spotlight/exhibit_defaults.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/filter.rb
- app/views/spotlight/exhibits/edit.html.erb
- app/views/spotlight/filters/_form.html.erb
- config/locales/spotlight.en.yml
- config/routes.rb
- db/migrate/20151217211019_create_spotlight_exhibit_filters.rb
- lib/spotlight/engine.rb
- spec/controllers/spotlight/filters_controller_spec.rb
- spec/lib/spotlight/catalog/access_controls_enforcement_spec.rb
- spec/models/spotlight/exhibit_spec.rb
- spec/models/spotlight/filter_spec.rb
- spec/views/spotlight/exhibits/edit.html.erb_spec.rb
> Allow solr filters to be configurable on a per-exhibit basis

- app/controllers/spotlight/exhibits_controller.rb
- app/models/spotlight/exhibit.rb
- app/views/spotlight/exhibits/_tags.html.erb
- app/views/spotlight/exhibits/index.html.erb
- config/locales/spotlight.en.yml
- spec/features/exhibits_index_spec.rb
- spec/views/spotlight/exhibits/index.html.erb_spec.rb
> filtering exhibits by tag

- app/views/shared/_site_sidebar.html.erb
This became a problem with a locally overridden exhibits_controller.
> Namespace new_exhibit_path helper

- config/locales/spotlight.en.yml
> Reword default invitation emails to remove all links besides the accept invitation action

- .solr_wrapper
- .travis.yml
- Gemfile
- Rakefile
- app/assets/javascripts/spotlight/spotlight.js
- app/controllers/concerns/spotlight/base.rb
- app/helpers/spotlight/main_app_helpers.rb
- app/views/spotlight/pages/_order_pages.html.erb
- blacklight-spotlight.gemspec
- config/jetty.yml
- solr_conf/conf/schema.xml
- solr_conf/conf/solrconfig.xml
- spec/fixtures/sample_solr_documents.yml
> [WIP] Solr6

- app/views/shared/_site_sidebar.html.erb
- app/views/spotlight/about_pages/_empty.html.erb
- app/views/spotlight/dashboards/analytics.html.erb
- app/views/spotlight/exhibits/_missing_exhibits.html.erb
- app/views/spotlight/feature_pages/_empty.html.erb
- app/views/spotlight/home_pages/_empty.html.erb
- app/views/spotlight/resources/_missing_external_resources_partials.html.erb
- blacklight-spotlight.gemspec
- template.rb
> Replace sul-dlss/spotlight references to projectblacklight/spotlight

- app/controllers/spotlight/contact_forms_controller.rb
- app/mailers/spotlight/contact_mailer.rb
- app/models/spotlight/contact_form.rb
- app/views/spotlight/contact_forms/show.html.erb
- app/views/spotlight/contact_mailer/report_problem.html.erb
- blacklight-spotlight.gemspec
- spec/controllers/spotlight/contact_forms_controller_spec.rb
> Replace mail_form with ordinary ActionMailer class

- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
- spec/views/spotlight/roles/index.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb_spec.rb
> Remove deprecations

- app/assets/stylesheets/spotlight/_multi_up_item_grid.scss
- app/assets/stylesheets/spotlight/_pages.scss
> Fix safari flexbox display bugs for multi-up grids; fixes #1444

- app/services/spotlight/carrierwave_file_resolver.rb
- blacklight-spotlight.gemspec
- lib/generators/spotlight/install_generator.rb
- lib/generators/spotlight/templates/config/initializers/riiif.rb
- spec/services/spotlight/carrierwave_file_resolver_spec.rb
> Install Riiif as a way to return carrierwave downloads

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
- app/controllers/spotlight/searches_controller.rb
- app/helpers/spotlight/browse_helper.rb
- app/helpers/spotlight/searches_helper.rb
- app/models/spotlight/blacklight_configuration.rb
- app/views/spotlight/browse/show.html.erb
- app/views/spotlight/searches/_form.html.erb
- config/locales/spotlight.en.yml
- db/migrate/20160711121314_add_default_view_to_spotlight_searches.rb
- spec/features/browse_category_admin_spec.rb
- spec/features/browse_category_spec.rb
- spec/models/spotlight/blacklight_configuration_spec.rb
> Allow the curator to select the default view for a browse category

- app/models/spotlight/analytics/ga.rb
- app/views/spotlight/dashboards/analytics.html.erb
- blacklight-spotlight.gemspec
Using new approach from: https://github.com/tpitale/legato/wiki/OAuth2-and-Google#application-code
> Update to use signet instead of google-api-client; fixes #1423

- app/helpers/spotlight/title_helper.rb
- spec/views/spotlight/pages/show.html.erb_spec.rb
Refs sul-dlss/exhibits#218
Fixes #1501
> Mark @page_title as html_safe. Fixes #1501

- app/controllers/spotlight/concerns/user_invitable.rb
- app/controllers/spotlight/roles_controller.rb
- config/locales/spotlight.en.yml
- spec/controllers/spotlight/admin_users_controller_spec.rb
- spec/controllers/spotlight/roles_controller_spec.rb
> Use i18n pluralization for role error message

- app/assets/javascripts/spotlight/application.js
- app/assets/javascripts/spotlight/spotlight.js
- app/assets/stylesheets/spotlight/_footer.scss
- app/views/shared/_footer.html.erb
- blacklight-spotlight.gemspec
- lib/generators/spotlight/install_generator.rb
- lib/generators/spotlight/templates/config/initializers/social_share_button.rb
- lib/generators/spotlight/templates/spotlight.scss
- lib/spotlight/engine.rb
- spec/test_app_templates/Gemfile.extra
- spec/views/shared/_footer.html.erb_spec.rb
> Remove social-share-button dependency

- app/models/spotlight/reindex_progress.rb
- app/models/spotlight/resource.rb
- spec/models/spotlight/reindex_progress_spec.rb
- spec/models/spotlight/resource_spec.rb
Fixes https://app.honeybadger.io/projects/49092/faults/30612323
> Gracefully handle missing resource indexing data

- app/controllers/spotlight/catalog_controller.rb
- app/helpers/spotlight/application_helper.rb
- app/helpers/spotlight/meta_helper.rb
- app/models/spotlight/feature_page.rb
- app/models/spotlight/page.rb
- app/views/spotlight/browse/_tophat.html.erb
- app/views/spotlight/browse/show.html.erb
- app/views/spotlight/catalog/_tophat_default.html.erb
- app/views/spotlight/home_pages/_tophat.html.erb
- app/views/spotlight/pages/_tophat.html.erb
- spec/features/browse_category_spec.rb
- spec/features/catalog_spec.rb
- spec/features/feature_page_spec.rb
- spec/features/home_page_spec.rb
- spec/helpers/spotlight/application_helper_spec.rb
- spec/helpers/spotlight/meta_helper_spec.rb
- spec/views/spotlight/browse/show.html.erb_spec.rb
- spec/views/spotlight/pages/show.html.erb_spec.rb
> Add twitter card and opengraph content for pages, browse categories, and search results

- app/assets/stylesheets/spotlight/typeahead.css
Fixes https://github.com/sul-dlss/exhibits/issues/329
> Override typeahead z-index with a big enough value

- app/controllers/spotlight/browse_controller.rb
- app/helpers/spotlight/pages_helper.rb
- app/models/spotlight/search.rb
- spec/models/spotlight/search_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/331
> Preserve user pagination parameters in browse category searches

- app/controllers/spotlight/browse_controller.rb
- spec/controllers/spotlight/browse_controller_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/341
> Add json response to browse#show to support dynamic views

- app/helpers/spotlight/pages_helper.rb
- spec/helpers/spotlight/pages_helper_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/342
> Handle nil input to sir_trevor_markdown helper

- app/assets/javascripts/spotlight/blocks/browse_block.js
- app/assets/javascripts/spotlight/blocks/pages_block.js
- app/assets/stylesheets/spotlight/_sir-trevor_overrides.scss
> Address a couple minor issues w/ the previous block updates

- app/controllers/spotlight/resources/csv_upload_controller.rb
- config/locales/spotlight.en.yml
- spec/controllers/spotlight/resources/csv_upload_controller_spec.rb
- spec/fixtures/csv-upload-fixture.csv
> Convert CSV uploads to UTF-8 encoded IO objects before parsing

- app/views/spotlight/sir_trevor/blocks/_list_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_quote_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_text_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_tweet_block.html.erb
- spec/features/javascript/home_page_edit_spec.rb
Fixes #1464  and fixes #1618 
Some of our view customizations for Sir Trevor are out of date. This PR brings them up to date with what Sir Trevor Rails uses.
(now also fixes #1604)
> Update Sir Trevor customized blocks

- app/views/spotlight/catalog/_edit_default.html.erb
> Improve performance for catalog#edit page with lots of custom fields

- app/assets/javascripts/spotlight/search_typeahead.js
- app/views/spotlight/featured_images/_form.html.erb
- config/locales/spotlight.en.yml
- spec/features/autocomplete_typeahead_spec.rb
- spec/support/features/test_features_helpers.rb
Closes #1668 
I discussed the different positioning w/ @ggeisler and he gave the 🆗.
> Add an alert message when a non-iiif item is autocompleted for cropping.

- app/controllers/spotlight/catalog_controller.rb
- app/presenters/spotlight/iiif_manifest_presenter.rb
- app/services/spotlight/upload_solr_document_builder.rb
- blacklight-spotlight.gemspec
- config/routes.rb
- lib/spotlight/engine.rb
- spec/controllers/spotlight/catalog_controller_spec.rb
- spec/models/spotlight/resources/upload_spec.rb
- spec/presenters/spotlight/iiif_manifest_presenter_spec.rb
- spec/routing/spotlight/exhibit_catalog_spec.rb
> IIIF manifests for documents

- app/views/spotlight/pages/edit.html.erb
Fixes left + right padding to align objects on the page.
> Wrap edit page in a col-md-12

- app/models/spotlight/analytics/ga.rb
- app/views/_user_util_links.html.erb
- config/locales/spotlight.en.yml
- spec/features/create_exhibit_spec.rb
- spec/features/home_page_spec.rb
- spec/features/javascript/feature_page_admin_spec.rb
- spec/features/javascript/search_config_admin_spec.rb
- spec/views/_user_util_links.html.erb_spec.rb
> Add site-wide administration links to the actions dropdown

- blacklight-spotlight.gemspec
- lib/generators/spotlight/install_generator.rb
> RIIIF is now a runtime dependency

- app/assets/javascripts/spotlight/crop.es6
> Clamp crop box region to the bounds of the image

- app/assets/javascripts/spotlight/blocks/solr_documents_base_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_carousel_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_embed_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_features_block.js
- app/assets/javascripts/spotlight/blocks/solr_documents_grid_block.js
- app/assets/javascripts/spotlight/sir-trevor/locales.js
- app/assets/javascripts/spotlight/zpr_links.js.erb
- app/assets/stylesheets/spotlight/_pages.scss
- app/models/sir_trevor_rails/blocks/solr_documents_block.rb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- spec/features/javascript/blocks/solr_documents_block_spec.rb
Admin UI:
----
Page UI:
---
Modal ZPR viewer:
> Add ZPR viewer link option for  solr documents block; fixes #1704

- app/controllers/spotlight/searches_controller.rb
- app/views/catalog/_save_search.html.erb
- config/locales/spotlight.en.yml
- spec/features/browse_category_admin_spec.rb
> Allow browse categories to be updated

- app/models/spotlight/resources/iiif_manifest.rb
- app/services/spotlight/upload_solr_document_builder.rb
- lib/spotlight/engine.rb
- spec/fixtures/iiif_responses.rb
- spec/models/spotlight/resources/iiif_manifest_spec.rb
Closes #1731 
* Fix thumbnail url for uploaded resources (slightly unrelated)
* Allow for string, array, or hash style labels.
* Allow for IIIF imported items to configure multiple title fields
> A few IIIF Importer improvements

- README.md
> Fix first-run instructions

- app/views/spotlight/filters/_form.html.erb
- config/locales/spotlight.en.yml
> Add instructions to the filter form; fixes #1407

- lib/migration/iiif.rb
- spec/lib/migration/iiif_spec.rb
> Migrate Upload Resources to IIIF.

- app/uploaders/spotlight/featured_image_uploader.rb
- spec/uploaders/spotlight/featured_image_uploader_spec.rb
The method name was changed in 1.0.0
> Update Carrierwave's extension whitelist method name.

- app/assets/javascripts/spotlight/pages.js.erb
- app/views/spotlight/pages/_form.html.erb
- lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb
- lib/spotlight/engine.rb
> Adds the ability to configure which sirtrevor widgets are shown

- app/views/spotlight/exhibits/_exhibit_card_back.html.erb
Fixes https://github.com/sul-dlss/exhibits/issues/550
> Truncate exhibit descriptions at whitespace

- lib/spotlight/version.rb
> bump to v1.1.0

- lib/spotlight/version.rb
> Bump to v1.2.0

- Rakefile
🤞 hoping this will fix our failing `master` build
> Pin Solr 7.1 until we can support 7.2

- lib/spotlight/version.rb
🎉 it's time for another Spotlight release
> Bump to v1.3.0

- app/views/spotlight/browse/_search.html.erb
- app/views/spotlight/searches/_search.html.erb
Closes #1884 
Needed for Sprockets >3.0
> add extension for default_browse_thumbnail

- lib/spotlight/version.rb
Time to cut a new Spotlight release!
🔪💎🔦
> Bump version to 1.4.1

- app/views/spotlight/translations/_general.html.erb
- app/views/spotlight/translations/_search_fields.html.erb
> enhances the responsiveness of translation forms

- .travis.yml
- spec/spec_helper.rb
> reenable travis container environment and use chrome with --no-sandbox

- .travis.yml
Discussed here: https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
> try bundler and sprockets caching

- blacklight-spotlight.gemspec
This was already submitted under i18n branch, but submitting to `master` too
> Stay below Capybara 3.0

- app/controllers/spotlight/catalog_controller.rb
- app/views/spotlight/translations/_general.html.erb
- spec/features/exhibits/translation_editing_spec.rb
Fixes #1991 
This PR accomplishes both tasks outlined in #1991.
> Did someone say breadcrumbs???

- .travis.yml
- Rakefile
- blacklight-spotlight.gemspec
> Cache the generated test app across builds

- config/locales/spotlight.en.yml
> adds missing key called from app/views/spotlight/sites/_exhibit.html.erb

- app/helpers/spotlight/languages_helper.rb
- app/views/spotlight/exhibits/_form.html.erb
- config/locales/spotlight.en.yml
- spec/helpers/spotlight/languages_helper_spec.rb
- spec/views/spotlight/exhibits/_form.html.erb_spec.rb
- spec/views/spotlight/exhibits/edit.html.erb_spec.rb
> disabled exhibit title edit in non default language

- app/controllers/concerns/spotlight/controller.rb
- app/models/concerns/spotlight/custom_translation_extension.rb
- lib/spotlight/version.rb
Starting to do backports now that #2013 has been merged.
> Backports for v1.5.1 release

- app/controllers/spotlight/languages_controller.rb
- app/controllers/spotlight/pages_controller.rb
- app/models/spotlight/language.rb
- app/services/spotlight/clone_translated_page_from_locale.rb
- config/locales/spotlight.en.yml
- spec/controllers/spotlight/about_pages_controller_spec.rb
- spec/controllers/spotlight/feature_pages_controller_spec.rb
- spec/controllers/spotlight/home_pages_controller_spec.rb
- spec/controllers/spotlight/languages_controller_spec.rb
- spec/models/spotlight/language_spec.rb
- spec/services/spotlight/clone_translated_page_from_locale_spec.rb
> Create home page automatically when a new language is created

- lib/spotlight/version.rb
(this was released in a backport already, but never got the version updated in master)
> Bump to version 1.5.1 🚧

- app/models/spotlight/page.rb
Updates to fix Rails deprecation warnings
> fix rails deprecation warnings

- app/controllers/spotlight/solr_controller.rb
- spec/controllers/spotlight/solr_controller_spec.rb
> Redirect successful raw solr document uploads back to the resources page; fixes #1900

- app/helpers/spotlight/languages_helper.rb
- app/models/spotlight/language.rb
- app/views/spotlight/exhibits/_languages.html.erb
- app/views/spotlight/translations/_browse_categories.html.erb
- app/views/spotlight/translations/_page.html.erb
- app/views/spotlight/translations/_pages_table.html.erb
- app/views/spotlight/translations/edit.html.erb
- config/locales/spotlight.en.yml
- lib/spotlight/engine.rb
- spec/helpers/spotlight/languages_helper_spec.rb
...also remove places where we're down-casing locale/languages.
> Fix pt-br locale to use uppercase BR.

- app/controllers/concerns/spotlight/controller.rb
- app/controllers/spotlight/pages_controller.rb
Instead make sure that a locale is available and returned.
> Modify default_url_options not to return early on the default language.

- lib/spotlight/version.rb
Wait for https://github.com/projectblacklight/spotlight/pull/2042
> bump to v2.0.0rc3

- config/locales/spotlight.en.yml
- spec/helpers/spotlight/languages_helper_spec.rb
> Fix spelling of Portuguese

- README.md
This PR adds information about where to get in touch with members of the Spotlight community.
> Add community info to README

- lib/spotlight/version.rb
> Bump version to 2.0.0.rc5.

- config/locales/spotlight.it.yml
- config/locales/spotlight.zh.yml
Closes #1972 and #1918 
Adds locale files for Chinese and Italian, with translations for end-user-facing strings (that is, non-admin UI strings).
> Add new locale files

- lib/generators/spotlight/templates/catalog_controller.rb
See https://github.com/projectblacklight/spotlight/issues/1812#issuecomment-327345318
Fixes GH-1453.
Fixes GH-1812.
Fixes GH-2099.
> enable facets by default

- app/models/spotlight/page.rb
- db/migrate/20181127085432_change_weight_on_pages.rb
- spec/models/spotlight/feature_page_spec.rb
Fixes https://github.com/sul-dlss/vatican_exhibits/issues/320
> Increase the maximum number of pages

- lib/spotlight/version.rb
And naturally, I neglected to bump the version file
> Bump version to 2.3.2

- app/controllers/spotlight/exhibits_controller.rb
- spec/controllers/spotlight/exhibits_controller_spec.rb
> Includes flash when redirecting from exhibits home page.

- blacklight-spotlight.gemspec
- config/routes.rb
- spec/routing/spotlight/exhibit_catalog_spec.rb
> Allow dots to appear in the identifier

- app/assets/javascripts/spotlight/catalog_edit.js
> Avoid using javascript keywords as variable names

- spec/controllers/spotlight/admin_users_controller_spec.rb
- spec/controllers/spotlight/exhibits_controller_spec.rb
- spec/controllers/spotlight/resources_controller_spec.rb
The success? predicate is deprecated and will be removed in Rails 6
> Use be_successful rather than be_success

- lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb
Show in a comment the default value.
> Default analytics_provider is not nil

- app/views/devise/confirmations/new.html.erb
See https://github.com/plataformatec/devise/commit/76b87dc0e83736cf16e3ffbc465fcd8ee3c06d46
Fixes #2156
> Avoid deprecated devise_error_messages!

- blacklight-spotlight.gemspec
> Remove pin of i18n

- .travis.yml
- app/helpers/spotlight/application_helper.rb
- blacklight-spotlight.gemspec
- spec/spec_helper.rb
Includes #2164, with updates to work with latest chrome + chromedriver-helper.
> render_document_class: avoid modifying frozen strings

- .travis.yml
- blacklight-spotlight.gemspec
- spec/spec_helper.rb
> Switch from chromedriver-helper to webdrivers.

- app/models/spotlight/blacklight_configuration.rb
Fixes https://github.com/sul-dlss/vatican_exhibits/issues/417
> Use paginated facets for exhibit tags

- app/models/concerns/spotlight/custom_translation_extension.rb
- spec/models/spotlight/custom_translation_extension_spec.rb
Fixes https://github.com/sul-dlss/vatican_exhibits/issues/410
> Reload I18n data across exhibit boundaries

- app/assets/javascripts/spotlight/blocks/solr_documents_base_block.js
Fixes https://github.com/sul-dlss/exhibits/issues/1406.
> Add additional compatibility for pre-IIIFification thumbnails

- .rubocop_todo.yml
- app/controllers/spotlight/resources/csv_upload_controller.rb
- app/controllers/spotlight/resources/upload_controller.rb
- app/controllers/spotlight/resources_controller.rb
- app/views/spotlight/resources/new.html.erb
- app/views/spotlight/resources/upload/_form.html.erb
- spec/controllers/spotlight/resources/csv_upload_controller_spec.rb
- spec/controllers/spotlight/resources/upload_controller_spec.rb
> fix redirects after uploading resources

- .rubocop.yml
- app/assets/javascripts/spotlight/admin/add_another.js
- app/controllers/spotlight/catalog_controller.rb
- app/controllers/spotlight/custom_fields_controller.rb
- app/controllers/spotlight/resources/upload_controller.rb
- app/controllers/spotlight/searches_controller.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/page.rb
- app/views/spotlight/custom_fields/_form.html.erb
- app/views/spotlight/custom_fields/form_group/_text.html.erb
- app/views/spotlight/custom_fields/form_group/_vocab.html.erb
- config/i18n-tasks.yml
- config/locales/spotlight.en.yml
- db/migrate/20190813085432_add_is_multiple_to_custom_fields.rb
- spec/controllers/spotlight/catalog_controller_spec.rb
- spec/controllers/spotlight/resources/upload_controller_spec.rb
- spec/features/add_custom_field_metadata_spec.rb
- spec/features/add_items_spec.rb
- spec/features/exhibits/custom_metadata_fields_spec.rb
> Add support for multivalued custom fields

- config/locales/spotlight.fr.yml
Adds French translations for user-facing (non-admin) fields not already covered in the Blacklight French locale file.
> Add French locale file

- app/models/sir_trevor_rails/blocks/featured_pages_block.rb
> sir_trevor: remove deleted feature pages from widget

- app/models/spotlight/resources/iiif_manifest.rb
- spec/fixtures/iiif_responses.rb
- spec/models/spotlight/resources/iiif_manifest_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1429
> Use the IIIF rules for handling multilingual metadata in a manifest

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
- app/assets/stylesheets/spotlight/_curation.scss
- app/views/spotlight/appearances/edit.html.erb
- app/views/spotlight/dashboards/_page.html.erb
- app/views/spotlight/dashboards/_page_activity.html.erb
- app/views/spotlight/dashboards/_reindexing_activity.html.erb
- app/views/spotlight/dashboards/show.html.erb
- app/views/spotlight/exhibits/_delete.html.erb
- app/views/spotlight/feature_pages/_header.html.erb
- app/views/spotlight/pages/_page.html.erb
- spec/views/spotlight/dashboards/_reindexing_activity.html.erb_spec.rb
> More bootstrap 4 styling fixes 

- lib/generators/spotlight/install_generator.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
This PR updates `blacklight-gallery` to take advantage of Arabic translations provided in [v1.1.0](https://github.com/projectblacklight/blacklight-gallery/releases/tag/v1.1.0).
> Update blacklight-gallery for Arabic translations

- app/views/spotlight/admin_users/index.html.erb
- vendor/assets/javascripts/bootstrap-tagsinput.js
> Convert bootstrap 3 labels into bootstrap 4 badges

- app/controllers/spotlight/featured_images_controller.rb
- app/models/spotlight/featured_image.rb
- app/presenters/spotlight/iiif_manifest_presenter.rb
- app/services/spotlight/upload_solr_document_builder.rb
- lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb
- lib/spotlight/engine.rb
- spec/presenters/spotlight/iiif_manifest_presenter_spec.rb
Fixes #2222; an alternative approach for the same functionality is being evaluated over in https://github.com/curationexperts/riiif/pull/129
> Revert IIIF configuration changes

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
- app/helpers/spotlight/crud_link_helpers.rb
- app/views/spotlight/shared/_configuration_sidebar.html.erb
- app/views/spotlight/shared/_curation_sidebar.html.erb
- app/views/spotlight/shared/_exhibit_sidebar.html.erb
- spec/helpers/spotlight/crud_link_helpers_spec.rb
> Add active classes to curator navs; fixes #1905

- app/views/shared/_curated_features_navbar.html.erb
Also fix typo in dropdown-item class
Part of #2224
> Add nav-item and nav-link classes to curated features navbar dropdown.

- app/assets/stylesheets/spotlight/_header.scss
> Fix responsive css for subtitles

- app/views/spotlight/searches/_form.html.erb
> Fix the display of search parameters; fixes #2253

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
- app/assets/stylesheets/spotlight/_browse.scss
- app/assets/stylesheets/spotlight/_exhibits_index.scss
- app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
- app/assets/stylesheets/spotlight/_multi_up_item_grid.scss
- app/assets/stylesheets/spotlight/_pages.scss
- app/assets/stylesheets/spotlight/_slideshow_block.scss
> Use breakpoint-min + -max functions instead of grid-breakpoints directly

- app/models/spotlight/contact_form.rb
- config/locales/spotlight.en.yml
- spec/models/spotlight/contact_form_spec.rb
> Use the site title in the email, if it is provided

- app/models/sir_trevor_rails/blocks/solr_documents_block.rb
- spec/features/javascript/blocks/solr_documents_block_spec.rb
- spec/models/sir_trevor_rails/blocks/solr_documents_block_spec.rb
> Cast serialized json string values back to booleans for the item captions

- app/views/shared/_header_navbar.html.erb
> Update header_navbar from upstream

- app/views/spotlight/exhibits/_contact.html.erb
- app/views/spotlight/exhibits/_form.html.erb
- app/views/spotlight/featured_images/_form.html.erb
- app/views/spotlight/translations/_browse_categories.html.erb
- app/views/spotlight/translations/_general.html.erb
- app/views/spotlight/translations/_metadata.html.erb
- app/views/spotlight/translations/_search_fields.html.erb
> Migrate p.form-text to small.form-text.text-muted

- lib/spotlight/version.rb
https://github.com/projectblacklight/spotlight/compare/v2.11.0...release-2.x
> Bump 2.x version to v2.12.0

- app/assets/stylesheets/spotlight/_report_a_problem.scss
- app/views/spotlight/shared/_report_a_problem.html.erb
> Update feedback form styling fixes #2290

- app/views/spotlight/browse/_search.html.erb
> Medium is the new small; fixes #2296

- app/assets/stylesheets/spotlight/_item_text_block.scss
- app/views/spotlight/admin_users/index.html.erb
- app/views/spotlight/sir_trevor/blocks/_oembed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
- spec/features/javascript/blocks/solr_documents_block_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_embed_block.html.erb_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb_spec.rb
> Fix sir-trevor left/right text orientation

- app/models/spotlight/search.rb
- app/views/spotlight/browse/_search.html.erb
- app/views/spotlight/browse/_search_title.html.erb
- app/views/spotlight/searches/_search.html.erb
- app/views/spotlight/sir_trevor/blocks/_browse_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_link_to_search_block.html.erb
- spec/models/spotlight/search_spec.rb
- spec/views/spotlight/browse/_search.html.erb_spec.rb
- spec/views/spotlight/browse/show.html.erb_spec.rb
Connected to sul-dlss/dlme#736
> Don't overwrite the fl param when querying for the documents in a browse category

- app/models/spotlight/ability.rb
Fixes https://github.com/projectblacklight/spotlight/issues/1752
> Allow curator + admin users to upload images for mastheads + thumbnails

- app/assets/stylesheets/spotlight/_slideshow_block.scss
- app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb_spec.rb
> Fix Item Slideshow / Solr Documents Features Block post BS4

- app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb
- spec/features/javascript/blocks/solr_documents_carousel_block_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb_spec.rb
> Fix issues w/ Carousel Widget

- app/views/devise/mailer/invitation_instructions.html.erb
Fixes an issue where invitations sent in multi-lingual exhibits raise an
error.
Fixes https://github.com/sul-dlss/dlme/issues/810
> Add locale to mailer invite

- app/assets/stylesheets/spotlight/_blacklight_overrides.scss
- app/assets/stylesheets/spotlight/_curation.scss
See https://github.com/sul-dlss/exhibits/issues/1478
> Fixes issue where search-btn in input group can be off

- app/assets/javascripts/spotlight/admin/blocks/solr_documents_base_block.js
- app/assets/javascripts/spotlight/admin/multi_image_selector.js
Addresses https://github.com/sul-dlss/exhibits/issues/1490
Classes were changed in https://github.com/projectblacklight/spotlight/commit/864f5622068465b6861b2aa77b980988330a0ee3
> Fix thumb selector for item widget

- app/views/spotlight/appearances/edit.html.erb
https://github.com/sul-dlss/exhibits/issues/1486
> Update BS classes to correctly wrap theme selection

- app/assets/stylesheets/spotlight/_header.scss
Removed in https://github.com/projectblacklight/spotlight/commit/1a4f3654758c9d02b978b48b3ca802dfada05264
Addressing https://github.com/sul-dlss/exhibits/issues/1493
> Retain capitialization for header navbar

- app/models/spotlight/reindex_progress.rb
- app/views/spotlight/dashboards/_page.html.erb
- app/views/spotlight/dashboards/_reindexing_activity.html.erb
- app/views/spotlight/sites/_exhibit.html.erb
- spec/models/spotlight/reindex_progress_spec.rb
- spec/views/spotlight/dashboards/_reindexing_activity.html.erb_spec.rb
Part of https://github.com/sul-dlss/exhibits/issues/1469
> Use the long date format to get the year to display

- app/assets/stylesheets/spotlight/_exhibits_index.scss
- app/helpers/spotlight/crud_link_helpers.rb
- app/views/spotlight/exhibits/_tags.html.erb
- spec/helpers/spotlight/crud_link_helpers_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1516
> Update exhibits tabs markup for bootstrap  4

- app/assets/stylesheets/spotlight/_exhibits_index.scss
- app/views/spotlight/exhibits/_exhibit_card_back.html.erb
- app/views/spotlight/exhibits/_exhibits.html.erb
Aiming to address https://github.com/sul-dlss/exhibits/issues/1517
> Update homepage styling to be more BS4

- app/views/spotlight/custom_search_fields/edit.html.erb
- app/views/spotlight/custom_search_fields/new.html.erb
Fixes https://github.com/sul-dlss/exhibits/issues/1535
> Update custom search field

- app/assets/stylesheets/spotlight/_header.scss
Fixes https://github.com/sul-dlss/exhibits/issues/1545
> Reduce masthead padding

- app/assets/javascripts/spotlight/admin/search_typeahead.js
- app/assets/stylesheets/spotlight/_catalog.scss
- app/assets/stylesheets/spotlight/_item_text_block.scss
- app/assets/stylesheets/spotlight/_pages.scss
- app/views/catalog/_image_default.html.erb
Just some maintenance to remove styles that are not used. (as far as I can tell)
> Update thumb stylin

- app/views/spotlight/browse/_search_box.html.erb
> Fix minor issues w/ the search w/i a browse category form

- config/locales/spotlight.es.yml
Closes #2387 
Related: projectblacklight/blacklight-gallery#73
Translation provided by Adan Griego, griego@stanford.edu
> Add Spanish (es) locale file

- app/views/spotlight/searches/_form.html.erb
- config/locales/spotlight.en.yml
- spec/features/browse_category_admin_spec.rb
> Update labels for browse category search box config

- app/assets/stylesheets/spotlight/_catalog.scss
- app/views/spotlight/custom_fields/form_group/_text.html.erb
- app/views/spotlight/custom_fields/form_group/_vocab.html.erb
- app/views/spotlight/resources/upload/_form.html.erb
- config/locales/spotlight.en.yml
> Address Custom Field form field layout in add/edit forms 

- app/assets/javascripts/spotlight/admin/exhibits.js
- app/views/spotlight/exhibits/_contact.html.erb
- app/views/spotlight/exhibits/_form.html.erb
- config/locales/spotlight.en.yml
- spec/features/exhibits/administration_spec.rb
> Update contact email label/inputs to be more accessible

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
> Remove admin tab-pane negative margin

- app/views/catalog/_image_default.html.erb
- app/views/spotlight/about_pages/_contact_properties.html.erb
- app/views/spotlight/browse/_search.html.erb
- app/views/spotlight/catalog/_admin_thumbnail_default.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_carousel_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_features_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb
- app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
- spec/features/javascript/blocks/uploaded_items_block_spec.rb
- spec/views/spotlight/sir_trevor/blocks/_solr_documents_grid_block.html.erb_spec.rb
Part of https://github.com/sul-dlss/exhibits/issues/1585
> Improve image alt texts

- app/assets/stylesheets/spotlight/_catalog.scss
- app/models/concerns/spotlight/solr_document.rb
- app/views/layouts/spotlight/spotlight.html.erb
> Small refactors to improve downstream customizations

- app/assets/stylesheets/spotlight/_bootstrap_overrides.scss
> Update file upload spacing

- app/views/spotlight/pages/_view_type_group.html.erb
- app/views/spotlight/sir_trevor/blocks/_search_results_block.html.erb
> Fix layout issue w/ Search Results Block

- app/views/layouts/spotlight/spotlight.html.erb
- app/views/shared/_breadcrumbs.html.erb
- app/views/shared/_exhibit_navbar.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_masthead.html.erb
- app/views/spotlight/browse/_sort_and_per_page.html.erb
- app/views/spotlight/sir_trevor/blocks/_search_results_block.html.erb
- config/locales/spotlight.en.yml
Update various aria-labels and landmarks.
Part of an accessibility review in Stanford's spotlight application sul-dlss/exhibits#1619
Related work upstream in https://github.com/projectblacklight/blacklight/pull/2241
> Update various aria-labels and landmarks.

- app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
Fixes https://github.com/sul-dlss/exhibits/issues/1655
> Update category/widget tile breakpoints to be better BS4

- app/views/spotlight/sir_trevor/blocks/_quote_block.html.erb
Part of https://github.com/sul-dlss/exhibits/issues/1658
> Apply bootstrap blockquote styling

- app/views/spotlight/translations/edit.html.erb
Fixes https://github.com/sul-dlss/exhibits/issues/1669
> Use default BS4 pill styling for translation language

- app/controllers/spotlight/translations_controller.rb
- spec/controllers/spotlight/translations_controller_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1670
> Add breadcrumbs to translation edit page

- app/assets/stylesheets/spotlight/_pages.scss
- app/helpers/spotlight/pages_helper.rb
- app/views/spotlight/about_pages/_contact_properties.html.erb
- spec/helpers/spotlight/pages_helper_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1657
> Improve contact email wrapping

- app/views/spotlight/exhibits/index.html.erb
- spec/views/spotlight/exhibits/index.html.erb_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/1701
> Update exhibits pagination to use bootstrap 4 classes

- config/locales/spotlight.es.yml
> Fix es locale file, somethings were not under the spotlight key 

- app/views/spotlight/browse/_search_box.html.erb
Fixes https://github.com/sul-dlss/exhibits/issues/1713
> Add labelled by for browse search form

- app/views/spotlight/search_configurations/_search_fields.html.erb
- app/views/spotlight/search_configurations/_sort.html.erb
Fixes https://github.com/sul-dlss/exhibits/issues/1723
> Update markup for drag and droppeed in-place editable cards

- app/views/spotlight/feature_pages/_sidebar.html.erb
- spec/views/spotlight/feature_pages/_sidebar.html.erb_spec.rb
> Only render subsections if there are documents to show

- app/assets/stylesheets/spotlight/_pages.scss
Fixes https://github.com/sul-dlss/exhibits/issues/1848
Fixes https://github.com/sul-dlss/exhibits/issues/1851
> Set a minwidth so that the css does not reflow

- app/assets/javascripts/spotlight/admin/blocks/browse_block.js
- app/assets/stylesheets/spotlight/_browse.scss
- app/assets/stylesheets/spotlight/_curation.scss
- app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
- app/controllers/spotlight/browse_controller.rb
- app/controllers/spotlight/searches_controller.rb
- app/models/spotlight/search.rb
- app/views/catalog/_save_search.html.erb
- app/views/spotlight/browse/_search.html.erb
- app/views/spotlight/browse/_search_title.html.erb
- app/views/spotlight/searches/_form.html.erb
- app/views/spotlight/searches/_search.html.erb
- app/views/spotlight/sir_trevor/blocks/_browse_block.html.erb
- app/views/spotlight/translations/_browse_categories.html.erb
- db/migrate/20200403161512_add_subtitle_to_searches.rb
- spec/features/exhibits/translation_editing_spec.rb
Fixes https://github.com/sul-dlss/dlme/issues/892
> Add subtitles to browse categories

- app/assets/stylesheets/spotlight/_translations.scss
- app/views/spotlight/translations/_browse_categories.html.erb
- config/locales/spotlight.en.yml
Includes #2509 (so we avoid a silly merge conflict)
Fixes #2511
> Put browse category subtitle translations into a collapse

- app/assets/stylesheets/spotlight/_accessibility.scss
🤷 https://github.com/sass/sass/issues/1873#issuecomment-152293725
cc @camillevilla 
Breaking spotlight builds using sassc 2.3.0
> Update selector to be compatible with sassc 2.3.0

- app/assets/javascripts/spotlight/admin/crop.es6
- app/controllers/spotlight/appearances_controller.rb
- app/controllers/spotlight/exhibits_controller.rb
- app/controllers/spotlight/featured_images_controller.rb
- app/helpers/spotlight/crop_helper.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/featured_image.rb
- app/models/spotlight/temporary_image.rb
- app/services/spotlight/exhibit_import_export_service.rb
- spec/factories/featured_images.rb
- spec/models/spotlight/featured_image_spec.rb
- spec/services/spotlight/exhibit_import_export_service_spec.rb
> Fix up new import/export service

- app/models/spotlight/about_page.rb
- app/models/spotlight/feature_page.rb
- app/models/spotlight/home_page.rb
- app/models/spotlight/page.rb
- spec/models/spotlight/page_spec.rb
> Blacklist page  slugs that conflict with our routing

- app/services/spotlight/exhibit_import_export_service.rb
- spec/services/spotlight/exhibit_import_export_service_spec.rb
Fixes issues reported in https://github.com/sul-dlss/dlme/issues/982
> Stringify blacklight configuration data

- config/locales/spotlight.ar.yml
> Add missing browse category item Arabic translations

- app/assets/javascripts/spotlight/admin/crop.es6
- vendor/assets/javascripts/leaflet-iiif.js
\+ Update to leaflet-iiif 3.0.0
Fixes #2537
> Fix bug when tile-source for a cropped image fails to load

- app/assets/stylesheets/spotlight/_item_text_block.scss
Fixes https://github.com/sul-dlss/exhibits/issues/1902
> Layer items above text

- config/i18n-tasks.yml
- config/locales/spotlight.en.yml
- spec/features/exhibits/administration_spec.rb
> Relabel exhibit contacts  'feedback recipients'; fixes #2538

- app/assets/stylesheets/spotlight/_report_a_problem.scss
- app/views/spotlight/shared/_honeypot_field.html.erb
- app/views/spotlight/shared/_report_a_problem.html.erb
- config/i18n-tasks.yml
- config/locales/spotlight.en.yml
- spec/features/report_a_problem_spec.rb
> Update layout of Feedback (Report a problem) form

- app/models/spotlight/blacklight_configuration.rb
- app/views/spotlight/catalog/index.iiif_json.jbuilder
- config/routes.rb
- lib/spotlight/engine.rb
> Generate a IIIF collection for the spotlight exhibit

- app/services/spotlight/exhibit_import_export_service.rb
> Replace deprecated update_attributes with update

- app/views/spotlight/catalog/_document.html.erb
instead of copying the partial content over
> Try to render Blacklight's document partial from spotlight

- app/assets/javascripts/spotlight/admin/add_new_button.js
- app/controllers/spotlight/groups_controller.rb
- app/controllers/spotlight/searches_controller.rb
- app/models/spotlight/ability.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/group.rb
- app/models/spotlight/search.rb
- app/views/spotlight/searches/_group.html.erb
- app/views/spotlight/searches/index.html.erb
- config/i18n-tasks.yml
- config/locales/spotlight.en.yml
- config/routes.rb
- spec/controllers/spotlight/groups_controller_spec.rb
- spec/controllers/spotlight/searches_controller_spec.rb
- spec/features/javascript/about_page_admin_spec.rb
- spec/features/javascript/block_controls_spec.rb
- spec/features/javascript/browse_group_admin_spec.rb
- spec/features/javascript/edit_in_place_spec.rb
- spec/features/javascript/feature_page_admin_spec.rb
- spec/models/spotlight/search_spec.rb
- spec/spec_helper.rb
Fixes #2594 Fixes #2596 , split out ticket #2607 for future
> Enable Browse Group administration

- app/assets/javascripts/spotlight/user/browse_group_categories.js
- app/assets/stylesheets/spotlight/browse_group_categories_block.scss
- vendor/assets/javascripts/tiny-slider.js
Fixes https://github.com/sul-dlss/dlme/issues/1172
I hate that we have to do use a custom version: https://github.com/ganlanyuan/tiny-slider/pull/658 but not really sure what our alternative is. 
Note the spacing is off because I don't have docs indexed so it thinks there should be facets.
> Supports RTL in browse group categories slider widget

- app/models/spotlight/solr_document_sidecar.rb
- spec/models/spotlight/solr_document_sidecar_spec.rb
> Ensure empty values for upload fields remove the value from the index

- app/assets/stylesheets/spotlight/browse_group_categories_block.scss
- app/views/spotlight/sir_trevor/blocks/_browse_group_categories_block.html.erb
Also fixes https://github.com/sul-dlss/dlme/issues/1185
> Fix an overflow issue in RTL for FeaturePage slider

- app/views/spotlight/sir_trevor/blocks/_browse_group_categories_block.html.erb
- config/locales/spotlight.ar.yml
- config/locales/spotlight.en.yml
> Add Arabic translations for Browse Group Category features fixes #2640

- spec/test_app_templates/Gemfile.extra
Until https://github.com/github/view_component/issues/642 is resolved
> Temporarily prevent us from using view_component v2.26.0

- .github/workflows/ruby.yml
> Run CI on all pull requests (not just master)

- app/helpers/spotlight/application_helper.rb
- spec/helpers/spotlight/application_helper_spec.rb
> Use the right field name for linking to tags

- app/assets/javascripts/spotlight/admin/catalog_edit.js
- app/assets/javascripts/spotlight/admin/exhibit_tag_autocomplete.js
- app/assets/stylesheets/spotlight/_catalog.scss
- app/controllers/spotlight/bulk_actions_controller.rb
- app/jobs/concerns/spotlight/gather_documents.rb
- app/jobs/spotlight/add_tags_job.rb
- app/jobs/spotlight/change_visibility_job.rb
- app/views/catalog/_bulk_actions.html.erb
- app/views/spotlight/catalog/_edit_default.html.erb
- config/locales/spotlight.en.yml
- config/routes.rb
- spec/controllers/spotlight/bulk_actions_controller_spec.rb
- spec/features/bulk_actions_spec.rb
- spec/jobs/spotlight/add_tags_job_spec.rb
- spec/views/spotlight/catalog/_edit_default.html.erb_spec.rb
> Adds bulk action to add tags

- app/assets/stylesheets/spotlight/_catalog.scss
- app/controllers/concerns/spotlight/catalog.rb
- app/controllers/spotlight/browse_controller.rb
- app/models/spotlight/blacklight_configuration.rb
- app/views/catalog/_add_tags.html.erb
- app/views/catalog/_bulk_actions.html.erb
- app/views/catalog/_change_visibility.html.erb
- app/views/catalog/_curator_actions.html.erb
- spec/controllers/spotlight/catalog_controller_spec.rb
> Use a shared 'tool' for all curator actions and use blacklight config for tools + actions

- app/assets/javascripts/spotlight/admin/exhibit_tag_autocomplete.js
- app/controllers/spotlight/bulk_actions_controller.rb
- app/jobs/spotlight/remove_tags_job.rb
- app/models/spotlight/blacklight_configuration.rb
- app/views/catalog/_remove_tags.html.erb
- config/i18n-tasks.yml
- config/locales/spotlight.en.yml
- config/routes.rb
- spec/controllers/spotlight/bulk_actions_controller_spec.rb
- spec/features/bulk_actions_spec.rb
- spec/jobs/spotlight/remove_tags_job_spec.rb
Fixes #2650 
Paired and confirmed the ux changes from the ticket w/ @ggeisler
> Adds the ability to bulk action remove tags

- spec/controllers/spotlight/bulk_actions_controller_spec.rb
- spec/factories/exhibits.rb
Paired w/ @jkeck on this one.
Fixes #2693 
Have rerun CI `3` times with all 🍏
> Fix issues with flaky bulk actions/update specs

- app/models/concerns/spotlight/resources/web.rb
- app/models/spotlight/resources/iiif_harvester.rb
- app/models/spotlight/resources/iiif_service.rb
- app/services/spotlight/iiif_resource_resolver.rb
- lib/spotlight/engine.rb
Fixes https://github.com/sul-dlss/exhibits/issues/2029 🤷‍♂️
> Follow HTTP redirects when retrieving IIIF resources

- app/controllers/spotlight/bulk_updates_controller.rb
- app/services/spotlight/bulk_updates_csv_template_service.rb
- app/views/spotlight/bulk_updates/_download.html.erb
- spec/services/spotlight/bulk_updates_csv_template_service_spec.rb
>  Stream the bulk update template CSV

- app/controllers/spotlight/bulk_updates_controller.rb
> Make BulkUpdatesController 'live'

- app/controllers/concerns/spotlight/catalog.rb
- config/locales/spotlight.en.yml
> Add a query facet for 'public' items

- app/assets/javascripts/spotlight/admin/blocks/uploaded_items_block.js
- app/models/sir_trevor_rails/blocks/uploaded_items_block.rb
- app/views/spotlight/sir_trevor/blocks/_uploaded_items_block.html.erb
- config/locales/spotlight.en.yml
- spec/features/javascript/blocks/uploaded_items_block_spec.rb
Fixes #2583
https://user-images.githubusercontent.com/111218/113311673-68863700-92be-11eb-9bf8-73488a5ad882.mp4
> Add support for ZPR links for uploaded item rows

- app/assets/stylesheets/spotlight/_nestable.scss
- app/controllers/spotlight/tags_controller.rb
- app/jobs/spotlight/rename_tags_job.rb
- app/views/spotlight/tags/_tag.html.erb
- app/views/spotlight/tags/index.html.erb
- config/locales/spotlight.en.yml
- config/routes.rb
- spec/controllers/spotlight/tags_controller_spec.rb
- spec/i18n_spec.rb
- spec/views/spotlight/tags/index.html.erb_spec.rb
Part of #2664 
https://user-images.githubusercontent.com/111218/113211394-44791600-922a-11eb-9147-7beb56e56a1e.mp4
> Add a job to rename/delete tags

- app/jobs/spotlight/rename_tags_job.rb
> Explicitly reindex documents with changed tags

- app/views/spotlight/browse/_search_title.html.erb
> Remove funky parent search count from search title partial

- app/views/spotlight/sir_trevor/blocks/_search_results_block.html.erb
Part of https://github.com/sul-dlss/exhibits/issues/2087
> Add some additional margin around the search results view type widget

- .github/workflows/ruby.yml
- app/controllers/spotlight/pages_controller.rb
- app/views/spotlight/pages/_order_pages.html.erb
Needed for Rails 6.1.3.2 etc that enforce this requirement with the exception:
> ArgumentError: Please use symbols for polymorphic route arguments
Fixes https://github.com/sul-dlss/exhibits/issues/2092
> Symbolize our strings used in paths

- spec/features/javascript/blocks/search_result_block_spec.rb
Replaces #2748, now that an upstream fix is available
> Check that we rendered the right view in search results block

- app/views/layouts/spotlight/base.html.erb
- spec/views/spotlight/pages/show.html.erb_spec.rb
> Only include Skip to search link on pages that have search

- app/views/spotlight/exhibits/_import.html.erb
- app/views/spotlight/exhibits/_languages.html.erb
- app/views/spotlight/filters/_form.html.erb
- app/views/spotlight/resources/upload/_form.html.erb
- app/views/spotlight/translations/_browse_categories.html.erb
- app/views/spotlight/translations/_groups.html.erb
- app/views/spotlight/translations/_import.html.erb
- app/views/spotlight/translations/_metadata.html.erb
- app/views/spotlight/translations/_search_fields.html.erb
> Omit HTML id attributes for the 'current tab tracking' hidden field

- README.md
> Update requirements listed in the README

- app/controllers/spotlight/attachments_controller.rb
- app/controllers/spotlight/custom_search_fields_controller.rb
- app/controllers/spotlight/pages_controller.rb
- app/controllers/spotlight/searches_controller.rb
- app/helpers/spotlight/application_helper.rb
- app/helpers/spotlight/main_app_helpers.rb
- spec/models/spotlight/page_spec.rb
> Tweak log messages and comments

- lib/generators/spotlight/templates/config/initializers/translation.rb
- lib/spotlight/engine.rb
…for Rails 7 (Zeitwerk?) compatibility
> Wrap initializers that depend on Rails autoloading with to_prepare

- config/locales/spotlight.de.yml
Adds German translations, provided by a translator in Stanford Libraries.
> Add German locale file

- .github/workflows/ruby.yml
- .rubocop.yml
- app/controllers/spotlight/roles_controller.rb
- blacklight-spotlight.gemspec
- spec/controllers/spotlight/roles_controller_spec.rb
```
ArgumentError:
Polymorphic associations do not support computing the class.
```
> Work around a cancancan regression with polymorphic relations

- app/views/spotlight/sir_trevor/blocks/_video_block.html.erb
- spec/features/autocomplete_typeahead_spec.rb
- spec/features/javascript/multi_image_select_spec.rb
Fixes https://github.com/sul-dlss/exhibits/issues/2210
> Fix video block's local variable

- .github/workflows/ruby.yml
- app/models/spotlight/search.rb
- lib/spotlight/engine.rb
This is, perhaps, kicking the can down the road until Rails provides a better option for serializing user input from forms, or we feel like adding a custom serializer.
> Update Rails versions under CI

- app/models/spotlight/search.rb
Fixes https://github.com/sul-dlss/exhibits/issues/2225
> Make sure Search#query_params has a default value; related to #2837

- README.md
Addresses https://github.com/projectblacklight/spotlight/issues/2832
> document docker-compose

- package.json
This works best for javascript tools like sass, webpack, and esbuild
> Publish assets to NPM

- app/views/shared/_exhibit_navbar.html.erb
- spec/views/shared/_exhibit_navbar.html.erb_spec.rb
> Avoid deprecated method render_search_bar

- Dockerfile
- lib/generators/spotlight/install_generator.rb
Spotlight has lots of turbolinks code, so let's test it.
Reverts part of https://github.com/projectblacklight/spotlight/pull/2865/commits/ccf26faf6d9f89f556d50ea726d97be780088ee6
> Revert adding shakapacker

- app/assets/javascripts/spotlight/admin/block_mixins/autocompleteable.js
- app/assets/javascripts/spotlight/admin/block_mixins/formable.js
- app/assets/javascripts/spotlight/admin/block_mixins/plustextable.js
- app/assets/javascripts/spotlight/admin/blocks/block.js
- app/assets/javascripts/spotlight/admin/blocks/browse_block.js
- app/assets/javascripts/spotlight/admin/blocks/browse_group_categories_block.js
- app/assets/javascripts/spotlight/admin/blocks/iframe_block.js
- app/assets/javascripts/spotlight/admin/blocks/oembed_block.js
- app/assets/javascripts/spotlight/admin/blocks/resources_block.js
- app/assets/javascripts/spotlight/admin/blocks/rule_block.js
- app/assets/javascripts/spotlight/admin/blocks/search_result_block.js
- app/assets/javascripts/spotlight/admin/blocks/solr_documents_base_block.js
- app/assets/javascripts/spotlight/admin/blocks/solr_documents_block.js
- app/assets/javascripts/spotlight/admin/blocks/solr_documents_carousel_block.js
- app/assets/javascripts/spotlight/admin/blocks/uploaded_items_block.js
- app/assets/javascripts/spotlight/admin/index.js
- blacklight-spotlight.gemspec
- lib/spotlight/engine.rb
All the functionality we need is now part of the browser.
> Drop dependency on underscore-rails

- Rakefile
- bin/db-migrate-seed.sh
- bin/docker-entrypoint.sh
- lib/generators/spotlight/install_generator.rb
This is the rails documented way to run these tasks. See https://guides.rubyonrails.org/active_record_migrations.html\#running-migrations
> Use bin/rails rather than bundle exec rake

- app/assets/javascripts/spotlight/spotlight.js
- app/assets/javascripts/spotlight/user/zpr_links.js
This will enable us to switch to other asset pipelines
> Stop compiling javascript with erb

- vendor/assets/javascripts/parameterize.js
> Declare the downcode variable

- app/controllers/spotlight/pages_controller.rb
- app/controllers/spotlight/versions_controller.rb
- app/helpers/spotlight/crud_link_helpers.rb
- app/views/spotlight/admin_users/index.html.erb
- app/views/spotlight/catalog/_admin_header.html.erb
- app/views/spotlight/exhibits/_confirmation_status.html.erb
- app/views/spotlight/exhibits/_contact.html.erb
- app/views/spotlight/translations/_page.html.erb
> Stop using deprecated rails-ujs options for link_to

- blacklight-spotlight.gemspec
- lib/generators/spotlight/install_generator.rb
- lib/spotlight/engine.rb
Sprockets-es6 has been obsolete since 2016
> Simplify javascript bundling on Rails 6

- app/assets/stylesheets/spotlight/_browse.scss
workaround by multiplying instead
> The / operator is deprecated in sass

- app/assets/stylesheets/spotlight/_variables.scss
These stopped being used in #2239
> Remove unused variables

- app/views/spotlight/pages/_order_pages.html.erb
- app/views/spotlight/searches/index.html.erb
Add new browse group button was not allowing clicking.  Adding "data-turbo=false" should remedy this.
> adding data-turbo=false

- lib/generators/spotlight/templates/spotlight.scss
> Use pure sass in the template

- app/javascript/spotlight/admin/blocks/solr_documents_base_block.js
@hackartisan and I had a very, very hard time parsing out how it was possible autocomplete wasn't returning IIIF information but somehow carousels were storing iiif_tilesource. I've renamed a couple variables and added some documentation that I wish we'd had while we were digging.
> Add some documentation to solr_documents_base_block.js

- spec/features/javascript/blocks/solr_documents_block_spec.rb
This test no longer seems to pass in CI. Some changes to the setup so it will pass locally.
> Fix flappy test

- app/models/spotlight/event.rb
- app/models/spotlight/job_tracker.rb
See https://github.com/rails/rails/blob/v7.1.2/activerecord/CHANGELOG.md\?plain\=1\#L995 
Fixes #3001
> Set the coder when using serialize

- app/models/spotlight/blacklight_configuration.rb
- app/models/spotlight/contact.rb
- app/models/spotlight/custom_field.rb
- app/models/spotlight/custom_search_field.rb
- app/models/spotlight/exhibit.rb
- app/models/spotlight/resource.rb
- app/models/spotlight/solr_document_sidecar.rb
see item ticket here: https://github.com/projectblacklight/spotlight/issues/3001#issuecomment-1914915935
> Coder: YAML change

- app/assets/stylesheets/spotlight/_exhibit_admin.scss
This will help make Spotlight compatible with bootstrap 4 or 5
> Avoid border-right-radius Boostrap 4 mixin

- app/controllers/spotlight/solr_controller.rb
Merging https://github.com/projectblacklight/spotlight/pull/2986 broke the tests. This refactors the fix slightly so the tests for solr_controller will work.
> Refactor solr repository fix so tests will pass

- spec/features/exhibits/translation_editing_spec.rb
- spec/spec_helper.rb
> Set window size to make test setup more predictable

- .github/workflows/ruby.yml
Trying to fix CI error:
`[EngineCart] Unable to find test application dependencies in /home/runner/work/spotlight/spotlight/.internal_test_app/Gemfile, using placeholder dependencies`
> Change permissions in CI

- app/javascript/spotlight/admin/blocks/uploaded_items_block.js
> Remove errant characters from uploaded items block

- Dockerfile
https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
> Use equals with docker env vars

- lib/generators/spotlight/templates/catalog_controller.rb
> Set add_results_collection_tool configs in CatalogController template

- .github/workflows/ruby.yml
- Rakefile
- app/models/spotlight/featured_image.rb
- blacklight-spotlight.gemspec
- lib/generators/spotlight/install_generator.rb
- spec/features/import_exhibit_spec.rb
- spec/test_app_templates/lib/generators/test_app_generator.rb
- template.rb
> Drop support for Rails 6

- app/views/spotlight/dashboards/analytics.html.erb
- spec/views/spotlight/dashboards/analytics.html.erb_spec.rb
> remove link for analytics view

- lib/generators/spotlight/templates/config/initializers/spotlight_initializer.rb
> fix upload_fields in spotlight_initializer

- app/controllers/concerns/spotlight/controller.rb
Path name changed with https://github.com/projectblacklight/blacklight/pull/1277/files#diff-167663e30c7d3f4b512919f01eedb181ac2289d9ec846a4e88e21066fbb9af98R751
closes #2810
> fix catalog_facet_url path

- .github/workflows/ruby.yml
- spec/controllers/spotlight/catalog_controller_spec.rb
- spec/test_app_templates/Gemfile.extra
- spec/test_app_templates/lib/generators/test_app_generator.rb
- spec/views/shared/_header_navbar.html.erb_spec.rb
- spec/views/spotlight/pages/show.html.erb_spec.rb
> Add a Blacklight 8 build

- app/components/blacklight/icons/arrow_alt_circle_left_component.rb
- app/components/blacklight/icons/arrow_alt_circle_right_component.rb
- app/components/blacklight/icons/arrow_back_ios_component.rb
- app/components/blacklight/icons/arrow_forward_ios_component.rb
- app/components/blacklight/icons/check_circle_component.rb
- app/components/blacklight/icons/check_component.rb
- app/components/blacklight/icons/chevron_right_component.rb
- app/components/blacklight/icons/close_component.rb
- app/components/blacklight/icons/edit_component.rb
- app/components/blacklight/icons/error_component.rb
- app/components/blacklight/icons/highlight_off_component.rb
- app/components/blacklight/icons/info_component.rb
- app/components/blacklight/icons/warning_component.rb
- app/components/blacklight/icons/zoom_in_component.rb
- app/components/blacklight/icons/zoom_out_component.rb
- app/components/spotlight/icon_component.rb
(and use it to work around a bug in Blacklight 7.)
> Define a base spotlight icon component class

- app/views/spotlight/catalog/_document_admin_table.html.erb
> Use the default view type on the admin page

- app/views/spotlight/catalog/edit.html.erb
> Support rendering Blacklight 7 partials on the catalog#edit template

- .env
- docker-compose.yml
Because Postgres 12 is EOL soon.
> Update the database in docker compose

- app/views/spotlight/bulk_updates/_download.html.erb
> fix download_template_exhibit_bulk_updates

- app/views/spotlight/translations/_import.html.erb
> fix loading bar on translation download

- .github/workflows/ruby.yml
>  Get the CI workflow back on Ubuntu latest

- app/views/spotlight/resources/csv_upload/_form.html.erb
> Set data-turbo: false on download template link

- app/views/spotlight/job_trackers/show.html.erb
Fixes #3227 
This fixes the issue described in #3227 for Blacklight 8.
> Use data-bl-dismiss attribute for blacklight modal

- app/controllers/spotlight/languages_controller.rb
- app/views/spotlight/exhibits/_languages.html.erb
> Use turbo streams for translation language removal

- app/views/spotlight/job_trackers/show.html.erb
> Convert job tracker modal to use upstream Blacklight::System::ModalComponent

- app/components/spotlight/breadcrumbs_component.rb
Backport https://github.com/projectblacklight/spotlight/pull/3268
Fix for https://github.com/sul-dlss/exhibits/issues/2638
> backport fix breadcrumbs for polymorphic paths #3268

- app/assets/stylesheets/spotlight/_mixins.scss
Backport https://github.com/projectblacklight/spotlight/pull/3276/files to v4
> Backport: Set private label text color to black

- app/views/spotlight/shared/_exhibit_sidebar.html.erb
- spec/views/spotlight/dashboards/analytics.html.erb_spec.rb
> Backport namespace reference to exhibit_alt_text_path

- app/models/spotlight/blacklight_configuration.rb
- app/views/spotlight/metadata_configurations/_metadata_field.html.erb
- app/views/spotlight/metadata_configurations/edit.html.erb
- config/locales/spotlight.en.yml
closes https://github.com/sul-dlss/exhibits/issues/2623
> add type column to metadata table

- app/views/spotlight/custom_fields/form_group/_text.html.erb
- app/views/spotlight/custom_fields/form_group/_vocab.html.erb
Before (BS5):
After (BS4):
After (BS5):
> Fix "Add another value" button styling

- app/views/spotlight/bulk_updates/_upload.html.erb
- app/views/spotlight/custom_fields/form_group/_text.html.erb
- app/views/spotlight/custom_fields/form_group/_vocab.html.erb
- app/views/spotlight/feature_pages/_header.html.erb
- app/views/spotlight/translations/_import.html.erb
Backport to release-4.x:
- https://github.com/projectblacklight/spotlight/pull/3305/files
- https://github.com/projectblacklight/spotlight/pull/3306/files
- https://github.com/projectblacklight/spotlight/pull/3306/files
> Various backports to 4.x

- app/controllers/spotlight/accessibility_controller.rb
- app/views/spotlight/accessibility/alt_text.html.erb
closes https://github.com/sul-dlss/exhibits/issues/2669
> have totals in dashboard be for all items

- app/controllers/spotlight/accessibility_controller.rb
- app/views/spotlight/accessibility/alt_text.html.erb
Backports https://github.com/projectblacklight/spotlight/pull/3316 to release-4.x
> backport: have totals in dashboard be for all items, remove limit

- app/assets/stylesheets/spotlight/_exhibits_index.scss
- app/assets/stylesheets/spotlight/_variables.scss
Set --bs-card-bg if a background change is needed.
> Remove unnecessary exhibit-card variables

- app/components/spotlight/header_navigation_link_component.html.erb
- app/components/spotlight/header_navigation_link_component.rb
- app/views/shared/_about_navbar.html.erb
- app/views/shared/_browse_navbar.html.erb
- app/views/shared/_curated_features_navbar.html.erb
- lib/spotlight/engine.rb
- spec/components/spotlight/header_navigation_link_component_spec.rb
Backport https://github.com/projectblacklight/spotlight/pull/3324 to release-4.x
> Backport: Extract the HeaderNavigationLinkComponent

- app/assets/stylesheets/spotlight/_exhibits_index.scss
> fix card bg on hover

- app/views/spotlight/admin_users/index.html.erb
You can't float a flex item (from .card-body)
> Fix float attempt on flex item

- .github/workflows/ruby.yml
- spec/features/javascript/feature_page_admin_spec.rb
Backports relevant parts of https://github.com/projectblacklight/spotlight/pull/3337 to release-4.x
> Backport: unpin chrome version; install imagemagick

- app/components/spotlight/translations/subheading_component.html.erb
- app/components/spotlight/translations/subheading_component.rb
- app/views/spotlight/translations/_general.html.erb
- app/views/spotlight/translations/_metadata.html.erb
- app/views/spotlight/translations/_pages.html.erb
- app/views/spotlight/translations/_search_fields.html.erb
Backports https://github.com/projectblacklight/spotlight/pull/3329 to release-4.x
> Backport: Extract Translations::SubheadingComponent

- app/views/spotlight/admin_users/index.html.erb
Backport https://github.com/projectblacklight/spotlight/pull/3338 to release-4.x
> Backport: Fix float attempt on flex item

- app/assets/stylesheets/spotlight/_variables_bootstrap.scss
- lib/generators/spotlight/templates/spotlight.scss
backport https://github.com/projectblacklight/spotlight/pull/3341 to release-4.x
> Backport: Remove empty sass file #3341

- app/assets/stylesheets/spotlight/_browse.scss
Backports https://github.com/projectblacklight/spotlight/pull/3344 to release-4.x
> Backport: Change style on browse thubmnail design hover

- app/assets/stylesheets/spotlight/_header.scss
- app/views/shared/_masthead.html.erb
This allows the user to customize the markup without having to override css
> Add classes to the markup

- app/assets/stylesheets/spotlight/_header.scss
- app/views/shared/_masthead.html.erb
This allows the user to customize the markup without having to override css
> [Backport 4.x] Add classes to the markup

- app/assets/stylesheets/spotlight/_header.scss
- app/components/spotlight/title_component.html.erb
> have header title/subtitle link to home page

- app/views/layouts/spotlight/spotlight.html.erb
closes https://github.com/sul-dlss/exhibits/issues/2466
> change tab order to be more accessible

- app/assets/stylesheets/spotlight/_browse.scss
- app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss
- app/assets/stylesheets/spotlight/browse_group_categories_block.scss
Backports https://github.com/projectblacklight/spotlight/pull/3409 to release-4.x
> Backport: Adjust gradient and hover effect for browse cards

- app/assets/stylesheets/spotlight/_spotlight.scss
Fixes https://github.com/sul-dlss/exhibits/issues/2824
More clean-up. I don't remember the story for this one but it doesn't belong here (this is specific to v5, it is not in release-4.x).
> Remove Blacklight icon style

- app/assets/stylesheets/spotlight/_exhibit_admin.scss
> Set leaflet z-index to 950 so it appears behind autocomplete dropdown

- spec/services/spotlight/iiif_resource_resolver_spec.rb
backport https://github.com/projectblacklight/spotlight/pull/3437 to release-4.x
> [backport] Stop checking for specific error message

- app/assets/stylesheets/spotlight/_exhibit_admin.scss
backport https://github.com/projectblacklight/spotlight/pull/3438 to release-4.x
> [backport] Set leaflet z-index to 950 so it appears behind autocomplete dropdown

- app/views/spotlight/sir_trevor/blocks/_oembed_block.html.erb
Fixes https://github.com/sul-dlss/exhibits/issues/2857
> Fix embed layout so text will show up on the right if that is selected

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This PR is to add a GitHub PR template which will include a basic checklist of things for people to consider when opening a Pull Request. I am using the markdown in this PR so you can see how it will actually look if this is approved. Suggestions are welcome.
- Add/update tests
- Update documentation
- Test changes locally
- Reference the GitHub issue number
- Include screenshots to help illustrate any visual changes
> Introducing a GitHub PR template

- spec/controllers/spotlight/bulk_updates_controller_spec.rb
- spec/features/bulk_actions_spec.rb
- spec/jobs/spotlight/reindex_job_spec.rb
- spec/models/spotlight/resource_spec.rb
- spec/support/with_queue_adapter.rb
this fixes some intermittent test failures
advances #3538
> Remove acrobatics around queue_adapter

- spec/features/bulk_actions_spec.rb
- spec/spec_helper.rb
advances #3538
With these changes on my local env I go from 8 or 9 failing feature tests to 0 or 1.
> Make feature tests run faster on local environment

- Dockerfile
Use the latest version of Ruby
- Add/update tests
- Update documentation
- Test changes locally
- Reference the GitHub issue number
- Include screenshots to help illustrate any visual changes
> Update ruby image in Dockerfile
